# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class NewcarNewItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    brandid = scrapy.Field()
    brandname = scrapy.Field()
    fctlist = scrapy.Field()
    fctid = scrapy.Field()
    fctname = scrapy.Field()
    seriesplace = scrapy.Field()
    series_list = scrapy.Field()
    seriesid = scrapy.Field()
    seriesName = scrapy.Field()
    levelName = scrapy.Field()
    seriesState = scrapy.Field()
    url = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()



class PcautoItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    datasave = scrapy.Field()
    jsonsave = scrapy.Field()
    brandname= scrapy.Field()
    brandid = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    carid = scrapy.Field()
    salesdesc = scrapy.Field()
    price = scrapy.Field()
    level = scrapy.Field()
    salemonth = scrapy.Field()
    motor = scrapy.Field()
    method = scrapy.Field()
    maxps = scrapy.Field()
    maxnm = scrapy.Field()
    gear = scrapy.Field()
    bodystyle = scrapy.Field()
    lengthwh = scrapy.Field()
    wheel = scrapy.Field()
    maxspeed = scrapy.Field()
    accelerate = scrapy.Field()
    actualaccelerate = scrapy.Field()
    actualstop = scrapy.Field()
    petrol = scrapy.Field()
    warranty = scrapy.Field()
    type = scrapy.Field()
    length = scrapy.Field()
    width = scrapy.Field()
    height = scrapy.Field()
    wheel = scrapy.Field()
    frontwheel = scrapy.Field()
    backwheel = scrapy.Field()
    liftoff_distance = scrapy.Field()
    weight = scrapy.Field()
    doors = scrapy.Field()
    seats = scrapy.Field()
    fuelvolumn = scrapy.Field()
    baggage = scrapy.Field()
    maxbaggage = scrapy.Field()
    motortype = scrapy.Field()
    cylinder = scrapy.Field()
    method1 = scrapy.Field()
    maxps1 = scrapy.Field()
    maxpower = scrapy.Field()
    maxrpm = scrapy.Field()
    maxnm1 = scrapy.Field()
    maxtorque = scrapy.Field()
    lwv = scrapy.Field()
    lwvnumber = scrapy.Field()
    valve = scrapy.Field()
    compress = scrapy.Field()
    valve_gear = scrapy.Field()
    cylinder_diameter = scrapy.Field()
    cylinder_travel = scrapy.Field()
    motortechnique = scrapy.Field()
    fuletype = scrapy.Field()
    fulevolumn = scrapy.Field()
    fulemethod = scrapy.Field()
    cylinder_head_material = scrapy.Field()
    cylinder_body_material = scrapy.Field()
    emission = scrapy.Field()
    geardesc = scrapy.Field()
    gearnumber = scrapy.Field()
    geartype = scrapy.Field()
    driveway = scrapy.Field()
    frontgauge = scrapy.Field()
    backgauge = scrapy.Field()
    assistanttype = scrapy.Field()
    body_structure = scrapy.Field()
    frontbrake = scrapy.Field()
    backbrake = scrapy.Field()
    parking_brake_type = scrapy.Field()
    frontwheel = scrapy.Field()
    backwheel = scrapy.Field()
    sparewheel = scrapy.Field()
    approach_angle = scrapy.Field()
    departure_angle = scrapy.Field()
    ramp_angle = scrapy.Field()
    climbing_angle = scrapy.Field()
    liftoff_distance1 = scrapy.Field()
    turning_radius = scrapy.Field()
    wading_depth = scrapy.Field()
    minBtPrice = scrapy.Field()


class AutohomeItem(scrapy.Item):
    # define the fields for your item here like:
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    datasave = scrapy.Field()
    jsonsave = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    carid = scrapy.Field()
    salesdesc = scrapy.Field()
    price = scrapy.Field()
    factoryname = scrapy.Field()
    type = scrapy.Field()
    motor = scrapy.Field()
    gear = scrapy.Field()
    lengthwh = scrapy.Field()
    body = scrapy.Field()
    maxspeed = scrapy.Field()
    accelerate = scrapy.Field()
    actualaccelerate = scrapy.Field()
    actualstop = scrapy.Field()
    actualpetrol = scrapy.Field()
    petrol = scrapy.Field()
    actual_liftoff_distance = scrapy.Field()
    warranty = scrapy.Field()
    length = scrapy.Field()
    width = scrapy.Field()
    height = scrapy.Field()
    wheel = scrapy.Field()
    frontwheel = scrapy.Field()
    backwheel = scrapy.Field()
    liftoff_distance = scrapy.Field()
    weight = scrapy.Field()
    doors = scrapy.Field()
    seats = scrapy.Field()
    fuelvolumn = scrapy.Field()
    baggage = scrapy.Field()
    motortype = scrapy.Field()
    cylinder = scrapy.Field()
    output = scrapy.Field()
    method = scrapy.Field()
    lwv = scrapy.Field()
    lwvnumber = scrapy.Field()
    valve = scrapy.Field()
    compress = scrapy.Field()
    valve_gear = scrapy.Field()
    cylinder_diameter = scrapy.Field()
    cylinder_travel = scrapy.Field()
    maxps = scrapy.Field()
    maxpower = scrapy.Field()
    maxrpm = scrapy.Field()
    maxnm = scrapy.Field()
    maxtorque = scrapy.Field()
    motortechnique = scrapy.Field()
    fuletype = scrapy.Field()
    fulevolumn = scrapy.Field()
    fulemethod = scrapy.Field()
    cylinder_head_material = scrapy.Field()
    cylinder_body_material = scrapy.Field()
    emission = scrapy.Field()
    geardesc = scrapy.Field()
    gearnumber = scrapy.Field()
    geartype = scrapy.Field()
    driveway = scrapy.Field()
    frontgauge = scrapy.Field()
    backgauge = scrapy.Field()
    assistanttype = scrapy.Field()
    body_structure = scrapy.Field()
    frontbrake = scrapy.Field()
    backbrake = scrapy.Field()
    parking_brake_type = scrapy.Field()
    sparewheel = scrapy.Field()


class AutohomeItem_price(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    website = scrapy.Field()
    Key = scrapy.Field()
    prov_ID = scrapy.Field()
    prov_Name = scrapy.Field()
    prov_Pinyin = scrapy.Field()
    prov_Count = scrapy.Field()
    city_ID = scrapy.Field()
    city_Name = scrapy.Field()
    city_Pinyin = scrapy.Field()
    city_Count = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    shopname = scrapy.Field()
    shopid = scrapy.Field()
    tel = scrapy.Field()
    saleregion = scrapy.Field()
    picurl = scrapy.Field()
    vehilename = scrapy.Field()
    salespricerange = scrapy.Field()
    guidepricerange = scrapy.Field()
    vehilenameid = scrapy.Field()
    salesdesc = scrapy.Field()
    salesdescid = scrapy.Field()
    guideprice = scrapy.Field()
    guidesalesprice = scrapy.Field()
    salesprice = scrapy.Field()
    status = scrapy.Field()
    car_md5 = scrapy.Field()
    dealer_address = scrapy.Field()