# -*- coding: utf-8 -*-
import redis
import scrapy
import re
import time
import json
from pprint import pprint

# from .items import YouxinTestSpider Item

pool = redis.ConnectionPool(host='192.168.1.92', port=6379, db=10)
con = redis.Redis(connection_pool=pool)
c = con.client()


class YouxinTestSpider(scrapy.Spider):
    name = 'youxin_test'
    allowed_domains = ['xin.com']

    # start_urls = ['http://xin.com/']

    @classmethod
    def update_settings(cls, settings):
        settings.setdict(
            getattr(cls, 'custom_debug_settings' if getattr(cls, 'is_debug', False) else 'custom_settings', None) or {},
            priority='spider')

    def __init__(self, **kwargs):
        super(YouxinTestSpider, self).__init__(**kwargs)
        self.counts = 0
        self.city_list = ['https://www.xin.com/hefei/s/', 'https://www.xin.com/anqing/s/',
                          'https://www.xin.com/bengbu/s/', 'https://www.xin.com/fuyang/s/',
                          'https://www.xin.com/huaibei/s/', 'https://www.xin.com/huainan/s/',
                          'https://www.xin.com/luan/s/', 'https://www.xin.com/maanshan/s/',
                          'https://www.xin.com/tongling/s/', 'https://www.xin.com/wuhu/s/',
                          'https://www.xin.com/xuancheng/s/', 'https://www.xin.com/chuzhou/s/',
                          'https://www.xin.com/bozhou/s/', 'https://www.xin.com/huangshan/s/',
                          'https://www.xin.com/suzhouah/s/', 'https://www.xin.com/beijing/s/',
                          'https://www.xin.com/fuzhou/s/', 'https://www.xin.com/xiamen/s/',
                          'https://www.xin.com/longyan/s/', 'https://www.xin.com/zhangzhou/s/',
                          'https://www.xin.com/putian/s/', 'https://www.xin.com/quanzhou/s/',
                          'https://www.xin.com/nanping/s/', 'https://www.xin.com/ningde/s/',
                          'https://www.xin.com/sanming/s/', 'https://www.xin.com/lanzhou/s/',
                          'https://www.xin.com/dingxi/s/', 'https://www.xin.com/pingliang/s/',
                          'https://www.xin.com/jiuquan/s/', 'https://www.xin.com/qingyang/s/',
                          'https://www.xin.com/wuwei/s/', 'https://www.xin.com/tianshui/s/',
                          'https://www.xin.com/baiyin/s/', 'https://www.xin.com/longnan/s/',
                          'https://www.xin.com/guangzhou/s/', 'https://www.xin.com/shenzhen/s/',
                          'https://www.xin.com/zhuhai/s/', 'https://www.xin.com/dongguan/s/',
                          'https://www.xin.com/zhongshan/s/', 'https://www.xin.com/shantou/s/',
                          'https://www.xin.com/chaozhou/s/', 'https://www.xin.com/shaoguan/s/',
                          'https://www.xin.com/zhanjiang/s/', 'https://www.xin.com/zhaoqing/s/',
                          'https://www.xin.com/maoming/s/', 'https://www.xin.com/meizhou/s/',
                          'https://www.xin.com/foshan/s/', 'https://www.xin.com/huizhou/s/',
                          'https://www.xin.com/jiangmen/s/', 'https://www.xin.com/jieyang/s/',
                          'https://www.xin.com/qingyuan/s/', 'https://www.xin.com/yangjiang/s/',
                          'https://www.xin.com/heyuan/s/', 'https://www.xin.com/shanwei/s/',
                          'https://www.xin.com/nanning/s/', 'https://www.xin.com/liuzhou/s/',
                          'https://www.xin.com/guilin/s/', 'https://www.xin.com/beihai/s/',
                          'https://www.xin.com/baise/s/', 'https://www.xin.com/hezhou/s/',
                          'https://www.xin.com/hechi/s/', 'https://www.xin.com/guigang/s/',
                          'https://www.xin.com/yulin/s/', 'https://www.xin.com/qinzhou/s/',
                          'https://www.xin.com/wuzhou/s/', 'https://www.xin.com/fangchenggang/s/',
                          'https://www.xin.com/guiyang/s/', 'https://www.xin.com/zunyi/s/',
                          'https://www.xin.com/bijie/s/', 'https://www.xin.com/liupanshui/s/',
                          'https://www.xin.com/tongren/s/', 'https://www.xin.com/haikou/s/',
                          'https://www.xin.com/sanya/s/', 'https://www.xin.com/shijiazhuang/s/',
                          'https://www.xin.com/tangshan/s/', 'https://www.xin.com/xingtai/s/',
                          'https://www.xin.com/qinhuangdao/s/', 'https://www.xin.com/langfang/s/',
                          'https://www.xin.com/handan/s/', 'https://www.xin.com/hengshui/s/',
                          'https://www.xin.com/cangzhou/s/', 'https://www.xin.com/baoding/s/',
                          'https://www.xin.com/zhangjiakou/s/', 'https://www.xin.com/chengde/s/',
                          'https://www.xin.com/zhengzhou/s/', 'https://www.xin.com/luoyang/s/',
                          'https://www.xin.com/zhoukou/s/', 'https://www.xin.com/xinyang/s/',
                          'https://www.xin.com/xinxiang/s/', 'https://www.xin.com/shangqiu/s/',
                          'https://www.xin.com/sanmenxia/s/', 'https://www.xin.com/puyang/s/',
                          'https://www.xin.com/nanyang/s/', 'https://www.xin.com/luohe/s/',
                          'https://www.xin.com/jiaozuo/s/', 'https://www.xin.com/kaifeng/s/',
                          'https://www.xin.com/anyang/s/', 'https://www.xin.com/dezhou/s/',
                          'https://www.xin.com/hebi/s/', 'https://www.xin.com/pingdingshan/s/',
                          'https://www.xin.com/zhumadian/s/', 'https://www.xin.com/xuchang/s/',
                          'https://www.xin.com/haerbin/s/', 'https://www.xin.com/daqing/s/',
                          'https://www.xin.com/qiqihaer/s/', 'https://www.xin.com/jiamusi/s/',
                          'https://www.xin.com/jixi/s/', 'https://www.xin.com/mudanjiang/s/',
                          'https://www.xin.com/qitaihe/s/', 'https://www.xin.com/yichun/s/',
                          'https://www.xin.com/heihe/s/', 'https://www.xin.com/suihua/s/',
                          'https://www.xin.com/shuangyashan/s/', 'https://www.xin.com/wuhan/s/',
                          'https://www.xin.com/shiyan/s/', 'https://www.xin.com/xiangyang/s/',
                          'https://www.xin.com/suizhou/s/', 'https://www.xin.com/xiantao/s/',
                          'https://www.xin.com/tianmenshi/s/', 'https://www.xin.com/yichang/s/',
                          'https://www.xin.com/huangshi/s/', 'https://www.xin.com/jingmen/s/',
                          'https://www.xin.com/jingzhou/s/', 'https://www.xin.com/huanggang/s/',
                          'https://www.xin.com/ezhou/s/', 'https://www.xin.com/xianning/s/',
                          'https://www.xin.com/xiaogan/s/', 'https://www.xin.com/qianjiang/s/',
                          'https://www.xin.com/changsha/s/', 'https://www.xin.com/chenzhou/s/',
                          'https://www.xin.com/changde/s/', 'https://www.xin.com/hengyang/s/',
                          'https://www.xin.com/huaihua/s/', 'https://www.xin.com/loudi/s/',
                          'https://www.xin.com/zhuzhou/s/', 'https://www.xin.com/yueyang/s/',
                          'https://www.xin.com/xiangtan/s/', 'https://www.xin.com/shaoyang/s/',
                          'https://www.xin.com/yiyang/s/', 'https://www.xin.com/zhangjiajie/s/',
                          'https://www.xin.com/changchun/s/', 'https://www.xin.com/jilin/s/',
                          'https://www.xin.com/tonghua/s/', 'https://www.xin.com/liaoyuan/s/',
                          'https://www.xin.com/baishan/s/', 'https://www.xin.com/baicheng/s/',
                          'https://www.xin.com/songyuan/s/', 'https://www.xin.com/nanjing/s/',
                          'https://www.xin.com/suzhou/s/', 'https://www.xin.com/wuxi/s/',
                          'https://www.xin.com/changzhou/s/', 'https://www.xin.com/huaian/s/',
                          'https://www.xin.com/lianyungang/s/', 'https://www.xin.com/nantong/s/',
                          'https://www.xin.com/yancheng/s/', 'https://www.xin.com/yangzhou/s/',
                          'https://www.xin.com/zhenjiang/s/', 'https://www.xin.com/taizhou/s/',
                          'https://www.xin.com/xuzhou/s/', 'https://www.xin.com/suqian/s/',
                          'https://www.xin.com/nanchang/s/', 'https://www.xin.com/shangrao/s/',
                          'https://www.xin.com/pingxiang/s/', 'https://www.xin.com/xinyu/s/',
                          'https://www.xin.com/yichunjx/s/', 'https://www.xin.com/jiujiang/s/',
                          'https://www.xin.com/ganzhou/s/', 'https://www.xin.com/jian/s/',
                          'https://www.xin.com/jingdezhen/s/', 'https://www.xin.com/fuzhoujx/s/',
                          'https://www.xin.com/siping/s/', 'https://www.xin.com/shenyang/s/',
                          'https://www.xin.com/dandong/s/', 'https://www.xin.com/fushun/s/',
                          'https://www.xin.com/fuxin/s/', 'https://www.xin.com/huludao/s/',
                          'https://www.xin.com/chaoyang/s/', 'https://www.xin.com/dalian/s/',
                          'https://www.xin.com/benxi/s/', 'https://www.xin.com/anshan/s/',
                          'https://www.xin.com/jinzhou/s/', 'https://www.xin.com/liaoyang/s/',
                          'https://www.xin.com/yingkou/s/', 'https://www.xin.com/panjin/s/',
                          'https://www.xin.com/tieling/s/', 'https://www.xin.com/huhehaote/s/',
                          'https://www.xin.com/baotou/s/', 'https://www.xin.com/chifeng/s/',
                          'https://www.xin.com/tongliao/s/', 'https://www.xin.com/wuhai/s/',
                          'https://www.xin.com/eerduosi/s/', 'https://www.xin.com/hulunbeier/s/',
                          'https://www.xin.com/xilinguolemeng/s/', 'https://www.xin.com/wulanchabu/s/',
                          'https://www.xin.com/alashanmeng/s/', 'https://www.xin.com/yinchuan/s/',
                          'https://www.xin.com/wuzhong/s/', 'https://www.xin.com/guyuan/s/',
                          'https://www.xin.com/shizuishan/s/', 'https://www.xin.com/xining/s/',
                          'https://www.xin.com/haidong/s/', 'https://www.xin.com/jinan/s/',
                          'https://www.xin.com/qingdao/s/', 'https://www.xin.com/yantai/s/',
                          'https://www.xin.com/weihai/s/', 'https://www.xin.com/weifang/s/',
                          'https://www.xin.com/taian/s/', 'https://www.xin.com/zaozhuang/s/',
                          'https://www.xin.com/zibo/s/', 'https://www.xin.com/dongying/s/',
                          'https://www.xin.com/heze/s/', 'https://www.xin.com/binzhou/s/',
                          'https://www.xin.com/liaocheng/s/', 'https://www.xin.com/linyi/s/',
                          'https://www.xin.com/jiningsd/s/', 'https://www.xin.com/rizhao/s/',
                          'https://www.xin.com/laiwu/s/', 'https://www.xin.com/taiyuan/s/',
                          'https://www.xin.com/datong/s/', 'https://www.xin.com/jincheng/s/',
                          'https://www.xin.com/jinzhong/s/', 'https://www.xin.com/linfen/s/',
                          'https://www.xin.com/changzhi/s/', 'https://www.xin.com/yuncheng/s/',
                          'https://www.xin.com/xinzhou/s/', 'https://www.xin.com/yangquan/s/',
                          'https://www.xin.com/shuozhou/s/', 'https://www.xin.com/lvliang/s/',
                          'https://www.xin.com/xian/s/', 'https://www.xin.com/xianyang/s/',
                          'https://www.xin.com/weinan/s/', 'https://www.xin.com/yulinsx/s/',
                          'https://www.xin.com/baoji/s/', 'https://www.xin.com/ankang/s/',
                          'https://www.xin.com/hanzhong/s/', 'https://www.xin.com/yanan/s/',
                          'https://www.xin.com/tongchuan/s/', 'https://www.xin.com/shangluo/s/',
                          'https://www.xin.com/shanghai/s/', 'https://www.xin.com/chengdu/s/',
                          'https://www.xin.com/mianyang/s/', 'https://www.xin.com/suining/s/',
                          'https://www.xin.com/panzhihua/s/', 'https://www.xin.com/yibin/s/',
                          'https://www.xin.com/zigong/s/', 'https://www.xin.com/guangyuan/s/',
                          'https://www.xin.com/deyang/s/', 'https://www.xin.com/leshan/s/',
                          'https://www.xin.com/nanchong/s/', 'https://www.xin.com/meishan/s/',
                          'https://www.xin.com/luzhou/s/', 'https://www.xin.com/neijiang/s/',
                          'https://www.xin.com/dazhou/s/', 'https://www.xin.com/guangan/s/',
                          'https://www.xin.com/tianjin/s/', 'https://www.xin.com/shannanshi/s/',
                          'https://www.xin.com/wulumuqi/s/', 'https://www.xin.com/hami/s/',
                          'https://www.xin.com/tulufan/s/', 'https://www.xin.com/shihezishi/s/',
                          'https://www.xin.com/kunming/s/', 'https://www.xin.com/yuxi/s/',
                          'https://www.xin.com/qujing/s/', 'https://www.xin.com/baoshanshi/s/',
                          'https://www.xin.com/zhaotong/s/', 'https://www.xin.com/lijiang/s/',
                          'https://www.xin.com/hangzhou/s/', 'https://www.xin.com/ningbo/s/',
                          'https://www.xin.com/wenzhou/s/', 'https://www.xin.com/jiaxing/s/',
                          'https://www.xin.com/jinhua/s/', 'https://www.xin.com/lishui/s/',
                          'https://www.xin.com/huzhou/s/', 'https://www.xin.com/quzhou/s/',
                          'https://www.xin.com/taizhouzj/s/', 'https://www.xin.com/shaoxing/s/',
                          'https://www.xin.com/zhoushan/s/', 'https://www.xin.com/chongqing/s/',
                          'https://www.xin.com/bayannaoer/s/', 'https://www.xin.com/zhongwei/s/',
                          'https://www.xin.com/yanbianchaoxianzuzizhizhou/s/',
                          'https://www.xin.com/enshitujiazuzizhizhou/s/', 'https://www.xin.com/chongzuo/s/',
                          'https://www.xin.com/liangshanyizuzizhizhou/s/', 'https://www.xin.com/qianxinan/s/',
                          'https://www.xin.com/qiandongnan/s/', 'https://www.xin.com/qiannanbuyizu/s/',
                          'https://www.xin.com/chuxiong/s/', 'https://www.xin.com/honghehanizu/s/',
                          'https://www.xin.com/wenshanzhuangzuzizhizhou/s/',
                          'https://www.xin.com/xishuangbannadaizuzizhizhou/s/',
                          'https://www.xin.com/dalibaizuzizhizhou/s/',
                          'https://www.xin.com/dehongdaizujingpozuzizhizhou/s/',
                          'https://www.xin.com/linxiahuizuzizhizhou/s/', 'https://www.xin.com/huangnan/s/',
                          'https://www.xin.com/changjihuizuzizhizhou/s/', 'https://www.xin.com/bayinguoleng/s/',
                          'https://www.xin.com/akesudiqu/s/', 'https://www.xin.com/yilihasakezizhizhou/s/']
        self.brand_list = ['https://www.xin.com/shanghai/yaxing/', 'https://www.xin.com/shanghai/ruichixinnenyuan/',
                           'https://www.xin.com/shanghai/localmotors/', 'https://www.xin.com/shanghai/biaozhi/',
                           'https://www.xin.com/shanghai/jianglingjituanxinnenyuan/',
                           'https://www.xin.com/shanghai/saibao/', 'https://www.xin.com/shanghai/zhongshun/',
                           'https://www.xin.com/shanghai/dongfengfengxing/',
                           'https://www.xin.com/shanghai/oushangqiche/', 'https://www.xin.com/shanghai/alpina/',
                           'https://www.xin.com/shanghai/kaibaihe/', 'https://www.xin.com/shanghai/guanzhi/',
                           'https://www.xin.com/shanghai/maibahe/', 'https://www.xin.com/shanghai/liebaoqiche/',
                           'https://www.xin.com/shanghai/juntianqiche/', 'https://www.xin.com/shanghai/luofuhate/',
                           'https://www.xin.com/shanghai/lite/', 'https://www.xin.com/shanghai/beiqixinnenyuan/',
                           'https://www.xin.com/shanghai/zhonghua/', 'https://www.xin.com/shanghai/aerfaluomiou/',
                           'https://www.xin.com/shanghai/xiaopengqiche/',
                           'https://www.xin.com/shanghai/polestarjixing/', 'https://www.xin.com/shanghai/qiantu/',
                           'https://www.xin.com/shanghai/leikesasi/', 'https://www.xin.com/shanghai/yingfeinidi/',
                           'https://www.xin.com/shanghai/dazhong/', 'https://www.xin.com/shanghai/kelaisile/',
                           'https://www.xin.com/shanghai/sabo/', 'https://www.xin.com/shanghai/beiqizhizao/',
                           'https://www.xin.com/shanghai/jeep/', 'https://www.xin.com/shanghai/yutongkeche/',
                           'https://www.xin.com/shanghai/kaimaqiche/', 'https://www.xin.com/shanghai/lifan/',
                           'https://www.xin.com/shanghai/siweiqiche/', 'https://www.xin.com/shanghai/lutesi/',
                           'https://www.xin.com/shanghai/woerwo/', 'https://www.xin.com/shanghai/shuanglong/',
                           'https://www.xin.com/shanghai/xingtu/', 'https://www.xin.com/shanghai/sitech/',
                           'https://www.xin.com/shanghai/kenisaike/', 'https://www.xin.com/shanghai/weiziman/',
                           'https://www.xin.com/shanghai/hanma/', 'https://www.xin.com/shanghai/hanlongqiche/',
                           'https://www.xin.com/shanghai/huakai/', 'https://www.xin.com/shanghai/guangqixinnenyuan/',
                           'https://www.xin.com/shanghai/ktm/', 'https://www.xin.com/shanghai/yujie/',
                           'https://www.xin.com/shanghai/xiyate/', 'https://www.xin.com/shanghai/yongyuan/',
                           'https://www.xin.com/shanghai/tongtian/', 'https://www.xin.com/shanghai/beijing/',
                           'https://www.xin.com/shanghai/asidunmading/', 'https://www.xin.com/shanghai/lianhua/',
                           'https://www.xin.com/shanghai/chenggong/', 'https://www.xin.com/shanghai/jinbei/',
                           'https://www.xin.com/shanghai/futianchengyongche/', 'https://www.xin.com/shanghai/fengtian/',
                           'https://www.xin.com/shanghai/jieda/', 'https://www.xin.com/shanghai/hafei/',
                           'https://www.xin.com/shanghai/richan/', 'https://www.xin.com/shanghai/beiqidaoda/',
                           'https://www.xin.com/shanghai/oula/', 'https://www.xin.com/shanghai/sanling/',
                           'https://www.xin.com/shanghai/tesila/', 'https://www.xin.com/shanghai/wey/',
                           'https://www.xin.com/shanghai/changhe/', 'https://www.xin.com/shanghai/guojizhijun/',
                           'https://www.xin.com/shanghai/spirra/', 'https://www.xin.com/shanghai/weilin/',
                           'https://www.xin.com/shanghai/yusheng/', 'https://www.xin.com/shanghai/yulu/',
                           'https://www.xin.com/shanghai/jiulong/', 'https://www.xin.com/shanghai/haima/',
                           'https://www.xin.com/shanghai/meiya/', 'https://www.xin.com/shanghai/dianka/',
                           'https://www.xin.com/shanghai/guangqichuanqi/', 'https://www.xin.com/shanghai/jinlong/',
                           'https://www.xin.com/shanghai/lufeng/', 'https://www.xin.com/shanghai/anchi/',
                           'https://www.xin.com/shanghai/linken/', 'https://www.xin.com/shanghai/huapu/',
                           'https://www.xin.com/shanghai/qirui/', 'https://www.xin.com/shanghai/tangjunqiche/',
                           'https://www.xin.com/shanghai/dongfeng/', 'https://www.xin.com/shanghai/tongbao/',
                           'https://www.xin.com/shanghai/shangqidatong/', 'https://www.xin.com/shanghai/qichen/',
                           'https://www.xin.com/shanghai/jinlv/', 'https://www.xin.com/shanghai/yiqi/',
                           'https://www.xin.com/shanghai/changan/', 'https://www.xin.com/shanghai/dachengqiche/',
                           'https://www.xin.com/shanghai/guanggang/', 'https://www.xin.com/shanghai/baoshijie/',
                           'https://www.xin.com/shanghai/baowo/', 'https://www.xin.com/shanghai/huaqi/',
                           'https://www.xin.com/shanghai/dafa/', 'https://www.xin.com/shanghai/beijingqiche/',
                           'https://www.xin.com/shanghai/nanjingjinlong/', 'https://www.xin.com/shanghai/lingtuqiche/',
                           'https://www.xin.com/shanghai/shanqitongjia/', 'https://www.xin.com/shanghai/tengshi/',
                           'https://www.xin.com/shanghai/mashaladi/', 'https://www.xin.com/shanghai/tianjiqiche/',
                           'https://www.xin.com/shanghai/bisuqiche/', 'https://www.xin.com/shanghai/dongfengruitaite/',
                           'https://www.xin.com/shanghai/huaxiang/', 'https://www.xin.com/shanghai/fuqiqiteng/',
                           'https://www.xin.com/shanghai/changcheng/', 'https://www.xin.com/shanghai/guangqijiao/',
                           'https://www.xin.com/shanghai/xiandai/', 'https://www.xin.com/shanghai/jiliqiche/',
                           'https://www.xin.com/shanghai/kangdiquanqiuying/', 'https://www.xin.com/shanghai/lingke/',
                           'https://www.xin.com/shanghai/mazida/', 'https://www.xin.com/shanghai/yundu/',
                           'https://www.xin.com/shanghai/zhongou/', 'https://www.xin.com/shanghai/hafu/',
                           'https://www.xin.com/shanghai/leinuo/', 'https://www.xin.com/shanghai/dayu/',
                           'https://www.xin.com/shanghai/bieke/', 'https://www.xin.com/shanghai/aichi/',
                           'https://www.xin.com/shanghai/beiqiweiwang/', 'https://www.xin.com/shanghai/huasong/',
                           'https://www.xin.com/shanghai/oubao/', 'https://www.xin.com/shanghai/ruiqi/',
                           'https://www.xin.com/shanghai/weimaqiche/', 'https://www.xin.com/shanghai/bujiadi/',
                           'https://www.xin.com/shanghai/huanghai/', 'https://www.xin.com/shanghai/dongfengfengdu/',
                           'https://www.xin.com/shanghai/jianghuai/', 'https://www.xin.com/shanghai/jiebao/',
                           'https://www.xin.com/shanghai/wuling/', 'https://www.xin.com/shanghai/jiangling/',
                           'https://www.xin.com/shanghai/mogen/', 'https://www.xin.com/shanghai/daoqi/',
                           'https://www.xin.com/shanghai/gmc/', 'https://www.xin.com/shanghai/benteng/',
                           'https://www.xin.com/shanghai/huatai/', 'https://www.xin.com/shanghai/luofu/',
                           'https://www.xin.com/shanghai/zhongtai/', 'https://www.xin.com/shanghai/qingnianqiche/',
                           'https://www.xin.com/shanghai/zhongxing/', 'https://www.xin.com/shanghai/nazhaqiche/',
                           'https://www.xin.com/shanghai/kawei/', 'https://www.xin.com/shanghai/yemaqiche/',
                           'https://www.xin.com/shanghai/zhinuo/', 'https://www.xin.com/shanghai/ludifangzhou/',
                           'https://www.xin.com/shanghai/aodi/', 'https://www.xin.com/shanghai/hongxingqiche/',
                           'https://www.xin.com/shanghai/kaiyi/', 'https://www.xin.com/shanghai/huataixinnenyuan/',
                           'https://www.xin.com/shanghai/xinyuan/', 'https://www.xin.com/shanghai/jinchengqiche/',
                           'https://www.xin.com/shanghai/kairui/', 'https://www.xin.com/shanghai/huabei/',
                           'https://www.xin.com/shanghai/mini/', 'https://www.xin.com/shanghai/sihao/',
                           'https://www.xin.com/shanghai/guangqijituan/', 'https://www.xin.com/shanghai/mingjue/',
                           'https://www.xin.com/shanghai/hanteng/', 'https://www.xin.com/shanghai/nanqi/',
                           'https://www.xin.com/shanghai/taikate/', 'https://www.xin.com/shanghai/linian/',
                           'https://www.xin.com/shanghai/kasheng/', 'https://www.xin.com/shanghai/binli/',
                           'https://www.xin.com/shanghai/lada/', 'https://www.xin.com/shanghai/dongnan/',
                           'https://www.xin.com/shanghai/kaersen/', 'https://www.xin.com/shanghai/leiding/',
                           'https://www.xin.com/shanghai/shuixing/', 'https://www.xin.com/shanghai/xinkai/',
                           'https://www.xin.com/shanghai/beiqihuansu/', 'https://www.xin.com/shanghai/sailin/',
                           'https://www.xin.com/shanghai/benchi/', 'https://www.xin.com/shanghai/xuefulan/',
                           'https://www.xin.com/shanghai/wanfeng/', 'https://www.xin.com/shanghai/luhu/',
                           'https://www.xin.com/shanghai/yiqilinghe/', 'https://www.xin.com/shanghai/sikeda/',
                           'https://www.xin.com/shanghai/rongdazhizao/', 'https://www.xin.com/shanghai/futian/',
                           'https://www.xin.com/shanghai/jietu/', 'https://www.xin.com/shanghai/acschnitzer/',
                           'https://www.xin.com/shanghai/xindadi/', 'https://www.xin.com/shanghai/dongfengfengshen/',
                           'https://www.xin.com/shanghai/fudi/', 'https://www.xin.com/shanghai/sibalu/',
                           'https://www.xin.com/shanghai/laosilaisi/', 'https://www.xin.com/shanghai/babosi/',
                           'https://www.xin.com/shanghai/qiya/', 'https://www.xin.com/shanghai/falali/',
                           'https://www.xin.com/shanghai/zhidou/', 'https://www.xin.com/shanghai/feiyate/',
                           'https://www.xin.com/shanghai/sidataike/', 'https://www.xin.com/shanghai/lingmu/',
                           'https://www.xin.com/shanghai/weichaiyingzhi/', 'https://www.xin.com/shanghai/lingpaoqiche/',
                           'https://www.xin.com/shanghai/baolong/', 'https://www.xin.com/shanghai/laolunshi/',
                           'https://www.xin.com/shanghai/nazhijie/', 'https://www.xin.com/shanghai/yunque/',
                           'https://www.xin.com/shanghai/dongfengxiaokang/', 'https://www.xin.com/shanghai/huayang/',
                           'https://www.xin.com/shanghai/lixiang/', 'https://www.xin.com/shanghai/hangtian/',
                           'https://www.xin.com/shanghai/haige/', 'https://www.xin.com/shanghai/xuetielong/',
                           'https://www.xin.com/shanghai/shuanghuan/',
                           'https://www.xin.com/shanghai/dongfengfengguang/', 'https://www.xin.com/shanghai/fute/',
                           'https://www.xin.com/shanghai/biyadi/', 'https://www.xin.com/shanghai/weilai/',
                           'https://www.xin.com/shanghai/dadi/', 'https://www.xin.com/shanghai/nanjunqiche/',
                           'https://www.xin.com/shanghai/hengtian/', 'https://www.xin.com/shanghai/zhongyu/',
                           'https://www.xin.com/shanghai/guojinqiche/', 'https://www.xin.com/shanghai/shijue/',
                           'https://www.xin.com/shanghai/tianma/', 'https://www.xin.com/shanghai/yiweike/',
                           'https://www.xin.com/shanghai/weichaiqiche/', 'https://www.xin.com/shanghai/baoqiqiche/',
                           'https://www.xin.com/shanghai/hongqi/',
                           'https://www.xin.com/shanghai/jianglingjituanqingqi/',
                           'https://www.xin.com/shanghai/yunbao/', 'https://www.xin.com/shanghai/changanqingxingche/',
                           'https://www.xin.com/shanghai/heibao/', 'https://www.xin.com/shanghai/beijingqingxing/',
                           'https://www.xin.com/shanghai/jiangnan/', 'https://www.xin.com/shanghai/qiaozhibadun/',
                           'https://www.xin.com/shanghai/siming/', 'https://www.xin.com/shanghai/smart/',
                           'https://www.xin.com/shanghai/baoma/', 'https://www.xin.com/shanghai/ruhu/',
                           'https://www.xin.com/shanghai/fisker/', 'https://www.xin.com/shanghai/huizhong/',
                           'https://www.xin.com/shanghai/ds/', 'https://www.xin.com/shanghai/wushiling/',
                           'https://www.xin.com/shanghai/kaidilake/', 'https://www.xin.com/shanghai/lanbojini/',
                           'https://www.xin.com/shanghai/ouge/', 'https://www.xin.com/shanghai/maikailun/',
                           'https://www.xin.com/shanghai/ankai/', 'https://www.xin.com/shanghai/changanoushang/',
                           'https://www.xin.com/shanghai/xinbaojun/', 'https://www.xin.com/shanghai/baojun/',
                           'https://www.xin.com/shanghai/junmaqiche/', 'https://www.xin.com/shanghai/rongwei/',
                           'https://www.xin.com/shanghai/pajiani/', 'https://www.xin.com/shanghai/duoshixing/',
                           'https://www.xin.com/shanghai/bentian/', 'https://www.xin.com/shanghai/xinte/']
        self.city_code_dic = {'1001': '郑州',
 '1002': '洛阳',
 '1003': '周口',
 '1004': '信阳',
 '1005': '新乡',
 '1006': '商丘',
 '1007': '三门峡',
 '1008': '濮阳',
 '1009': '南阳',
 '101': '合肥',
 '1010': '漯河',
 '1011': '焦作',
 '1013': '开封',
 '1014': '安阳',
 '1015': '德州',
 '1016': '鹤壁',
 '1018': '平顶山',
 '102': '安庆',
 '1021': '驻马店',
 '1023': '许昌',
 '103': '蚌埠',
 '106': '阜阳',
 '107': '淮北',
 '108': '淮南',
 '109': '六安',
 '110': '马鞍山',
 '1101': '哈尔滨',
 '1102': '大庆',
 '1103': '齐齐哈尔',
 '1106': '佳木斯',
 '1107': '鸡西',
 '1108': '牡丹江',
 '1109': '七台河',
 '1112': '伊春',
 '1113': '黑河',
 '1116': '绥化',
 '1118': '双鸭山',
 '113': '铜陵',
 '114': '芜湖',
 '115': '宣城',
 '116': '滁州',
 '117': '亳州',
 '118': '黄山',
 '120': '宿州',
 '1201': '武汉',
 '1202': '十堰',
 '1203': '襄阳',
 '1204': '随州',
 '1205': '仙桃',
 '1206': '天门市',
 '1207': '宜昌',
 '1208': '黄石',
 '1209': '荆门',
 '1210': '荆州',
 '1214': '黄冈',
 '1216': '鄂州',
 '1217': '咸宁',
 '1218': '孝感',
 '1219': '潜江',
 '1301': '长沙',
 '1302': '郴州',
 '1303': '常德',
 '1304': '衡阳',
 '1305': '怀化',
 '1306': '娄底',
 '1307': '株洲',
 '1308': '岳阳',
 '1309': '湘潭',
 '1310': '邵阳',
 '1313': '益阳',
 '1315': '张家界市',
 '1401': '长春',
 '1402': '吉林',
 '1403': '通化',
 '1405': '辽源',
 '1406': '白山',
 '1412': '白城',
 '1415': '松原',
 '1501': '南京',
 '1502': '苏州',
 '1503': '无锡',
 '1505': '常州',
 '1507': '淮安',
 '1510': '连云港',
 '1511': '南通',
 '1512': '盐城',
 '1513': '扬州',
 '1515': '镇江',
 '1517': '泰州',
 '1518': '徐州',
 '1520': '宿迁',
 '1601': '南昌',
 '1602': '上饶',
 '1603': '萍乡',
 '1604': '新余',
 '1605': '宜春',
 '1606': '九江',
 '1607': '赣州',
 '1609': '吉安',
 '1612': '景德镇',
 '1613': '抚州',
 '1616': '四平',
 '1701': '沈阳',
 '1702': '丹东',
 '1703': '抚顺',
 '1704': '阜新',
 '1705': '葫芦岛',
 '1707': '朝阳',
 '1708': '大连',
 '1709': '本溪',
 '1710': '鞍山',
 '1711': '锦州',
 '1713': '辽阳',
 '1714': '营口',
 '1716': '盘锦',
 '1717': '铁岭',
 '1801': '呼和浩特',
 '1802': '包头',
 '1803': '赤峰',
 '1804': '通辽',
 '1805': '乌海',
 '1808': '鄂尔多斯',
 '1812': '呼伦贝尔',
 '1817': '锡林郭勒盟',
 '1819': '乌兰察布',
 '1820': '阿拉善盟',
 '1901': '银川',
 '1902': '吴忠',
 '1903': '固原',
 '1904': '石嘴山',
 '2001': '西宁',
 '2004': '海东',
 '201': '北京',
 '2101': '济南',
 '2102': '青岛',
 '2103': '烟台',
 '2104': '威海',
 '2105': '潍坊',
 '2106': '泰安',
 '2107': '枣庄',
 '2109': '淄博',
 '2110': '东营',
 '2112': '菏泽',
 '2113': '滨州',
 '2114': '聊城',
 '2117': '临沂',
 '2118': '济宁',
 '2120': '日照',
 '2132': '莱芜',
 '2201': '太原',
 '2202': '大同',
 '2203': '晋城',
 '2204': '晋中',
 '2205': '临汾',
 '2206': '长治',
 '2207': '运城',
 '2210': '忻州',
 '2218': '阳泉',
 '2219': '朔州',
 '2220': '吕梁',
 '222400': '延边朝鲜族自治州',
 '2301': '西安',
 '2302': '咸阳',
 '2303': '渭南',
 '2304': '榆林',
 '2305': '宝鸡',
 '2306': '安康',
 '2307': '汉中',
 '2308': '延安',
 '2310': '铜川',
 '2311': '商洛',
 '2401': '上海',
 '2501': '成都',
 '2502': '绵阳',
 '2503': '遂宁',
 '2504': '攀枝花市',
 '2506': '宜宾',
 '2508': '自贡',
 '2510': '广元',
 '2511': '德阳',
 '2512': '乐山',
 '2513': '南充',
 '2514': '眉山',
 '2517': '泸州',
 '2519': '内江',
 '2522': '达州',
 '2523': '广安',
 '2601': '天津',
 '2704': '山南市',
 '2801': '乌鲁木齐',
 '2806': '哈密',
 '2807': '吐鲁番',
 '2810': '石河子市',
 '2901': '昆明',
 '2902': '玉溪',
 '2903': '曲靖',
 '2907': '保山市',
 '2918': '昭通',
 '2924': '丽江',
 '3001': '杭州',
 '3002': '宁波',
 '3003': '温州',
 '3005': '嘉兴',
 '3006': '金华',
 '3009': '丽水',
 '301': '福州',
 '3011': '湖州',
 '3012': '衢州',
 '3015': '台州',
 '3016': '绍兴',
 '302': '厦门',
 '3020': '舟山',
 '303': '龙岩',
 '305': '漳州',
 '306': '莆田',
 '307': '泉州',
 '3101': '重庆',
 '3110': '巴彦淖尔',
 '3111': '中卫',
 '314': '南平',
 '315': '宁德',
 '318': '三明',
 '401': '兰州',
 '402': '定西',
 '405': '平凉',
 '409': '酒泉',
 '410': '张掖',
 '411': '庆阳',
 '412': '武威',
 '415': '天水',
 '416': '白银',
 '417': '陇南',
 '422800': '恩施土家族苗族自治州',
 '451400': '崇左',
 '501': '广州',
 '502': '深圳',
 '503': '珠海',
 '504': '东莞',
 '505': '中山',
 '507': '汕头',
 '510': '潮州',
 '511': '韶关',
 '513': '湛江',
 '513400': '凉山彝族自治州',
 '514': '肇庆',
 '515': '茂名',
 '516': '梅州',
 '518': '佛山',
 '520': '惠州',
 '521': '江门',
 '522': '揭阳',
 '522300': '黔西南布依族苗族自治州',
 '522600': '黔东南苗族侗族自治州',
 '522700': '黔南布依族苗族自治州',
 '524': '清远',
 '532': '阳江',
 '532300': '楚雄彝族自治州',
 '532500': '红河哈尼族彝族自治州',
 '532600': '文山壮族苗族自治州',
 '532800': '西双版纳傣族自治州',
 '532900': '大理白族自治州',
 '533100': '德宏傣族景颇族自治州',
 '535': '河源',
 '550': '汕尾',
 '601': '南宁',
 '602': '柳州',
 '603': '桂林',
 '604': '北海',
 '605': '百色',
 '606': '贺州',
 '607': '河池',
 '608': '贵港',
 '610': '玉林',
 '612': '钦州',
 '613': '梧州',
 '618': '防城港',
 '622900': '临夏回族自治州',
 '632300': '黄南藏族自治州',
 '632500': '海南藏族自治州',
 '632700': '玉树藏族自治州',
 '632800': '海西蒙古族藏族自治州',
 '652300': '昌吉回族自治州',
 '652800': '巴音郭楞蒙古自治州',
 '652900': '阿克苏地区',
 '653100': '喀什地区',
 '654000': '伊犁哈萨克自治州',
 '701': '贵阳',
 '702': '遵义',
 '706': '毕节',
 '708': '六盘水',
 '710': '铜仁',
 '801': '海口',
 '803': '三亚',
 '901': '石家庄',
 '902': '唐山',
 '903': '邢台',
 '905': '秦皇岛',
 '906': '廊坊',
 '907': '邯郸',
 '908': '衡水',
 '909': '沧州',
 '910': '保定',
 '911': '张家口',
 '912': '承德'}


        self.c = con.client()
        self.drop_num = 0
        self.all_num = 0
        self.fail_url = []

    is_debug = True
    custom_debug_settings = {
        'MYSQL_SERVER': '192.168.1.94',
        'MYSQL_DB': 'usedcar_update',
        'MYSQL_TABLE': 'youxin_city',
        'WEBSITE': 'youxin',
        'CrawlCar_Num': 1000000,
        'CONCURRENT_REQUESTS': 8,
        'DOWNLOAD_DELAY': 0,
        'RANDOMIZE_DOWNLOAD_DELAY': True,
        'REDIS_URL': 'redis://192.168.1.92:6379/15',
        'DOWNLOAD_TIMEOUT': 5,
        'RETRY_ENABLED': True,
        'RETRY_TIMES': 3,
        'COOKIES_ENABLED': True,
        'SCHEDULER_PERSIST': False,
        'DOWNLOADER_MIDDLEWARES': {
            'usedcar_new.middlewares.ProxyMiddleware': 700,
            # 'usedcar_new.middlewares.MoGuProxyMiddleware': 701,
            # 'usedcar_new.middlewares.SeleniumIPMiddleware': 701,
            # 'usedcar_new.middlewares.MyproxiesSpiderMiddleware': 701,
        },
        'ITEM_PIPELINES': {
            'usedcar_new.pipelines.GanjiPipeline': 300,
        },
    }

    def start_requests(self):
        url = 'https://www.xin.com/apis/Ajax_common/get_home_city/'
        yield scrapy.Request(
            url=url,
        )

    def parse(self, response):
        data = json.loads(response.text)
        city_data = data["data"]['city_all']
        city_code_dic = {}
        
        for k, v in city_data.items():
            city_code_dic[k] = v["cityname"]
        url = 'https://www.xin.com/shanghai/s/'
        url_list = ["https://www.xin.com/shanghai/i5/","https://www.xin.com/shanghai/i6/", "https://www.xin.com/shanghai/i7/"]
        for url in url_list:
        # pprint(city_code_dic)
            yield scrapy.Request(
                url=url,
                callback=self.parse_list,
                meta={"city_dic": self.city_code_dic}
            )

    def parse_list(self, response):
        city_code_list = response.meta["city_dic"]
        if 'arg1' in response.text:
            self.drop_num += 1
            print("*" * 100)
            self.fail_url.append(response.url)
        else:
            counts = response.xpath("//h4[contains(text(),'全部车源')]/text()").re('\d+')[0] \
                if response.xpath("//h4[contains(text(),'全部车源')]/text()").re('\d+') else "0"
            print(counts)
            node_list = response.xpath('//li[@class="con caritem conHeight"]')
            print(len(self.fail_url))
            print(len(node_list))
            for node in node_list:
                urlbase = node.xpath('.//a[@class="aimg"]/@href').get()
                url = response.urljoin(urlbase)
                # 'https://www.xin.com/40d0nl1ky9/che28911337.html?cityid=2401'
                for code, name in city_code_list.items():
                    url = url[:55]+str(code)
                    print(url)
                    self.c.lpush('youxin:start_urls', url)

            # if len(self.fail_url) > 0:
            #     for fail_url in self.fail_url:
            #         yield scrapy.Request(
            #             fail_url,
            #             self.parse,
            #             dont_filter=True,
            #         )
