# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class Che300NewItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    pass


class che300_price(scrapy.Item):
    geartype = scrapy.Field()
    provname = scrapy.Field()
    provid = scrapy.Field()
    makeyear = scrapy.Field()
    price = scrapy.Field()
    cityname = scrapy.Field()
    cityid = scrapy.Field()
    emission = scrapy.Field()
    reyear = scrapy.Field()
    factoryname = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    date = scrapy.Field()
    salesdesc = scrapy.Field()
    salesdescid = scrapy.Field()
    milage = scrapy.Field()
    liter_type = scrapy.Field()
    url = scrapy.Field()
    grabtime = scrapy.Field()
    situation = scrapy.Field()
    price1 = scrapy.Field()
    price2 = scrapy.Field()
    price3 = scrapy.Field()
    price4 = scrapy.Field()
    price5 = scrapy.Field()
    price6 = scrapy.Field()
    price7 = scrapy.Field()
    saleDateRange1 = scrapy.Field()
    saleDateRange2 = scrapy.Field()
    saleDateRange3 = scrapy.Field()
    saleDateRange4 = scrapy.Field()
    saleDateRange5 = scrapy.Field()
    saleDateRange6 = scrapy.Field()
    saleDateRange7 = scrapy.Field()
    saleRate1 = scrapy.Field()
    saleRate2 = scrapy.Field()
    saleRate3 = scrapy.Field()
    saleRate4 = scrapy.Field()
    saleRate5 = scrapy.Field()
    saleRate6 = scrapy.Field()
    saleRate7 = scrapy.Field()
    status = scrapy.Field()
    datasave = scrapy.Field()
    default = scrapy.Field()
    excellent = scrapy.Field()
    good = scrapy.Field()
    normal = scrapy.Field()
    data = scrapy.Field()
    year_2017 = scrapy.Field()
    year_2018 = scrapy.Field()
    year_2019 = scrapy.Field()
    year_2020 = scrapy.Field()
    year_2021 = scrapy.Field()
    dealer_price = scrapy.Field()
    individual_price = scrapy.Field()
    help_sold_price = scrapy.Field()
    dealer_buy_price = scrapy.Field()
    dealer_auction_price = scrapy.Field()
    dealer_low_buy_price = scrapy.Field()
    dealer_low_auction_price = scrapy.Field()
    individual_low_sold_price = scrapy.Field()
    dealer_low_sold_price = scrapy.Field()
    dealer_high_sold_price = scrapy.Field()
    low_help_sold_price = scrapy.Field()
    b2c_price = scrapy.Field()


class Che300PriceDaily(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    grabtime = scrapy.Field()
    url = scrapy.Field()
    price1 = scrapy.Field()
    price2 = scrapy.Field()
    price3 = scrapy.Field()
    price4 = scrapy.Field()
    price5 = scrapy.Field()
    price6 = scrapy.Field()
    price7 = scrapy.Field()
    brand = scrapy.Field()
    series = scrapy.Field()
    salesdescid = scrapy.Field()
    regDate = scrapy.Field()
    cityid = scrapy.Field()
    prov = scrapy.Field()
    mile = scrapy.Field()

    car_md5 = scrapy.Field()
    statusplus = scrapy.Field()
    status = scrapy.Field()


class Che300_Big_Car_evaluate_Item(scrapy.Item):
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    brand_id = scrapy.Field()
    series_id = scrapy.Field()
    model_id = scrapy.Field()
    prov_id = scrapy.Field()
    city_id = scrapy.Field()
    mile = scrapy.Field()
    reg_date = scrapy.Field()
    default_car_condition = scrapy.Field()
    good_dealer_high_buy_price = scrapy.Field()
    good_dealer_low_buy_price = scrapy.Field()
    good_dealer_high_sold_price = scrapy.Field()
    good_dealer_buy_price = scrapy.Field()
    good_dealer_low_sold_price = scrapy.Field()
    good_dealer_sold_price = scrapy.Field()
    excellent_dealer_high_buy_price = scrapy.Field()
    excellent_dealer_low_buy_price = scrapy.Field()
    excellent_dealer_high_sold_price = scrapy.Field()
    excellent_dealer_buy_price = scrapy.Field()
    excellent_dealer_sold_price = scrapy.Field()
    excellent_dealer_low_sold_price = scrapy.Field()
    normal_dealer_high_buy_price = scrapy.Field()
    normal_dealer_low_buy_price = scrapy.Field()
    normal_dealer_high_sold_price = scrapy.Field()
    normal_dealer_buy_price = scrapy.Field()
    normal_dealer_low_sold_price = scrapy.Field()
    normal_dealer_sold_price = scrapy.Field()
    goods_type = scrapy.Field()
