__author__ = 'cagey'

import pymongo
import redis
import time

city_dic = {
    'aba': {'city_ID': 513200,
            'city_Name': '阿坝',
            'city_Pinyin': 'aba',
            'prov_ID': 510000,
            'prov_Name': '四川'},
    'akesu': {'city_ID': 652900,
              'city_Name': '阿克苏',
              'city_Pinyin': 'akesu',
              'prov_ID': 650000,
              'prov_Name': '新疆'},
    'alaer': {'city_ID': 659002,
              'city_Name': '阿拉尔',
              'city_Pinyin': 'alaer',
              'prov_ID': 650000,
              'prov_Name': '新疆'},
    'alashanmeng': {'city_ID': 152900,
                    'city_Name': '阿拉善盟',
                    'city_Pinyin': 'alashanmeng',
                    'prov_ID': 150000,
                    'prov_Name': '内蒙古'},
    'aletai': {'city_ID': 654300,
               'city_Name': '阿勒泰',
               'city_Pinyin': 'aletai',
               'prov_ID': 650000,
               'prov_Name': '新疆'},
    'ali': {'city_ID': 542500,
            'city_Name': '阿里',
            'city_Pinyin': 'ali',
            'prov_ID': 540000,
            'prov_Name': '西藏'},
    'ankang': {'city_ID': 610900,
               'city_Name': '安康',
               'city_Pinyin': 'ankang',
               'prov_ID': 610000,
               'prov_Name': '陕西'},
    'anqing': {'city_ID': 340800,
               'city_Name': '安庆',
               'city_Pinyin': 'anqing',
               'prov_ID': 340000,
               'prov_Name': '安徽'},
    'anshan': {'city_ID': 210300,
               'city_Name': '鞍山',
               'city_Pinyin': 'anshan',
               'prov_ID': 210000,
               'prov_Name': '辽宁'},
    'anshun': {'city_ID': 520400,
               'city_Name': '安顺',
               'city_Pinyin': 'anshun',
               'prov_ID': 520000,
               'prov_Name': '贵州'},
    'anyang': {'city_ID': 410500,
               'city_Name': '安阳',
               'city_Pinyin': 'anyang',
               'prov_ID': 410000,
               'prov_Name': '河南'},
    'aomen': {'city_ID': 820100,
              'city_Name': '澳门',
              'city_Pinyin': 'aomen',
              'prov_ID': 820000,
              'prov_Name': '澳门'},
    'baicheng': {'city_ID': 220800,
                 'city_Name': '白城',
                 'city_Pinyin': 'baicheng',
                 'prov_ID': 220000,
                 'prov_Name': '吉林'},
    'baise': {'city_ID': 451000,
              'city_Name': '百色',
              'city_Pinyin': 'baise',
              'prov_ID': 450000,
              'prov_Name': '广西'},
    'baisha': {'city_ID': 469025,
               'city_Name': '白沙',
               'city_Pinyin': 'baisha',
               'prov_ID': 460000,
               'prov_Name': '海南'},
    'baishan': {'city_ID': 220600,
                'city_Name': '白山',
                'city_Pinyin': 'baishan',
                'prov_ID': 220000,
                'prov_Name': '吉林'},
    'baiyin': {'city_ID': 620400,
               'city_Name': '白银',
               'city_Pinyin': 'baiyin',
               'prov_ID': 620000,
               'prov_Name': '甘肃'},
    'bangbu': {'city_ID': 340300,
               'city_Name': '蚌埠',
               'city_Pinyin': 'bangbu',
               'prov_ID': 340000,
               'prov_Name': '安徽'},
    'baoding': {'city_ID': 130600,
                'city_Name': '保定',
                'city_Pinyin': 'baoding',
                'prov_ID': 130000,
                'prov_Name': '河北'},
    'baoji': {'city_ID': 610300,
              'city_Name': '宝鸡',
              'city_Pinyin': 'baoji',
              'prov_ID': 610000,
              'prov_Name': '陕西'},
    'baoshan': {'city_ID': 530500,
                'city_Name': '保山',
                'city_Pinyin': 'baoshan',
                'prov_ID': 530000,
                'prov_Name': '云南'},
    'baoting': {'city_ID': 469029,
                'city_Name': '保亭',
                'city_Pinyin': 'baoting',
                'prov_ID': 460000,
                'prov_Name': '海南'},
    'baotou': {'city_ID': 150200,
               'city_Name': '包头',
               'city_Pinyin': 'baotou',
               'prov_ID': 150000,
               'prov_Name': '内蒙古'},
    'bayannaoer': {'city_ID': 150800,
                   'city_Name': '巴彦淖尔',
                   'city_Pinyin': 'bayannaoer',
                   'prov_ID': 150000,
                   'prov_Name': '内蒙古'},
    'bayinguoleng': {'city_ID': 652800,
                     'city_Name': '巴音郭楞',
                     'city_Pinyin': 'bayinguoleng',
                     'prov_ID': 650000,
                     'prov_Name': '新疆'},
    'bazhong': {'city_ID': 511900,
                'city_Name': '巴中',
                'city_Pinyin': 'bazhong',
                'prov_ID': 510000,
                'prov_Name': '四川'},
    'beihai': {'city_ID': 450500,
               'city_Name': '北海',
               'city_Pinyin': 'beihai',
               'prov_ID': 450000,
               'prov_Name': '广西'},
    'beijing': {'city_ID': 110100,
                'city_Name': '北京',
                'city_Pinyin': 'beijing',
                'prov_ID': 110000,
                'prov_Name': '北京'},
    'beitunshi': {'city_ID': 659005,
                  'city_Name': '北屯市',
                  'city_Pinyin': 'beitunshi',
                  'prov_ID': 650000,
                  'prov_Name': '新疆'},
    'benxi': {'city_ID': 210500,
              'city_Name': '本溪',
              'city_Pinyin': 'benxi',
              'prov_ID': 210000,
              'prov_Name': '辽宁'},
    'bijie': {'city_ID': 520500,
              'city_Name': '毕节',
              'city_Pinyin': 'bijie',
              'prov_ID': 520000,
              'prov_Name': '贵州'},
    'binzhou': {'city_ID': 371600,
                'city_Name': '滨州',
                'city_Pinyin': 'binzhou',
                'prov_ID': 370000,
                'prov_Name': '山东'},
    'boertala': {'city_ID': 652700,
                 'city_Name': '博尔塔拉',
                 'city_Pinyin': 'boertala',
                 'prov_ID': 650000,
                 'prov_Name': '新疆'},
    'bozhou': {'city_ID': 341600,
               'city_Name': '亳州',
               'city_Pinyin': 'bozhou',
               'prov_ID': 340000,
               'prov_Name': '安徽'},
    'cangzhou': {'city_ID': 130900,
                 'city_Name': '沧州',
                 'city_Pinyin': 'cangzhou',
                 'prov_ID': 130000,
                 'prov_Name': '河北'},
    'changchun': {'city_ID': 220100,
                  'city_Name': '长春',
                  'city_Pinyin': 'changchun',
                  'prov_ID': 220000,
                  'prov_Name': '吉林'},
    'changde': {'city_ID': 430700,
                'city_Name': '常德',
                'city_Pinyin': 'changde',
                'prov_ID': 430000,
                'prov_Name': '湖南'},
    'changdou': {'city_ID': 540300,
                 'city_Name': '昌都',
                 'city_Pinyin': 'changdou',
                 'prov_ID': 540000,
                 'prov_Name': '西藏'},
    'changji': {'city_ID': 652300,
                'city_Name': '昌吉',
                'city_Pinyin': 'changji',
                'prov_ID': 650000,
                'prov_Name': '新疆'},
    'changjiang': {'city_ID': 469026,
                   'city_Name': '昌江',
                   'city_Pinyin': 'changjiang',
                   'prov_ID': 460000,
                   'prov_Name': '海南'},
    'changsha': {'city_ID': 430100,
                 'city_Name': '长沙',
                 'city_Pinyin': 'changsha',
                 'prov_ID': 430000,
                 'prov_Name': '湖南'},
    'changzhi': {'city_ID': 140400,
                 'city_Name': '长治',
                 'city_Pinyin': 'changzhi',
                 'prov_ID': 140000,
                 'prov_Name': '山西'},
    'changzhou': {'city_ID': 320400,
                  'city_Name': '常州',
                  'city_Pinyin': 'changzhou',
                  'prov_ID': 320000,
                  'prov_Name': '江苏'},
    'chaoyang': {'city_ID': 211300,
                 'city_Name': '朝阳',
                 'city_Pinyin': 'chaoyang',
                 'prov_ID': 210000,
                 'prov_Name': '辽宁'},
    'chaozhou': {'city_ID': 445100,
                 'city_Name': '潮州',
                 'city_Pinyin': 'chaozhou',
                 'prov_ID': 440000,
                 'prov_Name': '广东'},
    'chengde': {'city_ID': 130800,
                'city_Name': '承德',
                'city_Pinyin': 'chengde',
                'prov_ID': 130000,
                'prov_Name': '河北'},
    'chengdu': {'city_ID': 510100,
                'city_Name': '成都',
                'city_Pinyin': 'chengdu',
                'prov_ID': 510000,
                'prov_Name': '四川'},
    'chengmai': {'city_ID': 469023,
                 'city_Name': '澄迈',
                 'city_Pinyin': 'chengmai',
                 'prov_ID': 460000,
                 'prov_Name': '海南'},
    'chenzhou': {'city_ID': 431000,
                 'city_Name': '郴州',
                 'city_Pinyin': 'chenzhou',
                 'prov_ID': 430000,
                 'prov_Name': '湖南'},
    'chifeng': {'city_ID': 150400,
                'city_Name': '赤峰',
                'city_Pinyin': 'chifeng',
                'prov_ID': 150000,
                'prov_Name': '内蒙古'},
    'chizhou': {'city_ID': 341700,
                'city_Name': '池州',
                'city_Pinyin': 'chizhou',
                'prov_ID': 340000,
                'prov_Name': '安徽'},
    'chongqing': {'city_ID': 500100,
                  'city_Name': '重庆',
                  'city_Pinyin': 'chongqing',
                  'prov_ID': 500000,
                  'prov_Name': '重庆'},
    'chongzuo': {'city_ID': 451400,
                 'city_Name': '崇左',
                 'city_Pinyin': 'chongzuo',
                 'prov_ID': 450000,
                 'prov_Name': '广西'},
    'chuxiong': {'city_ID': 532300,
                 'city_Name': '楚雄',
                 'city_Pinyin': 'chuxiong',
                 'prov_ID': 530000,
                 'prov_Name': '云南'},
    'chuzhou': {'city_ID': 341100,
                'city_Name': '滁州',
                'city_Pinyin': 'chuzhou',
                'prov_ID': 340000,
                'prov_Name': '安徽'},
    'dali': {'city_ID': 532900,
             'city_Name': '大理',
             'city_Pinyin': 'dali',
             'prov_ID': 530000,
             'prov_Name': '云南'},
    'dalian': {'city_ID': 210200,
               'city_Name': '大连',
               'city_Pinyin': 'dalian',
               'prov_ID': 210000,
               'prov_Name': '辽宁'},
    'dandong': {'city_ID': 210600,
                'city_Name': '丹东',
                'city_Pinyin': 'dandong',
                'prov_ID': 210000,
                'prov_Name': '辽宁'},
    'danzhou': {'city_ID': 460400,
                'city_Name': '儋州',
                'city_Pinyin': 'danzhou',
                'prov_ID': 460000,
                'prov_Name': '海南'},
    'daqing': {'city_ID': 230600,
               'city_Name': '大庆',
               'city_Pinyin': 'daqing',
               'prov_ID': 230000,
               'prov_Name': '黑龙江'},
    'datong': {'city_ID': 140200,
               'city_Name': '大同',
               'city_Pinyin': 'datong',
               'prov_ID': 140000,
               'prov_Name': '山西'},
    'daxinganling': {'city_ID': 232700,
                     'city_Name': '大兴安岭',
                     'city_Pinyin': 'daxinganling',
                     'prov_ID': 230000,
                     'prov_Name': '黑龙江'},
    'dazhou': {'city_ID': 511700,
               'city_Name': '达州',
               'city_Pinyin': 'dazhou',
               'prov_ID': 510000,
               'prov_Name': '四川'},
    'dehong': {'city_ID': 533100,
               'city_Name': '德宏',
               'city_Pinyin': 'dehong',
               'prov_ID': 530000,
               'prov_Name': '云南'},
    'deyang': {'city_ID': 510600,
               'city_Name': '德阳',
               'city_Pinyin': 'deyang',
               'prov_ID': 510000,
               'prov_Name': '四川'},
    'dezhou': {'city_ID': 371400,
               'city_Name': '德州',
               'city_Pinyin': 'dezhou',
               'prov_ID': 370000,
               'prov_Name': '山东'},
    'dingan': {'city_ID': 469021,
               'city_Name': '定安',
               'city_Pinyin': 'dingan',
               'prov_ID': 460000,
               'prov_Name': '海南'},
    'dingxi': {'city_ID': 621100,
               'city_Name': '定西',
               'city_Pinyin': 'dingxi',
               'prov_ID': 620000,
               'prov_Name': '甘肃'},
    'diqing': {'city_ID': 533400,
               'city_Name': '迪庆',
               'city_Pinyin': 'diqing',
               'prov_ID': 530000,
               'prov_Name': '云南'},
    'dongfang': {'city_ID': 469007,
                 'city_Name': '东方',
                 'city_Pinyin': 'dongfang',
                 'prov_ID': 460000,
                 'prov_Name': '海南'},
    'dongguan': {'city_ID': 441900,
                 'city_Name': '东莞',
                 'city_Pinyin': 'dongguan',
                 'prov_ID': 440000,
                 'prov_Name': '广东'},
    'dongying': {'city_ID': 370500,
                 'city_Name': '东营',
                 'city_Pinyin': 'dongying',
                 'prov_ID': 370000,
                 'prov_Name': '山东'},
    'duyunshi': {'city_ID': 522700,
                 'city_Name': '都匀市',
                 'city_Pinyin': 'duyunshi',
                 'prov_ID': 520000,
                 'prov_Name': '贵州'},
    'eerduosi': {'city_ID': 150600,
                 'city_Name': '鄂尔多斯',
                 'city_Pinyin': 'eerduosi',
                 'prov_ID': 150000,
                 'prov_Name': '内蒙古'},
    'enshi': {'city_ID': 422800,
              'city_Name': '恩施',
              'city_Pinyin': 'enshi',
              'prov_ID': 420000,
              'prov_Name': '湖北'},
    'ezhou': {'city_ID': 420700,
              'city_Name': '鄂州',
              'city_Pinyin': 'ezhou',
              'prov_ID': 420000,
              'prov_Name': '湖北'},
    'fangchenggang': {'city_ID': 450600,
                      'city_Name': '防城港',
                      'city_Pinyin': 'fangchenggang',
                      'prov_ID': 450000,
                      'prov_Name': '广西'},
    'foshan': {'city_ID': 440600,
               'city_Name': '佛山',
               'city_Pinyin': 'foshan',
               'prov_ID': 440000,
               'prov_Name': '广东'},
    'fu_yang': {'city_ID': 341200,
                'city_Name': '阜阳',
                'city_Pinyin': 'fu_yang',
                'prov_ID': 340000,
                'prov_Name': '安徽'},
    'fu_zhou': {'city_ID': 361000,
                'city_Name': '抚州',
                'city_Pinyin': 'fu_zhou',
                'prov_ID': 360000,
                'prov_Name': '江西'},
    'fushun': {'city_ID': 210400,
               'city_Name': '抚顺',
               'city_Pinyin': 'fushun',
               'prov_ID': 210000,
               'prov_Name': '辽宁'},
    'fuxin': {'city_ID': 210900,
              'city_Name': '阜新',
              'city_Pinyin': 'fuxin',
              'prov_ID': 210000,
              'prov_Name': '辽宁'},
    'fuzhou': {'city_ID': 350100,
               'city_Name': '福州',
               'city_Pinyin': 'fuzhou',
               'prov_ID': 350000,
               'prov_Name': '福建'},
    'gannan': {'city_ID': 623000,
               'city_Name': '甘南',
               'city_Pinyin': 'gannan',
               'prov_ID': 620000,
               'prov_Name': '甘肃'},
    'ganzhou': {'city_ID': 360700,
                'city_Name': '赣州',
                'city_Pinyin': 'ganzhou',
                'prov_ID': 360000,
                'prov_Name': '江西'},
    'ganzi': {'city_ID': 513300,
              'city_Name': '甘孜',
              'city_Pinyin': 'ganzi',
              'prov_ID': 510000,
              'prov_Name': '四川'},
    'guangan': {'city_ID': 511600,
                'city_Name': '广安',
                'city_Pinyin': 'guangan',
                'prov_ID': 510000,
                'prov_Name': '四川'},
    'guangyuan': {'city_ID': 510800,
                  'city_Name': '广元',
                  'city_Pinyin': 'guangyuan',
                  'prov_ID': 510000,
                  'prov_Name': '四川'},
    'guangzhou': {'city_ID': 440100,
                  'city_Name': '广州',
                  'city_Pinyin': 'guangzhou',
                  'prov_ID': 440000,
                  'prov_Name': '广东'},
    'guigang': {'city_ID': 450800,
                'city_Name': '贵港',
                'city_Pinyin': 'guigang',
                'prov_ID': 450000,
                'prov_Name': '广西'},
    'guilin': {'city_ID': 450300,
               'city_Name': '桂林',
               'city_Pinyin': 'guilin',
               'prov_ID': 450000,
               'prov_Name': '广西'},
    'guiyang': {'city_ID': 520100,
                'city_Name': '贵阳',
                'city_Pinyin': 'guiyang',
                'prov_ID': 520000,
                'prov_Name': '贵州'},
    'guoluo': {'city_ID': 632600,
               'city_Name': '果洛',
               'city_Pinyin': 'guoluo',
               'prov_ID': 630000,
               'prov_Name': '青海'},
    'guyuan': {'city_ID': 640400,
               'city_Name': '固原',
               'city_Pinyin': 'guyuan',
               'prov_ID': 640000,
               'prov_Name': '宁夏'},
    'haerbin': {'city_ID': 230100,
                'city_Name': '哈尔滨',
                'city_Pinyin': 'haerbin',
                'prov_ID': 230000,
                'prov_Name': '黑龙江'},
    'hai_nan': {'city_ID': 632500,
                'city_Name': '海南',
                'city_Pinyin': 'hai_nan',
                'prov_ID': 630000,
                'prov_Name': '青海'},
    'haibei': {'city_ID': 632200,
               'city_Name': '海北',
               'city_Pinyin': 'haibei',
               'prov_ID': 630000,
               'prov_Name': '青海'},
    'haidong': {'city_ID': 630200,
                'city_Name': '海东',
                'city_Pinyin': 'haidong',
                'prov_ID': 630000,
                'prov_Name': '青海'},
    'haikou': {'city_ID': 460100,
               'city_Name': '海口',
               'city_Pinyin': 'haikou',
               'prov_ID': 460000,
               'prov_Name': '海南'},
    'haixi': {'city_ID': 632800,
              'city_Name': '海西',
              'city_Pinyin': 'haixi',
              'prov_ID': 630000,
              'prov_Name': '青海'},
    'hami': {'city_ID': 650500,
             'city_Name': '哈密',
             'city_Pinyin': 'hami',
             'prov_ID': 650000,
             'prov_Name': '新疆'},
    'handan': {'city_ID': 130400,
               'city_Name': '邯郸',
               'city_Pinyin': 'handan',
               'prov_ID': 130000,
               'prov_Name': '河北'},
    'hangzhou': {'city_ID': 330100,
                 'city_Name': '杭州',
                 'city_Pinyin': 'hangzhou',
                 'prov_ID': 330000,
                 'prov_Name': '浙江'},
    'hanzhong': {'city_ID': 610700,
                 'city_Name': '汉中',
                 'city_Pinyin': 'hanzhong',
                 'prov_ID': 610000,
                 'prov_Name': '陕西'},
    'hebi': {'city_ID': 410600,
             'city_Name': '鹤壁',
             'city_Pinyin': 'hebi',
             'prov_ID': 410000,
             'prov_Name': '河南'},
    'hechi': {'city_ID': 451200,
              'city_Name': '河池',
              'city_Pinyin': 'hechi',
              'prov_ID': 450000,
              'prov_Name': '广西'},
    'hefei': {'city_ID': 340100,
              'city_Name': '合肥',
              'city_Pinyin': 'hefei',
              'prov_ID': 340000,
              'prov_Name': '安徽'},
    'hegang': {'city_ID': 230400,
               'city_Name': '鹤岗',
               'city_Pinyin': 'hegang',
               'prov_ID': 230000,
               'prov_Name': '黑龙江'},
    'heihe': {'city_ID': 231100,
              'city_Name': '黑河',
              'city_Pinyin': 'heihe',
              'prov_ID': 230000,
              'prov_Name': '黑龙江'},
    'hengshui': {'city_ID': 131100,
                 'city_Name': '衡水',
                 'city_Pinyin': 'hengshui',
                 'prov_ID': 130000,
                 'prov_Name': '河北'},
    'hengyang': {'city_ID': 430400,
                 'city_Name': '衡阳',
                 'city_Pinyin': 'hengyang',
                 'prov_ID': 430000,
                 'prov_Name': '湖南'},
    'hetian': {'city_ID': 653200,
               'city_Name': '和田',
               'city_Pinyin': 'hetian',
               'prov_ID': 650000,
               'prov_Name': '新疆'},
    'heyuan': {'city_ID': 441600,
               'city_Name': '河源',
               'city_Pinyin': 'heyuan',
               'prov_ID': 440000,
               'prov_Name': '广东'},
    'heze': {'city_ID': 371700,
             'city_Name': '菏泽',
             'city_Pinyin': 'heze',
             'prov_ID': 370000,
             'prov_Name': '山东'},
    'hezhou': {'city_ID': 451100,
               'city_Name': '贺州',
               'city_Pinyin': 'hezhou',
               'prov_ID': 450000,
               'prov_Name': '广西'},
    'honghe': {'city_ID': 532500,
               'city_Name': '红河',
               'city_Pinyin': 'honghe',
               'prov_ID': 530000,
               'prov_Name': '云南'},
    'huaian': {'city_ID': 320800,
               'city_Name': '淮安',
               'city_Pinyin': 'huaian',
               'prov_ID': 320000,
               'prov_Name': '江苏'},
    'huaibei': {'city_ID': 340600,
                'city_Name': '淮北',
                'city_Pinyin': 'huaibei',
                'prov_ID': 340000,
                'prov_Name': '安徽'},
    'huaihua': {'city_ID': 431200,
                'city_Name': '怀化',
                'city_Pinyin': 'huaihua',
                'prov_ID': 430000,
                'prov_Name': '湖南'},
    'huainan': {'city_ID': 340400,
                'city_Name': '淮南',
                'city_Pinyin': 'huainan',
                'prov_ID': 340000,
                'prov_Name': '安徽'},
    'huanggang': {'city_ID': 421100,
                  'city_Name': '黄冈',
                  'city_Pinyin': 'huanggang',
                  'prov_ID': 420000,
                  'prov_Name': '湖北'},
    'huangnan': {'city_ID': 632300,
                 'city_Name': '黄南',
                 'city_Pinyin': 'huangnan',
                 'prov_ID': 630000,
                 'prov_Name': '青海'},
    'huangshan': {'city_ID': 341000,
                  'city_Name': '黄山',
                  'city_Pinyin': 'huangshan',
                  'prov_ID': 340000,
                  'prov_Name': '安徽'},
    'huangshi': {'city_ID': 420200,
                 'city_Name': '黄石',
                 'city_Pinyin': 'huangshi',
                 'prov_ID': 420000,
                 'prov_Name': '湖北'},
    'huhehaote': {'city_ID': 150100,
                  'city_Name': '呼和浩特',
                  'city_Pinyin': 'huhehaote',
                  'prov_ID': 150000,
                  'prov_Name': '内蒙古'},
    'huizhou': {'city_ID': 441300,
                'city_Name': '惠州',
                'city_Pinyin': 'huizhou',
                'prov_ID': 440000,
                'prov_Name': '广东'},
    'huludao': {'city_ID': 211400,
                'city_Name': '葫芦岛',
                'city_Pinyin': 'huludao',
                'prov_ID': 210000,
                'prov_Name': '辽宁'},
    'hulunbeier': {'city_ID': 150700,
                   'city_Name': '呼伦贝尔',
                   'city_Pinyin': 'hulunbeier',
                   'prov_ID': 150000,
                   'prov_Name': '内蒙古'},
    'huzhou': {'city_ID': 330500,
               'city_Name': '湖州',
               'city_Pinyin': 'huzhou',
               'prov_ID': 330000,
               'prov_Name': '浙江'},
    'jiamusi': {'city_ID': 230800,
                'city_Name': '佳木斯',
                'city_Pinyin': 'jiamusi',
                'prov_ID': 230000,
                'prov_Name': '黑龙江'},
    'jian': {'city_ID': 360800,
             'city_Name': '吉安',
             'city_Pinyin': 'jian',
             'prov_ID': 360000,
             'prov_Name': '江西'},
    'jiangmen': {'city_ID': 440700,
                 'city_Name': '江门',
                 'city_Pinyin': 'jiangmen',
                 'prov_ID': 440000,
                 'prov_Name': '广东'},
    'jiaozuo': {'city_ID': 410800,
                'city_Name': '焦作',
                'city_Pinyin': 'jiaozuo',
                'prov_ID': 410000,
                'prov_Name': '河南'},
    'jiaxing': {'city_ID': 330400,
                'city_Name': '嘉兴',
                'city_Pinyin': 'jiaxing',
                'prov_ID': 330000,
                'prov_Name': '浙江'},
    'jiayuguan': {'city_ID': 620200,
                  'city_Name': '嘉峪关',
                  'city_Pinyin': 'jiayuguan',
                  'prov_ID': 620000,
                  'prov_Name': '甘肃'},
    'jieyang': {'city_ID': 445200,
                'city_Name': '揭阳',
                'city_Pinyin': 'jieyang',
                'prov_ID': 440000,
                'prov_Name': '广东'},
    'jilinshi': {'city_ID': 220200,
                 'city_Name': '吉林',
                 'city_Pinyin': 'jilinshi',
                 'prov_ID': 220000,
                 'prov_Name': '吉林'},
    'jinan': {'city_ID': 370100,
              'city_Name': '济南',
              'city_Pinyin': 'jinan',
              'prov_ID': 370000,
              'prov_Name': '山东'},
    'jinchang': {'city_ID': 620300,
                 'city_Name': '金昌',
                 'city_Pinyin': 'jinchang',
                 'prov_ID': 620000,
                 'prov_Name': '甘肃'},
    'jincheng': {'city_ID': 140500,
                 'city_Name': '晋城',
                 'city_Pinyin': 'jincheng',
                 'prov_ID': 140000,
                 'prov_Name': '山西'},
    'jingdezhen': {'city_ID': 360200,
                   'city_Name': '景德镇',
                   'city_Pinyin': 'jingdezhen',
                   'prov_ID': 360000,
                   'prov_Name': '江西'},
    'jingmen': {'city_ID': 420800,
                'city_Name': '荆门',
                'city_Pinyin': 'jingmen',
                'prov_ID': 420000,
                'prov_Name': '湖北'},
    'jingzhou': {'city_ID': 421000,
                 'city_Name': '荆州',
                 'city_Pinyin': 'jingzhou',
                 'prov_ID': 420000,
                 'prov_Name': '湖北'},
    'jinhua': {'city_ID': 330700,
               'city_Name': '金华',
               'city_Pinyin': 'jinhua',
               'prov_ID': 330000,
               'prov_Name': '浙江'},
    'jining': {'city_ID': 370800,
               'city_Name': '济宁',
               'city_Pinyin': 'jining',
               'prov_ID': 370000,
               'prov_Name': '山东'},
    'jinzhong': {'city_ID': 140700,
                 'city_Name': '晋中',
                 'city_Pinyin': 'jinzhong',
                 'prov_ID': 140000,
                 'prov_Name': '山西'},
    'jinzhou': {'city_ID': 210700,
                'city_Name': '锦州',
                'city_Pinyin': 'jinzhou',
                'prov_ID': 210000,
                'prov_Name': '辽宁'},
    'jiujiang': {'city_ID': 360400,
                 'city_Name': '九江',
                 'city_Pinyin': 'jiujiang',
                 'prov_ID': 360000,
                 'prov_Name': '江西'},
    'jiuquan': {'city_ID': 620900,
                'city_Name': '酒泉',
                'city_Pinyin': 'jiuquan',
                'prov_ID': 620000,
                'prov_Name': '甘肃'},
    'jixi': {'city_ID': 230300,
             'city_Name': '鸡西',
             'city_Pinyin': 'jixi',
             'prov_ID': 230000,
             'prov_Name': '黑龙江'},
    'jiyuan': {'city_ID': 419001,
               'city_Name': '济源',
               'city_Pinyin': 'jiyuan',
               'prov_ID': 410000,
               'prov_Name': '河南'},
    'kaifeng': {'city_ID': 410200,
                'city_Name': '开封',
                'city_Pinyin': 'kaifeng',
                'prov_ID': 410000,
                'prov_Name': '河南'},
    'kaili': {'city_ID': 522600,
              'city_Name': '凯里',
              'city_Pinyin': 'kaili',
              'prov_ID': 520000,
              'prov_Name': '贵州'},
    'kashen': {'city_ID': 653100,
               'city_Name': '喀什',
               'city_Pinyin': 'kashen',
               'prov_ID': 650000,
               'prov_Name': '新疆'},
    'kekedalashi': {'city_ID': 659008,
                    'city_Name': '可克达拉市',
                    'city_Pinyin': 'kekedalashi',
                    'prov_ID': 650000,
                    'prov_Name': '新疆'},
    'kelamayi': {'city_ID': 650200,
                 'city_Name': '克拉玛依',
                 'city_Pinyin': 'kelamayi',
                 'prov_ID': 650000,
                 'prov_Name': '新疆'},
    'kezilesu': {'city_ID': 653000,
                 'city_Name': '克孜勒苏',
                 'city_Pinyin': 'kezilesu',
                 'prov_ID': 650000,
                 'prov_Name': '新疆'},
    'kunming': {'city_ID': 530100,
                'city_Name': '昆明',
                'city_Pinyin': 'kunming',
                'prov_ID': 530000,
                'prov_Name': '云南'},
    'kunyu': {'city_ID': 659009,
              'city_Name': '昆玉',
              'city_Pinyin': 'kunyu',
              'prov_ID': 650000,
              'prov_Name': '新疆'},
    'laibin': {'city_ID': 451300,
               'city_Name': '来宾',
               'city_Pinyin': 'laibin',
               'prov_ID': 450000,
               'prov_Name': '广西'},
    'laiwu': {'city_ID': 371200,
              'city_Name': '莱芜',
              'city_Pinyin': 'laiwu',
              'prov_ID': 370000,
              'prov_Name': '山东'},
    'langfang': {'city_ID': 131000,
                 'city_Name': '廊坊',
                 'city_Pinyin': 'langfang',
                 'prov_ID': 130000,
                 'prov_Name': '河北'},
    'lanzhou': {'city_ID': 620100,
                'city_Name': '兰州',
                'city_Pinyin': 'lanzhou',
                'prov_ID': 620000,
                'prov_Name': '甘肃'},
    'lasa': {'city_ID': 540100,
             'city_Name': '拉萨',
             'city_Pinyin': 'lasa',
             'prov_ID': 540000,
             'prov_Name': '西藏'},
    'ledong': {'city_ID': 469027,
               'city_Name': '乐东',
               'city_Pinyin': 'ledong',
               'prov_ID': 460000,
               'prov_Name': '海南'},
    'leshan': {'city_ID': 511100,
               'city_Name': '乐山',
               'city_Pinyin': 'leshan',
               'prov_ID': 510000,
               'prov_Name': '四川'},
    'liangshan': {'city_ID': 513400,
                  'city_Name': '凉山',
                  'city_Pinyin': 'liangshan',
                  'prov_ID': 510000,
                  'prov_Name': '四川'},
    'lianyungang': {'city_ID': 320700,
                    'city_Name': '连云港',
                    'city_Pinyin': 'lianyungang',
                    'prov_ID': 320000,
                    'prov_Name': '江苏'},
    'liaocheng': {'city_ID': 371500,
                  'city_Name': '聊城',
                  'city_Pinyin': 'liaocheng',
                  'prov_ID': 370000,
                  'prov_Name': '山东'},
    'liaoyang': {'city_ID': 211000,
                 'city_Name': '辽阳',
                 'city_Pinyin': 'liaoyang',
                 'prov_ID': 210000,
                 'prov_Name': '辽宁'},
    'liaoyuan': {'city_ID': 220400,
                 'city_Name': '辽源',
                 'city_Pinyin': 'liaoyuan',
                 'prov_ID': 220000,
                 'prov_Name': '吉林'},
    'lijiang': {'city_ID': 530700,
                'city_Name': '丽江',
                'city_Pinyin': 'lijiang',
                'prov_ID': 530000,
                'prov_Name': '云南'},
    'lincang': {'city_ID': 530900,
                'city_Name': '临沧',
                'city_Pinyin': 'lincang',
                'prov_ID': 530000,
                'prov_Name': '云南'},
    'linfen': {'city_ID': 141000,
               'city_Name': '临汾',
               'city_Pinyin': 'linfen',
               'prov_ID': 140000,
               'prov_Name': '山西'},
    'lingao': {'city_ID': 469024,
               'city_Name': '临高',
               'city_Pinyin': 'lingao',
               'prov_ID': 460000,
               'prov_Name': '海南'},
    'lingshui': {'city_ID': 469028,
                 'city_Name': '陵水',
                 'city_Pinyin': 'lingshui',
                 'prov_ID': 460000,
                 'prov_Name': '海南'},
    'linxia': {'city_ID': 622900,
               'city_Name': '临夏',
               'city_Pinyin': 'linxia',
               'prov_ID': 620000,
               'prov_Name': '甘肃'},
    'linyi': {'city_ID': 371300,
              'city_Name': '临沂',
              'city_Pinyin': 'linyi',
              'prov_ID': 370000,
              'prov_Name': '山东'},
    'linzhi': {'city_ID': 540400,
               'city_Name': '林芝',
               'city_Pinyin': 'linzhi',
               'prov_ID': 540000,
               'prov_Name': '西藏'},
    'lishui': {'city_ID': 331100,
               'city_Name': '丽水',
               'city_Pinyin': 'lishui',
               'prov_ID': 330000,
               'prov_Name': '浙江'},
    'liuan': {'city_ID': 341500,
              'city_Name': '六安',
              'city_Pinyin': 'liuan',
              'prov_ID': 340000,
              'prov_Name': '安徽'},
    'liupanshui': {'city_ID': 520200,
                   'city_Name': '六盘水',
                   'city_Pinyin': 'liupanshui',
                   'prov_ID': 520000,
                   'prov_Name': '贵州'},
    'liuzhou': {'city_ID': 450200,
                'city_Name': '柳州',
                'city_Pinyin': 'liuzhou',
                'prov_ID': 450000,
                'prov_Name': '广西'},
    'longnan': {'city_ID': 621200,
                'city_Name': '陇南',
                'city_Pinyin': 'longnan',
                'prov_ID': 620000,
                'prov_Name': '甘肃'},
    'longyan': {'city_ID': 350800,
                'city_Name': '龙岩',
                'city_Pinyin': 'longyan',
                'prov_ID': 350000,
                'prov_Name': '福建'},
    'loudi': {'city_ID': 431300,
              'city_Name': '娄底',
              'city_Pinyin': 'loudi',
              'prov_ID': 430000,
              'prov_Name': '湖南'},
    'luohe': {'city_ID': 411100,
              'city_Name': '漯河',
              'city_Pinyin': 'luohe',
              'prov_ID': 410000,
              'prov_Name': '河南'},
    'luoyang': {'city_ID': 410300,
                'city_Name': '洛阳',
                'city_Pinyin': 'luoyang',
                'prov_ID': 410000,
                'prov_Name': '河南'},
    'luzhou': {'city_ID': 510500,
               'city_Name': '泸州',
               'city_Pinyin': 'luzhou',
               'prov_ID': 510000,
               'prov_Name': '四川'},
    'lvliang': {'city_ID': 141100,
                'city_Name': '吕梁',
                'city_Pinyin': 'lvliang',
                'prov_ID': 140000,
                'prov_Name': '山西'},
    'maanshan': {'city_ID': 340500,
                 'city_Name': '马鞍山',
                 'city_Pinyin': 'maanshan',
                 'prov_ID': 340000,
                 'prov_Name': '安徽'},
    'maoming': {'city_ID': 440900,
                'city_Name': '茂名',
                'city_Pinyin': 'maoming',
                'prov_ID': 440000,
                'prov_Name': '广东'},
    'meishan': {'city_ID': 511400,
                'city_Name': '眉山',
                'city_Pinyin': 'meishan',
                'prov_ID': 510000,
                'prov_Name': '四川'},
    'meizhou': {'city_ID': 441400,
                'city_Name': '梅州',
                'city_Pinyin': 'meizhou',
                'prov_ID': 440000,
                'prov_Name': '广东'},
    'mianyang': {'city_ID': 510700,
                 'city_Name': '绵阳',
                 'city_Pinyin': 'mianyang',
                 'prov_ID': 510000,
                 'prov_Name': '四川'},
    'mudanjiang': {'city_ID': 231000,
                   'city_Name': '牡丹江',
                   'city_Pinyin': 'mudanjiang',
                   'prov_ID': 230000,
                   'prov_Name': '黑龙江'},
    'nanchang': {'city_ID': 360100,
                 'city_Name': '南昌',
                 'city_Pinyin': 'nanchang',
                 'prov_ID': 360000,
                 'prov_Name': '江西'},
    'nanchong': {'city_ID': 511300,
                 'city_Name': '南充',
                 'city_Pinyin': 'nanchong',
                 'prov_ID': 510000,
                 'prov_Name': '四川'},
    'nanjing': {'city_ID': 320100,
                'city_Name': '南京',
                'city_Pinyin': 'nanjing',
                'prov_ID': 320000,
                'prov_Name': '江苏'},
    'nanning': {'city_ID': 450100,
                'city_Name': '南宁',
                'city_Pinyin': 'nanning',
                'prov_ID': 450000,
                'prov_Name': '广西'},
    'nanping': {'city_ID': 350700,
                'city_Name': '南平',
                'city_Pinyin': 'nanping',
                'prov_ID': 350000,
                'prov_Name': '福建'},
    'nantong': {'city_ID': 320600,
                'city_Name': '南通',
                'city_Pinyin': 'nantong',
                'prov_ID': 320000,
                'prov_Name': '江苏'},
    'nanyang': {'city_ID': 411300,
                'city_Name': '南阳',
                'city_Pinyin': 'nanyang',
                'prov_ID': 410000,
                'prov_Name': '河南'},
    'naqu': {'city_ID': 542400,
             'city_Name': '那曲',
             'city_Pinyin': 'naqu',
             'prov_ID': 540000,
             'prov_Name': '西藏'},
    'neijiang': {'city_ID': 511000,
                 'city_Name': '内江',
                 'city_Pinyin': 'neijiang',
                 'prov_ID': 510000,
                 'prov_Name': '四川'},
    'ningbo': {'city_ID': 330200,
               'city_Name': '宁波',
               'city_Pinyin': 'ningbo',
               'prov_ID': 330000,
               'prov_Name': '浙江'},
    'ningde': {'city_ID': 350900,
               'city_Name': '宁德',
               'city_Pinyin': 'ningde',
               'prov_ID': 350000,
               'prov_Name': '福建'},
    'nujiang': {'city_ID': 533300,
                'city_Name': '怒江',
                'city_Pinyin': 'nujiang',
                'prov_ID': 530000,
                'prov_Name': '云南'},
    'panjin': {'city_ID': 211100,
               'city_Name': '盘锦',
               'city_Pinyin': 'panjin',
               'prov_ID': 210000,
               'prov_Name': '辽宁'},
    'panzhihua': {'city_ID': 510400,
                  'city_Name': '攀枝花',
                  'city_Pinyin': 'panzhihua',
                  'prov_ID': 510000,
                  'prov_Name': '四川'},
    'ping_xiang': {'city_ID': 360300,
                   'city_Name': '萍乡',
                   'city_Pinyin': 'ping_xiang',
                   'prov_ID': 360000,
                   'prov_Name': '江西'},
    'pingdingshan': {'city_ID': 410400,
                     'city_Name': '平顶山',
                     'city_Pinyin': 'pingdingshan',
                     'prov_ID': 410000,
                     'prov_Name': '河南'},
    'pingliang': {'city_ID': 620800,
                  'city_Name': '平凉',
                  'city_Pinyin': 'pingliang',
                  'prov_ID': 620000,
                  'prov_Name': '甘肃'},
    'puer': {'city_ID': 530800,
             'city_Name': '普洱',
             'city_Pinyin': 'puer',
             'prov_ID': 530000,
             'prov_Name': '云南'},
    'putian': {'city_ID': 350300,
               'city_Name': '莆田',
               'city_Pinyin': 'putian',
               'prov_ID': 350000,
               'prov_Name': '福建'},
    'puyang': {'city_ID': 410900,
               'city_Name': '濮阳',
               'city_Pinyin': 'puyang',
               'prov_ID': 410000,
               'prov_Name': '河南'},
    'qianjiang': {'city_ID': 429005,
                  'city_Name': '潜江',
                  'city_Pinyin': 'qianjiang',
                  'prov_ID': 420000,
                  'prov_Name': '湖北'},
    'qingdao': {'city_ID': 370200,
                'city_Name': '青岛',
                'city_Pinyin': 'qingdao',
                'prov_ID': 370000,
                'prov_Name': '山东'},
    'qingyang': {'city_ID': 621000,
                 'city_Name': '庆阳',
                 'city_Pinyin': 'qingyang',
                 'prov_ID': 620000,
                 'prov_Name': '甘肃'},
    'qingyuan': {'city_ID': 441800,
                 'city_Name': '清远',
                 'city_Pinyin': 'qingyuan',
                 'prov_ID': 440000,
                 'prov_Name': '广东'},
    'qinhuangdao': {'city_ID': 130300,
                    'city_Name': '秦皇岛',
                    'city_Pinyin': 'qinhuangdao',
                    'prov_ID': 130000,
                    'prov_Name': '河北'},
    'qinzhou': {'city_ID': 450700,
                'city_Name': '钦州',
                'city_Pinyin': 'qinzhou',
                'prov_ID': 450000,
                'prov_Name': '广西'},
    'qionghai': {'city_ID': 469002,
                 'city_Name': '琼海',
                 'city_Pinyin': 'qionghai',
                 'prov_ID': 460000,
                 'prov_Name': '海南'},
    'qiongzhong': {'city_ID': 469030,
                   'city_Name': '琼中',
                   'city_Pinyin': 'qiongzhong',
                   'prov_ID': 460000,
                   'prov_Name': '海南'},
    'qiqihaer': {'city_ID': 230200,
                 'city_Name': '齐齐哈尔',
                 'city_Pinyin': 'qiqihaer',
                 'prov_ID': 230000,
                 'prov_Name': '黑龙江'},
    'qitaihe': {'city_ID': 230900,
                'city_Name': '七台河',
                'city_Pinyin': 'qitaihe',
                'prov_ID': 230000,
                'prov_Name': '黑龙江'},
    'quanzhou': {'city_ID': 350500,
                 'city_Name': '泉州',
                 'city_Pinyin': 'quanzhou',
                 'prov_ID': 350000,
                 'prov_Name': '福建'},
    'qujing': {'city_ID': 530300,
               'city_Name': '曲靖',
               'city_Pinyin': 'qujing',
               'prov_ID': 530000,
               'prov_Name': '云南'},
    'quzhou': {'city_ID': 330800,
               'city_Name': '衢州',
               'city_Pinyin': 'quzhou',
               'prov_ID': 330000,
               'prov_Name': '浙江'},
    'rikaze': {'city_ID': 540200,
               'city_Name': '日喀则',
               'city_Pinyin': 'rikaze',
               'prov_ID': 540000,
               'prov_Name': '西藏'},
    'rizhao': {'city_ID': 371100,
               'city_Name': '日照',
               'city_Pinyin': 'rizhao',
               'prov_ID': 370000,
               'prov_Name': '山东'},
    'sanmenxia': {'city_ID': 411200,
                  'city_Name': '三门峡',
                  'city_Pinyin': 'sanmenxia',
                  'prov_ID': 410000,
                  'prov_Name': '河南'},
    'sanming': {'city_ID': 350400,
                'city_Name': '三明',
                'city_Pinyin': 'sanming',
                'prov_ID': 350000,
                'prov_Name': '福建'},
    'sanshashi': {'city_ID': 460300,
                  'city_Name': '三沙市',
                  'city_Pinyin': 'sanshashi',
                  'prov_ID': 460000,
                  'prov_Name': '海南'},
    'sanya': {'city_ID': 460200,
              'city_Name': '三亚',
              'city_Pinyin': 'sanya',
              'prov_ID': 460000,
              'prov_Name': '海南'},
    'shanghai': {'city_ID': 310100,
                 'city_Name': '上海',
                 'city_Pinyin': 'shanghai',
                 'prov_ID': 310000,
                 'prov_Name': '上海'},
    'shangluo': {'city_ID': 611000,
                 'city_Name': '商洛',
                 'city_Pinyin': 'shangluo',
                 'prov_ID': 610000,
                 'prov_Name': '陕西'},
    'shangqiu': {'city_ID': 411400,
                 'city_Name': '商丘',
                 'city_Pinyin': 'shangqiu',
                 'prov_ID': 410000,
                 'prov_Name': '河南'},
    'shangrao': {'city_ID': 361100,
                 'city_Name': '上饶',
                 'city_Pinyin': 'shangrao',
                 'prov_ID': 360000,
                 'prov_Name': '江西'},
    'shannan': {'city_ID': 540500,
                'city_Name': '山南',
                'city_Pinyin': 'shannan',
                'prov_ID': 540000,
                'prov_Name': '西藏'},
    'shantou': {'city_ID': 440500,
                'city_Name': '汕头',
                'city_Pinyin': 'shantou',
                'prov_ID': 440000,
                'prov_Name': '广东'},
    'shanwei': {'city_ID': 441500,
                'city_Name': '汕尾',
                'city_Pinyin': 'shanwei',
                'prov_ID': 440000,
                'prov_Name': '广东'},
    'shaoguan': {'city_ID': 440200,
                 'city_Name': '韶关',
                 'city_Pinyin': 'shaoguan',
                 'prov_ID': 440000,
                 'prov_Name': '广东'},
    'shaoxing': {'city_ID': 330600,
                 'city_Name': '绍兴',
                 'city_Pinyin': 'shaoxing',
                 'prov_ID': 330000,
                 'prov_Name': '浙江'},
    'shaoyang': {'city_ID': 430500,
                 'city_Name': '邵阳',
                 'city_Pinyin': 'shaoyang',
                 'prov_ID': 430000,
                 'prov_Name': '湖南'},
    'shennongjia': {'city_ID': 429021,
                    'city_Name': '神农架',
                    'city_Pinyin': 'shennongjia',
                    'prov_ID': 420000,
                    'prov_Name': '湖北'},
    'shenyang': {'city_ID': 210100,
                 'city_Name': '沈阳',
                 'city_Pinyin': 'shenyang',
                 'prov_ID': 210000,
                 'prov_Name': '辽宁'},
    'shenzhen': {'city_ID': 440300,
                 'city_Name': '深圳',
                 'city_Pinyin': 'shenzhen',
                 'prov_ID': 440000,
                 'prov_Name': '广东'},
    'shihezi': {'city_ID': 659001,
                'city_Name': '石河子',
                'city_Pinyin': 'shihezi',
                'prov_ID': 650000,
                'prov_Name': '新疆'},
    'shijiazhuang': {'city_ID': 130100,
                     'city_Name': '石家庄',
                     'city_Pinyin': 'shijiazhuang',
                     'prov_ID': 130000,
                     'prov_Name': '河北'},
    'shiyan': {'city_ID': 420300,
               'city_Name': '十堰',
               'city_Pinyin': 'shiyan',
               'prov_ID': 420000,
               'prov_Name': '湖北'},
    'shizuishan': {'city_ID': 640200,
                   'city_Name': '石嘴山',
                   'city_Pinyin': 'shizuishan',
                   'prov_ID': 640000,
                   'prov_Name': '宁夏'},
    'shuangheshi': {'city_ID': 659007,
                    'city_Name': '双河市',
                    'city_Pinyin': 'shuangheshi',
                    'prov_ID': 650000,
                    'prov_Name': '新疆'},
    'shuangyashan': {'city_ID': 230500,
                     'city_Name': '双鸭山',
                     'city_Pinyin': 'shuangyashan',
                     'prov_ID': 230000,
                     'prov_Name': '黑龙江'},
    'shuozhou': {'city_ID': 140600,
                 'city_Name': '朔州',
                 'city_Pinyin': 'shuozhou',
                 'prov_ID': 140000,
                 'prov_Name': '山西'},
    'siping': {'city_ID': 220300,
               'city_Name': '四平',
               'city_Pinyin': 'siping',
               'prov_ID': 220000,
               'prov_Name': '吉林'},
    'songyuan': {'city_ID': 220700,
                 'city_Name': '松原',
                 'city_Pinyin': 'songyuan',
                 'prov_ID': 220000,
                 'prov_Name': '吉林'},
    'su_zhou': {'city_ID': 341300,
                'city_Name': '宿州',
                'city_Pinyin': 'su_zhou',
                'prov_ID': 340000,
                'prov_Name': '安徽'},
    'suihua': {'city_ID': 231200,
               'city_Name': '绥化',
               'city_Pinyin': 'suihua',
               'prov_ID': 230000,
               'prov_Name': '黑龙江'},
    'suining': {'city_ID': 510900,
                'city_Name': '遂宁',
                'city_Pinyin': 'suining',
                'prov_ID': 510000,
                'prov_Name': '四川'},
    'suizhou': {'city_ID': 421300,
                'city_Name': '随州',
                'city_Pinyin': 'suizhou',
                'prov_ID': 420000,
                'prov_Name': '湖北'},
    'suqian': {'city_ID': 321300,
               'city_Name': '宿迁',
               'city_Pinyin': 'suqian',
               'prov_ID': 320000,
               'prov_Name': '江苏'},
    'suzhou': {'city_ID': 320500,
               'city_Name': '苏州',
               'city_Pinyin': 'suzhou',
               'prov_ID': 320000,
               'prov_Name': '江苏'},
    'tacheng': {'city_ID': 654200,
                'city_Name': '塔城',
                'city_Pinyin': 'tacheng',
                'prov_ID': 650000,
                'prov_Name': '新疆'},
    'tai_zhou': {'city_ID': 321200,
                 'city_Name': '泰州',
                 'city_Pinyin': 'tai_zhou',
                 'prov_ID': 320000,
                 'prov_Name': '江苏'},
    'taian': {'city_ID': 370900,
              'city_Name': '泰安',
              'city_Pinyin': 'taian',
              'prov_ID': 370000,
              'prov_Name': '山东'},
    'taiwan': {'city_ID': 710100,
               'city_Name': '台湾',
               'city_Pinyin': 'taiwan',
               'prov_ID': 710000,
               'prov_Name': '台湾'},
    'taiyuan': {'city_ID': 140100,
                'city_Name': '太原',
                'city_Pinyin': 'taiyuan',
                'prov_ID': 140000,
                'prov_Name': '山西'},
    'taizhou': {'city_ID': 331000,
                'city_Name': '台州',
                'city_Pinyin': 'taizhou',
                'prov_ID': 330000,
                'prov_Name': '浙江'},
    'tangshan': {'city_ID': 130200,
                 'city_Name': '唐山',
                 'city_Pinyin': 'tangshan',
                 'prov_ID': 130000,
                 'prov_Name': '河北'},
    'tianjin': {'city_ID': 120100,
                'city_Name': '天津',
                'city_Pinyin': 'tianjin',
                'prov_ID': 120000,
                'prov_Name': '天津'},
    'tianmen': {'city_ID': 429006,
                'city_Name': '天门',
                'city_Pinyin': 'tianmen',
                'prov_ID': 420000,
                'prov_Name': '湖北'},
    'tianshui': {'city_ID': 620500,
                 'city_Name': '天水',
                 'city_Pinyin': 'tianshui',
                 'prov_ID': 620000,
                 'prov_Name': '甘肃'},
    'tieling': {'city_ID': 211200,
                'city_Name': '铁岭',
                'city_Pinyin': 'tieling',
                'prov_ID': 210000,
                'prov_Name': '辽宁'},
    'tiemenguanshi': {'city_ID': 659006,
                      'city_Name': '铁门关市',
                      'city_Pinyin': 'tiemenguanshi',
                      'prov_ID': 650000,
                      'prov_Name': '新疆'},
    'tongchuan': {'city_ID': 610200,
                  'city_Name': '铜川',
                  'city_Pinyin': 'tongchuan',
                  'prov_ID': 610000,
                  'prov_Name': '陕西'},
    'tonghua': {'city_ID': 220500,
                'city_Name': '通化',
                'city_Pinyin': 'tonghua',
                'prov_ID': 220000,
                'prov_Name': '吉林'},
    'tongliao': {'city_ID': 150500,
                 'city_Name': '通辽',
                 'city_Pinyin': 'tongliao',
                 'prov_ID': 150000,
                 'prov_Name': '内蒙古'},
    'tongling': {'city_ID': 340700,
                 'city_Name': '铜陵',
                 'city_Pinyin': 'tongling',
                 'prov_ID': 340000,
                 'prov_Name': '安徽'},
    'tongren': {'city_ID': 520600,
                'city_Name': '铜仁',
                'city_Pinyin': 'tongren',
                'prov_ID': 520000,
                'prov_Name': '贵州'},
    'tulufan': {'city_ID': 650400,
                'city_Name': '吐鲁番',
                'city_Pinyin': 'tulufan',
                'prov_ID': 650000,
                'prov_Name': '新疆'},
    'tumushuke': {'city_ID': 659003,
                  'city_Name': '图木舒克',
                  'city_Pinyin': 'tumushuke',
                  'prov_ID': 650000,
                  'prov_Name': '新疆'},
    'tunchang': {'city_ID': 469022,
                 'city_Name': '屯昌',
                 'city_Pinyin': 'tunchang',
                 'prov_ID': 460000,
                 'prov_Name': '海南'},
    'wanning': {'city_ID': 469006,
                'city_Name': '万宁',
                'city_Pinyin': 'wanning',
                'prov_ID': 460000,
                'prov_Name': '海南'},
    'weifang': {'city_ID': 370700,
                'city_Name': '潍坊',
                'city_Pinyin': 'weifang',
                'prov_ID': 370000,
                'prov_Name': '山东'},
    'weihai': {'city_ID': 371000,
               'city_Name': '威海',
               'city_Pinyin': 'weihai',
               'prov_ID': 370000,
               'prov_Name': '山东'},
    'weinan': {'city_ID': 610500,
               'city_Name': '渭南',
               'city_Pinyin': 'weinan',
               'prov_ID': 610000,
               'prov_Name': '陕西'},
    'wenchang': {'city_ID': 469005,
                 'city_Name': '文昌',
                 'city_Pinyin': 'wenchang',
                 'prov_ID': 460000,
                 'prov_Name': '海南'},
    'wenshan': {'city_ID': 532600,
                'city_Name': '文山',
                'city_Pinyin': 'wenshan',
                'prov_ID': 530000,
                'prov_Name': '云南'},
    'wenzhou': {'city_ID': 330300,
                'city_Name': '温州',
                'city_Pinyin': 'wenzhou',
                'prov_ID': 330000,
                'prov_Name': '浙江'},
    'wuhai': {'city_ID': 150300,
              'city_Name': '乌海',
              'city_Pinyin': 'wuhai',
              'prov_ID': 150000,
              'prov_Name': '内蒙古'},
    'wuhan': {'city_ID': 420100,
              'city_Name': '武汉',
              'city_Pinyin': 'wuhan',
              'prov_ID': 420000,
              'prov_Name': '湖北'},
    'wuhu': {'city_ID': 340200,
             'city_Name': '芜湖',
             'city_Pinyin': 'wuhu',
             'prov_ID': 340000,
             'prov_Name': '安徽'},
    'wujiaqu': {'city_ID': 659004,
                'city_Name': '五家渠',
                'city_Pinyin': 'wujiaqu',
                'prov_ID': 650000,
                'prov_Name': '新疆'},
    'wulanchabu': {'city_ID': 150900,
                   'city_Name': '乌兰察布',
                   'city_Pinyin': 'wulanchabu',
                   'prov_ID': 150000,
                   'prov_Name': '内蒙古'},
    'wulumuqi': {'city_ID': 650100,
                 'city_Name': '乌鲁木齐',
                 'city_Pinyin': 'wulumuqi',
                 'prov_ID': 650000,
                 'prov_Name': '新疆'},
    'wuwei': {'city_ID': 620600,
              'city_Name': '武威',
              'city_Pinyin': 'wuwei',
              'prov_ID': 620000,
              'prov_Name': '甘肃'},
    'wuxi': {'city_ID': 320200,
             'city_Name': '无锡',
             'city_Pinyin': 'wuxi',
             'prov_ID': 320000,
             'prov_Name': '江苏'},
    'wuzhishan': {'city_ID': 469001,
                  'city_Name': '五指山',
                  'city_Pinyin': 'wuzhishan',
                  'prov_ID': 460000,
                  'prov_Name': '海南'},
    'wuzhong': {'city_ID': 640300,
                'city_Name': '吴忠',
                'city_Pinyin': 'wuzhong',
                'prov_ID': 640000,
                'prov_Name': '宁夏'},
    'wuzhou': {'city_ID': 450400,
               'city_Name': '梧州',
               'city_Pinyin': 'wuzhou',
               'prov_ID': 450000,
               'prov_Name': '广西'},
    'xiamen': {'city_ID': 350200,
               'city_Name': '厦门',
               'city_Pinyin': 'xiamen',
               'prov_ID': 350000,
               'prov_Name': '福建'},
    'xian': {'city_ID': 610100,
             'city_Name': '西安',
             'city_Pinyin': 'xian',
             'prov_ID': 610000,
             'prov_Name': '陕西'},
    'xianggang': {'city_ID': 810100,
                  'city_Name': '香港',
                  'city_Pinyin': 'xianggang',
                  'prov_ID': 810000,
                  'prov_Name': '香港'},
    'xiangtan': {'city_ID': 430300,
                 'city_Name': '湘潭',
                 'city_Pinyin': 'xiangtan',
                 'prov_ID': 430000,
                 'prov_Name': '湖南'},
    'xiangxi': {'city_ID': 433100,
                'city_Name': '湘西',
                'city_Pinyin': 'xiangxi',
                'prov_ID': 430000,
                'prov_Name': '湖南'},
    'xiangyang': {'city_ID': 420600,
                  'city_Name': '襄阳',
                  'city_Pinyin': 'xiangyang',
                  'prov_ID': 420000,
                  'prov_Name': '湖北'},
    'xianning': {'city_ID': 421200,
                 'city_Name': '咸宁',
                 'city_Pinyin': 'xianning',
                 'prov_ID': 420000,
                 'prov_Name': '湖北'},
    'xiantao': {'city_ID': 429004,
                'city_Name': '仙桃',
                'city_Pinyin': 'xiantao',
                'prov_ID': 420000,
                'prov_Name': '湖北'},
    'xianyang': {'city_ID': 610400,
                 'city_Name': '咸阳',
                 'city_Pinyin': 'xianyang',
                 'prov_ID': 610000,
                 'prov_Name': '陕西'},
    'xiaogan': {'city_ID': 420900,
                'city_Name': '孝感',
                'city_Pinyin': 'xiaogan',
                'prov_ID': 420000,
                'prov_Name': '湖北'},
    'xilinguolemeng': {'city_ID': 152500,
                       'city_Name': '锡林郭勒盟',
                       'city_Pinyin': 'xilinguolemeng',
                       'prov_ID': 150000,
                       'prov_Name': '内蒙古'},
    'xinganmeng': {'city_ID': 152200,
                   'city_Name': '兴安盟',
                   'city_Pinyin': 'xinganmeng',
                   'prov_ID': 150000,
                   'prov_Name': '内蒙古'},
    'xingtai': {'city_ID': 130500,
                'city_Name': '邢台',
                'city_Pinyin': 'xingtai',
                'prov_ID': 130000,
                'prov_Name': '河北'},
    'xingyishi': {'city_ID': 522300,
                  'city_Name': '兴义市',
                  'city_Pinyin': 'xingyishi',
                  'prov_ID': 520000,
                  'prov_Name': '贵州'},
    'xining': {'city_ID': 630100,
               'city_Name': '西宁',
               'city_Pinyin': 'xining',
               'prov_ID': 630000,
               'prov_Name': '青海'},
    'xinxiang': {'city_ID': 410700,
                 'city_Name': '新乡',
                 'city_Pinyin': 'xinxiang',
                 'prov_ID': 410000,
                 'prov_Name': '河南'},
    'xinyang': {'city_ID': 411500,
                'city_Name': '信阳',
                'city_Pinyin': 'xinyang',
                'prov_ID': 410000,
                'prov_Name': '河南'},
    'xinyu': {'city_ID': 360500,
              'city_Name': '新余',
              'city_Pinyin': 'xinyu',
              'prov_ID': 360000,
              'prov_Name': '江西'},
    'xinzhou': {'city_ID': 140900,
                'city_Name': '忻州',
                'city_Pinyin': 'xinzhou',
                'prov_ID': 140000,
                'prov_Name': '山西'},
    'xishuangbanna': {'city_ID': 532800,
                      'city_Name': '西双版纳',
                      'city_Pinyin': 'xishuangbanna',
                      'prov_ID': 530000,
                      'prov_Name': '云南'},
    'xuancheng': {'city_ID': 341800,
                  'city_Name': '宣城',
                  'city_Pinyin': 'xuancheng',
                  'prov_ID': 340000,
                  'prov_Name': '安徽'},
    'xuchang': {'city_ID': 411000,
                'city_Name': '许昌',
                'city_Pinyin': 'xuchang',
                'prov_ID': 410000,
                'prov_Name': '河南'},
    'xuzhou': {'city_ID': 320300,
               'city_Name': '徐州',
               'city_Pinyin': 'xuzhou',
               'prov_ID': 320000,
               'prov_Name': '江苏'},
    'yaan': {'city_ID': 511800,
             'city_Name': '雅安',
             'city_Pinyin': 'yaan',
             'prov_ID': 510000,
             'prov_Name': '四川'},
    'yanan': {'city_ID': 610600,
              'city_Name': '延安',
              'city_Pinyin': 'yanan',
              'prov_ID': 610000,
              'prov_Name': '陕西'},
    'yanbian': {'city_ID': 222400,
                'city_Name': '延边',
                'city_Pinyin': 'yanbian',
                'prov_ID': 220000,
                'prov_Name': '吉林'},
    'yancheng': {'city_ID': 320900,
                 'city_Name': '盐城',
                 'city_Pinyin': 'yancheng',
                 'prov_ID': 320000,
                 'prov_Name': '江苏'},
    'yangjiang': {'city_ID': 441700,
                  'city_Name': '阳江',
                  'city_Pinyin': 'yangjiang',
                  'prov_ID': 440000,
                  'prov_Name': '广东'},
    'yangquan': {'city_ID': 140300,
                 'city_Name': '阳泉',
                 'city_Pinyin': 'yangquan',
                 'prov_ID': 140000,
                 'prov_Name': '山西'},
    'yangzhou': {'city_ID': 321000,
                 'city_Name': '扬州',
                 'city_Pinyin': 'yangzhou',
                 'prov_ID': 320000,
                 'prov_Name': '江苏'},
    'yantai': {'city_ID': 370600,
               'city_Name': '烟台',
               'city_Pinyin': 'yantai',
               'prov_ID': 370000,
               'prov_Name': '山东'},
    'yi_chun': {'city_ID': 360900,
                'city_Name': '宜春',
                'city_Pinyin': 'yi_chun',
                'prov_ID': 360000,
                'prov_Name': '江西'},
    'yibin': {'city_ID': 511500,
              'city_Name': '宜宾',
              'city_Pinyin': 'yibin',
              'prov_ID': 510000,
              'prov_Name': '四川'},
    'yichang': {'city_ID': 420500,
                'city_Name': '宜昌',
                'city_Pinyin': 'yichang',
                'prov_ID': 420000,
                'prov_Name': '湖北'},
    'yichun': {'city_ID': 230700,
               'city_Name': '伊春',
               'city_Pinyin': 'yichun',
               'prov_ID': 230000,
               'prov_Name': '黑龙江'},
    'yili': {'city_ID': 654000,
             'city_Name': '伊犁',
             'city_Pinyin': 'yili',
             'prov_ID': 650000,
             'prov_Name': '新疆'},
    'yinchuan': {'city_ID': 640100,
                 'city_Name': '银川',
                 'city_Pinyin': 'yinchuan',
                 'prov_ID': 640000,
                 'prov_Name': '宁夏'},
    'yingkou': {'city_ID': 210800,
                'city_Name': '营口',
                'city_Pinyin': 'yingkou',
                'prov_ID': 210000,
                'prov_Name': '辽宁'},
    'yingtan': {'city_ID': 360600,
                'city_Name': '鹰潭',
                'city_Pinyin': 'yingtan',
                'prov_ID': 360000,
                'prov_Name': '江西'},
    'yiyang': {'city_ID': 430900,
               'city_Name': '益阳',
               'city_Pinyin': 'yiyang',
               'prov_ID': 430000,
               'prov_Name': '湖南'},
    'yongzhou': {'city_ID': 431100,
                 'city_Name': '永州',
                 'city_Pinyin': 'yongzhou',
                 'prov_ID': 430000,
                 'prov_Name': '湖南'},
    'yu_lin': {'city_ID': 450900,
               'city_Name': '玉林',
               'city_Pinyin': 'yu_lin',
               'prov_ID': 450000,
               'prov_Name': '广西'},
    'yueyang': {'city_ID': 430600,
                'city_Name': '岳阳',
                'city_Pinyin': 'yueyang',
                'prov_ID': 430000,
                'prov_Name': '湖南'},
    'yulin': {'city_ID': 610800,
              'city_Name': '榆林',
              'city_Pinyin': 'yulin',
              'prov_ID': 610000,
              'prov_Name': '陕西'},
    'yuncheng': {'city_ID': 140800,
                 'city_Name': '运城',
                 'city_Pinyin': 'yuncheng',
                 'prov_ID': 140000,
                 'prov_Name': '山西'},
    'yunfu': {'city_ID': 445300,
              'city_Name': '云浮',
              'city_Pinyin': 'yunfu',
              'prov_ID': 440000,
              'prov_Name': '广东'},
    'yushu': {'city_ID': 632700,
              'city_Name': '玉树',
              'city_Pinyin': 'yushu',
              'prov_ID': 630000,
              'prov_Name': '青海'},
    'yuxi': {'city_ID': 530400,
             'city_Name': '玉溪',
             'city_Pinyin': 'yuxi',
             'prov_ID': 530000,
             'prov_Name': '云南'},
    'zaozhuang': {'city_ID': 370400,
                  'city_Name': '枣庄',
                  'city_Pinyin': 'zaozhuang',
                  'prov_ID': 370000,
                  'prov_Name': '山东'},
    'zhangjiajie': {'city_ID': 430800,
                    'city_Name': '张家界',
                    'city_Pinyin': 'zhangjiajie',
                    'prov_ID': 430000,
                    'prov_Name': '湖南'},
    'zhangjiakou': {'city_ID': 130700,
                    'city_Name': '张家口',
                    'city_Pinyin': 'zhangjiakou',
                    'prov_ID': 130000,
                    'prov_Name': '河北'},
    'zhangye': {'city_ID': 620700,
                'city_Name': '张掖',
                'city_Pinyin': 'zhangye',
                'prov_ID': 620000,
                'prov_Name': '甘肃'},
    'zhangzhou': {'city_ID': 350600,
                  'city_Name': '漳州',
                  'city_Pinyin': 'zhangzhou',
                  'prov_ID': 350000,
                  'prov_Name': '福建'},
    'zhanjiang': {'city_ID': 440800,
                  'city_Name': '湛江',
                  'city_Pinyin': 'zhanjiang',
                  'prov_ID': 440000,
                  'prov_Name': '广东'},
    'zhaoqing': {'city_ID': 441200,
                 'city_Name': '肇庆',
                 'city_Pinyin': 'zhaoqing',
                 'prov_ID': 440000,
                 'prov_Name': '广东'},
    'zhaotong': {'city_ID': 530600,
                 'city_Name': '昭通',
                 'city_Pinyin': 'zhaotong',
                 'prov_ID': 530000,
                 'prov_Name': '云南'},
    'zhengzhou': {'city_ID': 410100,
                  'city_Name': '郑州',
                  'city_Pinyin': 'zhengzhou',
                  'prov_ID': 410000,
                  'prov_Name': '河南'},
    'zhenjiang': {'city_ID': 321100,
                  'city_Name': '镇江',
                  'city_Pinyin': 'zhenjiang',
                  'prov_ID': 320000,
                  'prov_Name': '江苏'},
    'zhongshan': {'city_ID': 442000,
                  'city_Name': '中山',
                  'city_Pinyin': 'zhongshan',
                  'prov_ID': 440000,
                  'prov_Name': '广东'},
    'zhongwei': {'city_ID': 640500,
                 'city_Name': '中卫',
                 'city_Pinyin': 'zhongwei',
                 'prov_ID': 640000,
                 'prov_Name': '宁夏'},
    'zhoukou': {'city_ID': 411600,
                'city_Name': '周口',
                'city_Pinyin': 'zhoukou',
                'prov_ID': 410000,
                'prov_Name': '河南'},
    'zhoushan': {'city_ID': 330900,
                 'city_Name': '舟山',
                 'city_Pinyin': 'zhoushan',
                 'prov_ID': 330000,
                 'prov_Name': '浙江'},
    'zhuhai': {'city_ID': 440400,
               'city_Name': '珠海',
               'city_Pinyin': 'zhuhai',
               'prov_ID': 440000,
               'prov_Name': '广东'},
    'zhumadian': {'city_ID': 411700,
                  'city_Name': '驻马店',
                  'city_Pinyin': 'zhumadian',
                  'prov_ID': 410000,
                  'prov_Name': '河南'},
    'zhuzhou': {'city_ID': 430200,
                'city_Name': '株洲',
                'city_Pinyin': 'zhuzhou',
                'prov_ID': 430000,
                'prov_Name': '湖南'},
    'zibo': {'city_ID': 370300,
             'city_Name': '淄博',
             'city_Pinyin': 'zibo',
             'prov_ID': 370000,
             'prov_Name': '山东'},
    'zigong': {'city_ID': 510300,
               'city_Name': '自贡',
               'city_Pinyin': 'zigong',
               'prov_ID': 510000,
               'prov_Name': '四川'},
    'ziyang': {'city_ID': 512000,
               'city_Name': '资阳',
               'city_Pinyin': 'ziyang',
               'prov_ID': 510000,
               'prov_Name': '四川'},
    'zunyi': {'city_ID': 520300,
              'city_Name': '遵义',
              'city_Pinyin': 'zunyi',
              'prov_ID': 520000,
              'prov_Name': '贵州'}}
settings = {
    # 'MONGODB_USER': 'admin',
    # 'MONGODB_PWD': 'ABCabc123',
    'MONGODB_PORT': 27017,
    'MONGODB_SERVER': '192.168.1.94',
    'MONGODB_DB': 'newcar_price',
    'MONGODB_COLLECTION': 'autohome_price',

}
local_time = time.strftime('%Y-%m-%d', time.localtime())
connection = pymongo.MongoClient(
    settings['MONGODB_SERVER'],
    settings['MONGODB_PORT']
)
db = connection[settings['MONGODB_DB']]
collection = db[settings['MONGODB_COLLECTION']]

count = collection.count()
name = settings['MONGODB_COLLECTION'] + '_' + str(local_time)
if count:
    print(count)
    collection.rename(name)


city_list = []
for k, v in city_dic.items():
    city_url = f"https://dealer.autohome.com.cn/{k}/"
    city_list.append(city_url)

pool = redis.ConnectionPool(host='192.168.1.241', port=6379, db=15)
con = redis.Redis(connection_pool=pool)
c = con.client()

c.delete('autohome_price_new:dupefilter')
c.lpush('autohome_price:start_urls', *city_list)


# p = c.lpop('autohome_gz:start_urls')
# p = bytes.decode(p)
# print(p)
# con.close()




