# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class GanjiItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    datasave = scrapy.Field()
    carinfo0 = scrapy.Field()
    carinfo1 = scrapy.Field()
    carinfo2 = scrapy.Field()
    carinfo3 = scrapy.Field()
    carinfo4 = scrapy.Field()
    carinfo5 = scrapy.Field()
    carinfo6 = scrapy.Field()
    carinfo7 = scrapy.Field()
    carinfo8 = scrapy.Field()
    carinfo9 = scrapy.Field()
    carinfo10 = scrapy.Field()
    carinfo11 = scrapy.Field()
    carinfo12 = scrapy.Field()
    carinfo13 = scrapy.Field()
    carinfo14 = scrapy.Field()
    carinfo15 = scrapy.Field()
    carinfo16 = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    salesdesc = scrapy.Field()
    carid = scrapy.Field()
    makeyear = scrapy.Field()
    producestatus = scrapy.Field()
    salestatus = scrapy.Field()
    type = scrapy.Field()
    price = scrapy.Field()
    output = scrapy.Field()
    geartype = scrapy.Field()
    gearnum = scrapy.Field()
    length = scrapy.Field()
    width = scrapy.Field()
    height = scrapy.Field()
    wheel = scrapy.Field()
    weight = scrapy.Field()
    method = scrapy.Field()
    maxps = scrapy.Field()
    emission = scrapy.Field()
    fueltype = scrapy.Field()
    fuelnumber = scrapy.Field()
    assitanttype = scrapy.Field()
    backhang = scrapy.Field()

class AutohomeItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    datasave = scrapy.Field()
    jsonsave = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    carid = scrapy.Field()
    salesdesc = scrapy.Field()
    price = scrapy.Field()
    factoryname = scrapy.Field()
    type = scrapy.Field()
    motor = scrapy.Field()
    gear = scrapy.Field()
    lengthwh = scrapy.Field()
    body = scrapy.Field()
    maxspeed = scrapy.Field()
    accelerate = scrapy.Field()
    actualaccelerate = scrapy.Field()
    actualstop = scrapy.Field()
    actualpetrol = scrapy.Field()
    petrol = scrapy.Field()
    actual_liftoff_distance = scrapy.Field()
    warranty = scrapy.Field()
    length = scrapy.Field()
    width = scrapy.Field()
    height = scrapy.Field()
    wheel = scrapy.Field()
    frontwheel = scrapy.Field()
    backwheel = scrapy.Field()
    liftoff_distance = scrapy.Field()
    weight = scrapy.Field()
    body = scrapy.Field()
    doors = scrapy.Field()
    seats = scrapy.Field()
    fuelvolumn = scrapy.Field()
    baggage = scrapy.Field()
    motortype = scrapy.Field()
    cylinder = scrapy.Field()
    output = scrapy.Field()
    method = scrapy.Field()
    lwv = scrapy.Field()
    lwvnumber = scrapy.Field()
    valve = scrapy.Field()
    compress = scrapy.Field()
    valve_gear = scrapy.Field()
    cylinder_diameter = scrapy.Field()
    cylinder_travel = scrapy.Field()
    maxps = scrapy.Field()
    maxpower = scrapy.Field()
    maxrpm = scrapy.Field()
    maxnm = scrapy.Field()
    maxtorque = scrapy.Field()
    motortechnique = scrapy.Field()
    fuletype = scrapy.Field()
    fulevolumn = scrapy.Field()
    fulemethod = scrapy.Field()
    cylinder_head_material = scrapy.Field()
    cylinder_body_material = scrapy.Field()
    emission = scrapy.Field()
    geardesc = scrapy.Field()
    gearnumber = scrapy.Field()
    geartype = scrapy.Field()
    driveway = scrapy.Field()
    frontgauge = scrapy.Field()
    backgauge = scrapy.Field()
    assistanttype = scrapy.Field()
    body_structure = scrapy.Field()
    frontbrake = scrapy.Field()
    backbrake = scrapy.Field()
    parking_brake_type = scrapy.Field()
    frontwheel = scrapy.Field()
    backwheel = scrapy.Field()
    sparewheel = scrapy.Field()

class AutohomefamilyItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    maxprice = scrapy.Field()
    minprice = scrapy.Field()
    seriesPicUrl=scrapy.Field()

class XcarItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    datasave = scrapy.Field()
    brandname=scrapy.Field()
    brandid=scrapy.Field()
    factoryname=scrapy.Field()
    factoryid=scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    carid = scrapy.Field()
    salesdesc = scrapy.Field()
    makeyear = scrapy.Field()
    price = scrapy.Field()
    an_price = scrapy.Field()
    bname = scrapy.Field()
    type_name = scrapy.Field()
    disl_working_mpower = scrapy.Field()
    dynamic = scrapy.Field()
    speed_transtype = scrapy.Field()
    length_width_height = scrapy.Field()
    door_seat_frame = scrapy.Field()
    ear = scrapy.Field()
    mspeed = scrapy.Field()
    hatime = scrapy.Field()
    comfuel = scrapy.Field()
    ypolicy = scrapy.Field()
    length = scrapy.Field()
    width = scrapy.Field()
    height = scrapy.Field()
    wheelbase = scrapy.Field()
    weight = scrapy.Field()
    clearance = scrapy.Field()
    btread = scrapy.Field()
    ftread = scrapy.Field()
    frame = scrapy.Field()
    door = scrapy.Field()
    seat = scrapy.Field()
    oilbox = scrapy.Field()
    trunk = scrapy.Field()
    mtrunk = scrapy.Field()
    enginetype = scrapy.Field()
    disl = scrapy.Field()
    mdisl = scrapy.Field()
    working = scrapy.Field()
    cyarrange = scrapy.Field()
    cylinder = scrapy.Field()
    cylindernum = scrapy.Field()
    cr = scrapy.Field()
    valvegear = scrapy.Field()
    cylinderbore = scrapy.Field()
    journey = scrapy.Field()
    cylinderblock = scrapy.Field()
    cylinderhead = scrapy.Field()
    mhpower = scrapy.Field()
    mpower = scrapy.Field()
    mtorque = scrapy.Field()
    fuel = scrapy.Field()
    fuelno = scrapy.Field()
    sfueltype = scrapy.Field()
    envstand = scrapy.Field()
    stechnology = scrapy.Field()
    speed = scrapy.Field()
    transtype = scrapy.Field()
    tranname = scrapy.Field()
    drivetype = scrapy.Field()
    awdtype = scrapy.Field()
    mdifferentialtype = scrapy.Field()
    carstruc = scrapy.Field()
    hptype = scrapy.Field()
    fsustype_text = scrapy.Field()
    bsustype_text = scrapy.Field()
    fdifferentiallock = scrapy.Field()
    mdifferentiallock = scrapy.Field()
    rdifferentiallock = scrapy.Field()
    fbraketype = scrapy.Field()
    bbraketype = scrapy.Field()
    park = scrapy.Field()
    ftiresize = scrapy.Field()
    btiresize = scrapy.Field()
    sparetire = scrapy.Field()
    isdairbag = scrapy.Field()
    isfhairbag = scrapy.Field()
    isfsairbag = scrapy.Field()
    iskairbag = scrapy.Field()
    pedeairbag = scrapy.Field()
    isofix = scrapy.Field()
    istpmonitor = scrapy.Field()
    istpruning = scrapy.Field()
    isseatbeltti = scrapy.Field()
    iseanti = scrapy.Field()
    enginelock = scrapy.Field()
    iscclock = scrapy.Field()
    isrekey = scrapy.Field()
    baws = scrapy.Field()
    nightwork = scrapy.Field()
    isabs = scrapy.Field()
    isebd = scrapy.Field()
    iseba = scrapy.Field()
    isasr = scrapy.Field()
    isesp = scrapy.Field()
    hillassist = scrapy.Field()
    hdc = scrapy.Field()
    isuphillassist = scrapy.Field()
    isandstitch = scrapy.Field()
    deviatewar = scrapy.Field()
    iskbsus = scrapy.Field()
    issteesys = scrapy.Field()
    aba = scrapy.Field()
    iswindow = scrapy.Field()
    isarwindow = scrapy.Field()
    isspround = scrapy.Field()
    isaluhub = scrapy.Field()
    eletric_sdoor = scrapy.Field()
    electricdoor = scrapy.Field()
    rack = scrapy.Field()
    agrille = scrapy.Field()
    elecartrunk = scrapy.Field()
    isleasw = scrapy.Field()
    isswud = scrapy.Field()
    ismultisw = scrapy.Field()
    steelectrol = scrapy.Field()
    steewhmory = scrapy.Field()
    iswheelhot = scrapy.Field()
    isswshift = scrapy.Field()
    isassibc = scrapy.Field()
    isparkvideo = scrapy.Field()
    panorcamera = scrapy.Field()
    ispark = scrapy.Field()
    isascd = scrapy.Field()
    autcruise = scrapy.Field()
    isnokeyinto = scrapy.Field()
    isnokeysys = scrapy.Field()
    display = scrapy.Field()
    ishud = scrapy.Field()
    isleaseat = scrapy.Field()
    sportseat = scrapy.Field()
    isseatadj = scrapy.Field()
    isfseatadj = scrapy.Field()
    reseateletrol = scrapy.Field()
    iswaistadj = scrapy.Field()
    shouldersdj = scrapy.Field()
    thighsdj = scrapy.Field()
    iseseatmem = scrapy.Field()
    isseathot = scrapy.Field()
    isseatknead = scrapy.Field()
    chairmassage = scrapy.Field()
    secseatbadj = scrapy.Field()
    secseatfbwadj = scrapy.Field()
    isbseatlay = scrapy.Field()
    isbseatplay = scrapy.Field()
    thirdrowseat = scrapy.Field()
    isfarmrest = scrapy.Field()
    isbcup = scrapy.Field()
    isgps = scrapy.Field()
    isbluetooth = scrapy.Field()
    iscclcd = scrapy.Field()
    isblcd = scrapy.Field()
    humancomption = scrapy.Field()
    interservice = scrapy.Field()
    istv = scrapy.Field()
    audio_brand = scrapy.Field()
    aux = scrapy.Field()
    ismp3 = scrapy.Field()
    isscd = scrapy.Field()
    ismcd = scrapy.Field()
    allcd = scrapy.Field()
    onedvd = scrapy.Field()
    ismdvd = scrapy.Field()
    is2audio = scrapy.Field()
    is4audio = scrapy.Field()
    is6audio = scrapy.Field()
    is8audio = scrapy.Field()
    isxelamp = scrapy.Field()
    isledlamp = scrapy.Field()
    isjglamp = scrapy.Field()
    ishfoglamp = scrapy.Field()
    dayrunlight = scrapy.Field()
    islampheiadj = scrapy.Field()
    isautohlamp = scrapy.Field()
    bendauxlig = scrapy.Field()
    isturnhlamp = scrapy.Field()
    islampclset = scrapy.Field()
    interatmlamp = scrapy.Field()
    isfewindow = scrapy.Field()
    isgnhand = scrapy.Field()
    ispreventionuv = scrapy.Field()
    fseat_pglass = scrapy.Field()
    isermirror = scrapy.Field()
    ishotrmirror = scrapy.Field()
    iseprmirror = scrapy.Field()
    ecm = scrapy.Field()
    ismemorymirror = scrapy.Field()
    isbssvisor = scrapy.Field()
    ishbsvisor = scrapy.Field()
    issvisordr = scrapy.Field()
    isinswiper = scrapy.Field()
    rwiper = scrapy.Field()
    isairc = scrapy.Field()
    isaairc = scrapy.Field()
    fseat_ac = scrapy.Field()
    isbsairo = scrapy.Field()
    istempdct = scrapy.Field()
    isairfilter = scrapy.Field()
    iscaricebox = scrapy.Field()
    other = scrapy.Field()
class PcautoItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    datasave = scrapy.Field()
    jsonsave = scrapy.Field()
    brandname= scrapy.Field()
    brandid = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    carid = scrapy.Field()
    salesdesc = scrapy.Field()
    price = scrapy.Field()
    level = scrapy.Field()
    salemonth = scrapy.Field()
    motor = scrapy.Field()
    method = scrapy.Field()
    maxps = scrapy.Field()
    maxnm = scrapy.Field()
    gear = scrapy.Field()
    bodystyle = scrapy.Field()
    lengthwh = scrapy.Field()
    wheel = scrapy.Field()
    maxspeed = scrapy.Field()
    accelerate = scrapy.Field()
    actualaccelerate = scrapy.Field()
    actualstop = scrapy.Field()
    petrol = scrapy.Field()
    warranty = scrapy.Field()
    type = scrapy.Field()
    length = scrapy.Field()
    width = scrapy.Field()
    height = scrapy.Field()
    wheel = scrapy.Field()
    frontwheel = scrapy.Field()
    backwheel = scrapy.Field()
    liftoff_distance = scrapy.Field()
    weight = scrapy.Field()
    doors = scrapy.Field()
    seats = scrapy.Field()
    fuelvolumn = scrapy.Field()
    baggage = scrapy.Field()
    maxbaggage = scrapy.Field()
    motortype = scrapy.Field()
    cylinder = scrapy.Field()
    method1 = scrapy.Field()
    maxps1 = scrapy.Field()
    maxpower = scrapy.Field()
    maxrpm = scrapy.Field()
    maxnm1 = scrapy.Field()
    maxtorque = scrapy.Field()
    lwv = scrapy.Field()
    lwvnumber = scrapy.Field()
    valve = scrapy.Field()
    compress = scrapy.Field()
    valve_gear = scrapy.Field()
    cylinder_diameter = scrapy.Field()
    cylinder_travel = scrapy.Field()
    motortechnique = scrapy.Field()
    fuletype = scrapy.Field()
    fulevolumn = scrapy.Field()
    fulemethod = scrapy.Field()
    cylinder_head_material = scrapy.Field()
    cylinder_body_material = scrapy.Field()
    emission = scrapy.Field()
    geardesc = scrapy.Field()
    gearnumber = scrapy.Field()
    geartype = scrapy.Field()
    driveway = scrapy.Field()
    frontgauge = scrapy.Field()
    backgauge = scrapy.Field()
    assistanttype = scrapy.Field()
    body_structure = scrapy.Field()
    frontbrake = scrapy.Field()
    backbrake = scrapy.Field()
    parking_brake_type = scrapy.Field()
    frontwheel = scrapy.Field()
    backwheel = scrapy.Field()
    sparewheel = scrapy.Field()
    approach_angle = scrapy.Field()
    departure_angle = scrapy.Field()
    ramp_angle = scrapy.Field()
    climbing_angle = scrapy.Field()
    liftoff_distance1 = scrapy.Field()
    turning_radius = scrapy.Field()
    wading_depth = scrapy.Field()

class QQItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    datasave = scrapy.Field()
    jsonsave = scrapy.Field()
    brandname= scrapy.Field()
    brandid = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    carid=scrapy.Field()
    salesdesc = scrapy.Field()
    carid = scrapy.Field()

class cheshiItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    datasave = scrapy.Field()
    jsonsave = scrapy.Field()
    brandname= scrapy.Field()
    brandid = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    carid=scrapy.Field()
    salesdesc = scrapy.Field()
    price = scrapy.Field()
    makeyear = scrapy.Field()

class iautosItem(scrapy.Item):
        # define the fields for your item here like:
        # name = scrapy.Field()
        url = scrapy.Field()
        website = scrapy.Field()
        grabtime = scrapy.Field()
        status = scrapy.Field()
        datasave = scrapy.Field()
        brandname = scrapy.Field()
        brandid = scrapy.Field()
        factoryname = scrapy.Field()
        factoryid = scrapy.Field()
        familyname = scrapy.Field()
        familyid = scrapy.Field()
        carid = scrapy.Field()
        salesdesc = scrapy.Field()
        price = scrapy.Field()
        saleprice=scrapy.Field()
        price1_north=scrapy.Field()
        price1_east= scrapy.Field()
        price1_west= scrapy.Field()
        price1_south= scrapy.Field()
        comments_good= scrapy.Field()
        comments_bad= scrapy.Field()
        desc= scrapy.Field()
        salesdesc1 = scrapy.Field()
        produceyear = scrapy.Field()
        makeyear = scrapy.Field()
        emission = scrapy.Field()
        bodystyle = scrapy.Field()
        frontwheel_backwheel = scrapy.Field()
        wheel = scrapy.Field()
        weight = scrapy.Field()
        fuelvolumn = scrapy.Field()
        baggage = scrapy.Field()
        doors = scrapy.Field()
        approach_angle = scrapy.Field()
        lengthwh = scrapy.Field()
        frontgauge_backgauge_length = scrapy.Field()
        drag_coef = scrapy.Field()
        maxload = scrapy.Field()
        maxbaggage = scrapy.Field()
        passengers = scrapy.Field()
        departure_angle = scrapy.Field()
        motortechnique = scrapy.Field()
        motordesc = scrapy.Field()
        motortype = scrapy.Field()
        powerL = scrapy.Field()
        compress = scrapy.Field()
        cylinder_travel = scrapy.Field()
        valve = scrapy.Field()
        maxpower = scrapy.Field()
        fueltype = scrapy.Field()
        cylinder = scrapy.Field()
        lwv = scrapy.Field()
        method = scrapy.Field()
        motorfactoryname = scrapy.Field()
        petrol = scrapy.Field()
        cylinder_diameter = scrapy.Field()
        cylinder_head_material = scrapy.Field()
        cylinder_body_material = scrapy.Field()
        maxnm = scrapy.Field()
        fuelmethod = scrapy.Field()
        lwvnumber = scrapy.Field()
        motor_position = scrapy.Field()
        cooling_system = scrapy.Field()
        gear = scrapy.Field()
        driveway = scrapy.Field()
        fronthang = scrapy.Field()
        frontbrake = scrapy.Field()
        geardesc = scrapy.Field()
        frontwheel = scrapy.Field()
        sparewheel = scrapy.Field()
        fronthubtype = scrapy.Field()
        drive_width = scrapy.Field()
        drive_load = scrapy.Field()
        drive_wheel = scrapy.Field()
        transmission_way = scrapy.Field()
        assistanttype = scrapy.Field()
        backhang = scrapy.Field()
        backbrake = scrapy.Field()
        platform = scrapy.Field()
        backwheel = scrapy.Field()
        sparehubtype = scrapy.Field()
        backhubtype = scrapy.Field()
        drive_flat = scrapy.Field()
        drive_speed = scrapy.Field()
        maxspeed = scrapy.Field()
        max_grade_angel = scrapy.Field()
        warranty = scrapy.Field()
        accelerate = scrapy.Field()
        airbag = scrapy.Field()
        brakelength = scrapy.Field()
        jsonsave = scrapy.Field()
        infors = scrapy.Field()


class AutohomeItem_koubei(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    website = scrapy.Field()
    carid = scrapy.Field()
    salesdesc = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    type = scrapy.Field()
    typeid = scrapy.Field()
    familycount = scrapy.Field()
    familyscore = scrapy.Field()
    user_name = scrapy.Field()
    userid = scrapy.Field()
    userlevel = scrapy.Field()
    usercfcar = scrapy.Field()
    url = scrapy.Field()
    status = scrapy.Field()
    post_date = scrapy.Field()
    grabtime = scrapy.Field()
    contentid = scrapy.Field()
    koubeilevel = scrapy.Field()
    ext_dealer = scrapy.Field()
    ext_dealerid = scrapy.Field()
    ext_fuel = scrapy.Field()
    ext_nake_price = scrapy.Field()
    ext_purchase_date = scrapy.Field()
    ext_purchase_place = scrapy.Field()
    ext_purpose = scrapy.Field()
    ext_run = scrapy.Field()
    mouth_content = scrapy.Field()
    mouth_reply_count = scrapy.Field()
    mouth_support_count = scrapy.Field()
    mouth_view_count = scrapy.Field()
    mouth_space = scrapy.Field()
    mouth_power = scrapy.Field()
    mouth_control = scrapy.Field()
    mouth_fuel = scrapy.Field()
    mouth_comfort = scrapy.Field()
    mouth_appearance = scrapy.Field()
    mouth_trim = scrapy.Field()
    mouth_cost_efficient = scrapy.Field()
    score_space = scrapy.Field()
    score_power = scrapy.Field()
    score_control = scrapy.Field()
    score_fuel = scrapy.Field()
    score_comfort = scrapy.Field()
    score_appearance = scrapy.Field()
    score_trim = scrapy.Field()
    score_cost_efficient = scrapy.Field()

class AutohomeItem_easykoubei(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    website = scrapy.Field()
    datasave = scrapy.Field()
    carid = scrapy.Field()
    salesdesc = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    type = scrapy.Field()
    typeid = scrapy.Field()
    familycount = scrapy.Field()
    familyscore = scrapy.Field()
    user_name = scrapy.Field()
    userid = scrapy.Field()
    userlevel = scrapy.Field()
    usercfcar = scrapy.Field()
    url = scrapy.Field()
    status = scrapy.Field()
    post_date = scrapy.Field()
    grabtime = scrapy.Field()
    contentid = scrapy.Field()
    koubeilevel = scrapy.Field()
    ext_dealer = scrapy.Field()
    ext_dealerid = scrapy.Field()
    ext_fuel = scrapy.Field()
    ext_nake_price = scrapy.Field()
    ext_purchase_date = scrapy.Field()
    ext_purchase_place = scrapy.Field()
    ext_purpose = scrapy.Field()
    ext_run = scrapy.Field()
    mouth_content = scrapy.Field()
    mouth_reply_count = scrapy.Field()
    mouth_support_count = scrapy.Field()
    mouth_view_count = scrapy.Field()
    mouth_space = scrapy.Field()
    mouth_power = scrapy.Field()
    mouth_control = scrapy.Field()
    mouth_fuel = scrapy.Field()
    mouth_comfort = scrapy.Field()
    mouth_appearance = scrapy.Field()
    mouth_trim = scrapy.Field()
    mouth_cost_efficient = scrapy.Field()
    score_space = scrapy.Field()
    score_power = scrapy.Field()
    score_control = scrapy.Field()
    score_fuel = scrapy.Field()
    score_comfort = scrapy.Field()
    score_appearance = scrapy.Field()
    score_trim = scrapy.Field()
    score_cost_efficient = scrapy.Field()
    EvalId = scrapy.Field()
    EvalCreated = scrapy.Field()
    LastAppendId = scrapy.Field()
    LastAppendCreated = scrapy.Field()
    maitenance = scrapy.Field()
    fault = scrapy.Field()
    complain = scrapy.Field()

class AutohomeItem_network(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    Key= scrapy.Field()
    prov_ID= scrapy.Field()
    prov_Name= scrapy.Field()
    prov_Pinyin= scrapy.Field()
    prov_Count= scrapy.Field()
    city_ID= scrapy.Field()
    city_Name= scrapy.Field()
    city_Pinyin= scrapy.Field()
    city_Count= scrapy.Field()
    ####key info
    shopname= scrapy.Field()
    shoptype= scrapy.Field()
    shopcolor= scrapy.Field()
    shopstar= scrapy.Field()
    ####salemodel and saleprice
    modelnumber= scrapy.Field()
    mainbrands= scrapy.Field()
    tel= scrapy.Field()
    saleregion=scrapy.Field()
    priceurl= scrapy.Field()
    ####location
    location= scrapy.Field()
    locationurl= scrapy.Field()
    ####promotion
    promotion= scrapy.Field()
    promotionurl= scrapy.Field()
    ####img
    imageurl= scrapy.Field()

class YicheItem(scrapy.Item):
    chexing_id =scrapy.Field()
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    datasave = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    factoryname = scrapy.Field()
    salesdesc = scrapy.Field()
    makeyear = scrapy.Field()
    guideprice = scrapy.Field()
    shangjiabaojia = scrapy.Field()
    market_time = scrapy.Field()
    level = scrapy.Field()
    body = scrapy.Field()
    power_type = scrapy.Field()
    engine = scrapy.Field()
    maximum_power_torque= scrapy.Field()
    gear_type = scrapy.Field()
    hybrid_oil_comsuption = scrapy.Field()
    acceleration_time = scrapy.Field()
    max_speed = scrapy.Field()
    environmental_standard = scrapy.Field()
    warranty_policy = scrapy.Field()
    color = scrapy.Field()
    length = scrapy.Field()
    width = scrapy.Field()
    height = scrapy.Field()
    wheelbase = scrapy.Field()
    curb_weight = scrapy.Field()
    seats_num = scrapy.Field()
    luggage_compartment_volume = scrapy.Field()
    tank_volume = scrapy.Field()
    front_tire_specification = scrapy.Field()
    rear_tire_specification = scrapy.Field()
    spare_tire = scrapy.Field()
    displacement = scrapy.Field()
    maximum_power = scrapy.Field()
    maximum_horsepower = scrapy.Field()
    maximum_power_speed = scrapy.Field()
    maximum_torque = scrapy.Field()
    maximum_torque_speed = scrapy.Field()
    gangtixingshi = scrapy.Field()
    qigangshu = scrapy.Field()
    jinqifangshi = scrapy.Field()
    oil_supply_mode = scrapy.Field()
    fuel_labeling = scrapy.Field()
    engine_start_stop = scrapy.Field()
    gear_type2 = scrapy.Field()
    gears_number = scrapy.Field()
    driving_mode = scrapy.Field()
    front_suspension_type = scrapy.Field()
    rear_suspension_type = scrapy.Field()
    adjustable_suspension = scrapy.Field()
    front_wheel_brake_type = scrapy.Field()
    rear_wheel_brake_type = scrapy.Field()
    parking_brake_type = scrapy.Field()
    body_structure = scrapy.Field()
    differential_gear= scrapy.Field()
    abs = scrapy.Field()
    braking_force_distribution = scrapy.Field()
    brake_assistant = scrapy.Field()
    traction_control = scrapy.Field()
    vehicle_body_stability_control = scrapy.Field()
    main_driving_safety_airbag = scrapy.Field()
    auxiliary_driving_safety_airbag = scrapy.Field()
    front_air_bag = scrapy.Field()
    rear_air_bag = scrapy.Field()
    side_safety_air_curtain = scrapy.Field()
    knee_airbag = scrapy.Field()
    seat_belt_airbag = scrapy.Field()
    rear_central_airbag = scrapy.Field()
    tire_pressure_monitoring = scrapy.Field()
    run_flats = scrapy.Field()
    rear_child_seat_interface = scrapy.Field()
    cruise_control = scrapy.Field()
    lane_keeping = scrapy.Field()
    parallel_auxiliary = scrapy.Field()
    collision_alarm = scrapy.Field()
    fatigue_reminding = scrapy.Field()
    zidongboche = scrapy.Field()
    remote_parking = scrapy.Field()
    automatic_driving_assistance = scrapy.Field()
    zidongzhuche = scrapy.Field()
    shangpofuzhu = scrapy.Field()
    doupohuanjiang = scrapy.Field()
    yeshixitong = scrapy.Field()
    kebianchibizhuanxiang = scrapy.Field()
    qiandaocheleida = scrapy.Field()
    houdaocheleida = scrapy.Field()
    daocheyingxiang = scrapy.Field()
    jiashimoshixuanze = scrapy.Field()
    qiandadeng = scrapy.Field()
    ledrijianxingchedeng = scrapy.Field()
    zidongdadeng = scrapy.Field()
    qianwudeng = scrapy.Field()
    dadenggongneng = scrapy.Field()
    tianchuangleixing = scrapy.Field()
    qiandiandongchechuang = scrapy.Field()
    houdiandongchechuang = scrapy.Field()
    waihoushijingdiandongtiaojie = scrapy.Field()
    neihoushijingzidongfangxuanmu = scrapy.Field()
    liumeitihoushijing = scrapy.Field()
    waihoushijingzidongfangxuanmu = scrapy.Field()
    yinsiboli = scrapy.Field()
    houpaicezheyanglian = scrapy.Field()
    houzheyanglian = scrapy.Field()
    qianyushuaqi = scrapy.Field()
    houyushuaqi = scrapy.Field()
    dianximen = scrapy.Field()
    diandongcehuamen = scrapy.Field()
    diandongxinglixiang = scrapy.Field()
    chedingxinglijia = scrapy.Field()
    zhongkongsuo = scrapy.Field()
    zhinengyaoshi = scrapy.Field()
    yuanchengyaokonggongneng = scrapy.Field()
    weiyi_raoliuban = scrapy.Field()
    yundongwaiguantaojian = scrapy.Field()
    neishicailiao = scrapy.Field()
    cheneifenweideng = scrapy.Field()
    zheyangbanhuazhuangjing = scrapy.Field()
    fangxiangpancaizhi = scrapy.Field()
    duogongnengfangxiangpan = scrapy.Field()
    fangxiangpantiaojie = scrapy.Field()
    fangxiangpanjiare = scrapy.Field()
    fangxiangpanhuandang = scrapy.Field()
    qianpaikongtiao = scrapy.Field()
    houpaikongtiao = scrapy.Field()
    xiangfenxitong = scrapy.Field()
    kongqijinghua = scrapy.Field()
    chezaibingxiang = scrapy.Field()
    zhudongjiangzao = scrapy.Field()
    zuoyicaizhi = scrapy.Field()
    yundongfenggezuoyi = scrapy.Field()
    zhuzuoyidiandongtiaojie = scrapy.Field()
    fuzuoyidiandongtiaojie = scrapy.Field()
    zhuzuoyitiaojiefangshi = scrapy.Field()
    fuzuoyitiaojiefangshi = scrapy.Field()
    dierpaizuoyidiandongtiaojie = scrapy.Field()
    dierpaizuoyitiaojiefangshi = scrapy.Field()
    qianpaizuoyigongneng = scrapy.Field()
    houpaizuoyigongneng = scrapy.Field()
    qianpaizhongyangfushou = scrapy.Field()
    houpaizhongyangfushou = scrapy.Field()
    disanpaizuoyi = scrapy.Field()
    zuoyifangdaofangshi = scrapy.Field()
    houpaibeijiang = scrapy.Field()
    houpaizhediezhuoban = scrapy.Field()
    zhongkongcaiseyejingping = scrapy.Field()
    quanyejingyibiaopan = scrapy.Field()
    xingchediannaoxianshiping = scrapy.Field()
    hudpingshixianshi = scrapy.Field()
    gpsdaohang = scrapy.Field()
    zhinenghuliandingwei = scrapy.Field()
    yuyinkongzhi = scrapy.Field()
    shoujihulian = scrapy.Field()
    shoujiwuxianchongdian = scrapy.Field()
    shoushikongzhixitong = scrapy.Field()
    cd_dvd = scrapy.Field()
    lanya_wifilianjie = scrapy.Field()
    waijiejiekou = scrapy.Field()
    chezaixingchejiluyi = scrapy.Field()
    chezaidianshi = scrapy.Field()
    yinxiangpinpai = scrapy.Field()
    yangshengqishuliang = scrapy.Field()
    houpaiyejingping_yulexitong = scrapy.Field()
    chezai220vdianyuan = scrapy.Field()
    beijing_price = scrapy.Field()


class yichedealeritem(scrapy.Item):
    website= scrapy.Field()
    tel= scrapy.Field()
    shopname = scrapy.Field()
    shopstar = scrapy.Field()
    shoptype= scrapy.Field()
    brandid= scrapy.Field()
    location= scrapy.Field()
    mainbrand= scrapy.Field()
    url = scrapy.Field()
    status = scrapy.Field()
    grabtime = scrapy.Field()
    promotionurl = scrapy.Field()
    saleregeion = scrapy.Field()
    skype= scrapy.Field()
    promotion= scrapy.Field()

class aikadealerItem(scrapy.Item):
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    datasave = scrapy.Field()
    # brandid=scrapy.Field()
    tel=scrapy.Field()
    shopname=scrapy.Field()
    shoptype=scrapy.Field()
    mainbrand=scrapy.Field()
    location=scrapy.Field()
    promotion=scrapy.Field()
    promotionurl=scrapy.Field()
    salesregion=scrapy.Field()


class autohomedealeritem(scrapy.Item):
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    datasave=scrapy.Field()
    tel=scrapy.Field()
    shopname=scrapy.Field()
    shoptype=scrapy.Field()
    mainbrand=scrapy.Field()
    location=scrapy.Field()
    promotion=scrapy.Field()
    promotionurl=scrapy.Field()
    salesregion=scrapy.Field()


class yicheItem_network(scrapy.Item):
    # define the fields for your item here like:
    # com
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    #bf
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    brandurl = scrapy.Field()
    brandnum = scrapy.Field()
    factoryname = scrapy.Field()
    factoryurl = scrapy.Field()
    factorynum = scrapy.Field()
    #city region
    cityId = scrapy.Field()
    regionId = scrapy.Field()
    cityName = scrapy.Field()
    regionName = scrapy.Field()
    cityPinYin = scrapy.Field()
    parentId = scrapy.Field()
    shortName = scrapy.Field()
    cityLevel = scrapy.Field()
    navCityId = scrapy.Field()
    centerCityId = scrapy.Field()
    type = scrapy.Field()
    ####key info
    shopid= scrapy.Field()
    shopname= scrapy.Field()
    shopfullname = scrapy.Field()
    shoptype= scrapy.Field()
    ####salemodel and saleprice
    mainbrands= scrapy.Field()
    tel= scrapy.Field()
    saleregion=scrapy.Field()
    ####location
    location= scrapy.Field()
    locationurl= scrapy.Field()
    ####promotion
    promotion= scrapy.Field()
    promotionurl= scrapy.Field()

class yicheItem_price(scrapy.Item):
    # define the fields for your item here like:
    # com
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    #bf
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    brandurl = scrapy.Field()
    brandnum = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    factorynum = scrapy.Field()
    factoryurl = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    familynum = scrapy.Field()
    familyurl = scrapy.Field()
    #model
    modelid= scrapy.Field()
    model= scrapy.Field()
    #city region
    # cityId = scrapy.Field()
    # regionId = scrapy.Field()
    # cityName = scrapy.Field()
    # regionName = scrapy.Field()
    # cityPinYin = scrapy.Field()
    # parentId = scrapy.Field()
    # shortName = scrapy.Field()
    # cityLevel = scrapy.Field()
    # navCityId = scrapy.Field()
    # centerCityId = scrapy.Field()
    type = scrapy.Field()
    ####key info
    shopid= scrapy.Field()
    shopname= scrapy.Field()
    shopfullname = scrapy.Field()
    shoptype= scrapy.Field()
    ####salemodel and saleprice
    mainbrands= scrapy.Field()
    tel= scrapy.Field()
    tel400 = scrapy.Field()
    saleregion=scrapy.Field()
    ####location
    location= scrapy.Field()
    locationurl= scrapy.Field()
    ####promotion
    promotion= scrapy.Field()
    promotionurl= scrapy.Field()
    #price
    price= scrapy.Field()
    price_district= scrapy.Field()
    price_city= scrapy.Field()
    guideprice = scrapy.Field()

class SuhuagencyItem(scrapy.Item):
    grabtime=scrapy.Field()
    url=scrapy.Field()
    status=scrapy.Field()
    website=scrapy.Field()
    # datasave=scrapy.Field()
    provinceid=scrapy.Field()
    cityid=scrapy.Field()
    cityname=scrapy.Field()
    agencyid=scrapy.Field()
    agencyname=scrapy.Field()
    mainbrand=scrapy.Field()
    telephone=scrapy.Field()
    adress=scrapy.Field()
    shopclass=scrapy.Field()
    mainclass=scrapy.Field()
    seriesclass=scrapy.Field()
    datasave=scrapy.Field()

class AutohomeItem_bfv(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    brandtag = scrapy.Field()
    brandid = scrapy.Field()
    brandname = scrapy.Field()
    factoryid = scrapy.Field()
    factoryname = scrapy.Field()
    factorytag = scrapy.Field()
    familyid = scrapy.Field()
    familyname = scrapy.Field()
    familytag = scrapy.Field()
    status = scrapy.Field()


class autohome_compare(scrapy.Item):
    url = scrapy.Field()
    familyid = scrapy.Field()
    shortdesc = scrapy.Field()
    rank = scrapy.Field()
    grabtime = scrapy.Field()
    comparename = scrapy.Field()
    compareurl = scrapy.Field()
    comparefamilyid = scrapy.Field()
    status = scrapy.Field()

class Autohome_koubei_all(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    picurl = scrapy.Field()
    guideprice = scrapy.Field()
    score_star = scrapy.Field()
    score = scrapy.Field()
    commment_people = scrapy.Field()
    fuel = scrapy.Field()
    score_space = scrapy.Field()
    score_space_compare = scrapy.Field()
    score_power = scrapy.Field()
    score_power_compare = scrapy.Field()
    score_control = scrapy.Field()
    score_control_compare = scrapy.Field()
    score_fuel = scrapy.Field()
    score_fuel_compare = scrapy.Field()
    score_comfort = scrapy.Field()
    score_comfort_compare = scrapy.Field()
    score_appearance = scrapy.Field()
    score_appearance_compare = scrapy.Field()
    score_trim = scrapy.Field()
    score_trim_compare = scrapy.Field()
    score_cost = scrapy.Field()
    score_cost_compare = scrapy.Field()
    familyname = scrapy.Field()
    familynameid = scrapy.Field()
    shortdesc = scrapy.Field()
    autohomeid = scrapy.Field()
    buyername = scrapy.Field()
    buyerid = scrapy.Field()
    buy_location = scrapy.Field()
    buy_date = scrapy.Field()
    buy_pure_price = scrapy.Field()
    oil_consume = scrapy.Field()
    mileage = scrapy.Field()
    score_space = scrapy.Field()
    score_power = scrapy.Field()
    score_control = scrapy.Field()
    score_fuel = scrapy.Field()
    score_comfort = scrapy.Field()
    score_appearance = scrapy.Field()
    score_trim = scrapy.Field()
    score_cost = scrapy.Field()
    usage = scrapy.Field()
    quantity = scrapy.Field()
    isGoodComment = scrapy.Field()
    commentDetail = scrapy.Field()
    status = scrapy.Field()

class Autohomepic(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    brandid = scrapy.Field()
    brandname = scrapy.Field()
    picurl = scrapy.Field()
    purl = scrapy.Field()

class AutohomekoubeiItem(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    shortdesc = scrapy.Field()
    autohomeid = scrapy.Field()
    picurl = scrapy.Field()
    buyerid = scrapy.Field()
    buyername = scrapy.Field()
    buy_location = scrapy.Field()
    buy_date = scrapy.Field()
    buy_pure_price = scrapy.Field()
    status = scrapy.Field()

class AutohomeItem_price(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    website = scrapy.Field()
    Key = scrapy.Field()
    prov_ID = scrapy.Field()
    prov_Name = scrapy.Field()
    prov_Pinyin = scrapy.Field()
    prov_Count = scrapy.Field()
    city_ID = scrapy.Field()
    city_Name = scrapy.Field()
    city_Pinyin = scrapy.Field()
    city_Count = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    shopname = scrapy.Field()
    shopid = scrapy.Field()
    tel = scrapy.Field()
    saleregion = scrapy.Field()
    picurl = scrapy.Field()
    vehilename = scrapy.Field()
    salespricerange = scrapy.Field()
    guidepricerange = scrapy.Field()
    vehilenameid = scrapy.Field()
    salesdesc = scrapy.Field()
    salesdescid = scrapy.Field()
    guideprice = scrapy.Field()
    guidesalesprice = scrapy.Field()
    salesprice = scrapy.Field()
    status = scrapy.Field()

class AutohomeItem_network(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    Key= scrapy.Field()
    prov_ID= scrapy.Field()
    prov_Name= scrapy.Field()
    prov_Pinyin= scrapy.Field()
    prov_Count= scrapy.Field()
    city_ID= scrapy.Field()
    city_Name= scrapy.Field()
    city_Pinyin= scrapy.Field()
    city_Count= scrapy.Field()
    ####key info
    shopname= scrapy.Field()
    shoptype= scrapy.Field()
    shopcolor= scrapy.Field()
    shopstar= scrapy.Field()
    ####salemodel and saleprice
    modelnumber= scrapy.Field()
    mainbrands= scrapy.Field()
    tel= scrapy.Field()
    saleregion=scrapy.Field()
    priceurl= scrapy.Field()
    ####location
    location= scrapy.Field()
    locationurl= scrapy.Field()
    ####promotion
    promotion= scrapy.Field()
    promotionurl= scrapy.Field()
    ####img
    imageurl= scrapy.Field()


#车系总体评论
class yiche_mainpageItem(scrapy.Item):
    website = scrapy.Field()
    url = scrapy.Field()
    status = scrapy.Field()
    grabtime = scrapy.Field()

    brandname = scrapy.Field()
    factoryname = scrapy.Field()
    familyname = scrapy.Field()
    score = scrapy.Field()
    fuel = scrapy.Field()

    Rank = scrapy.Field()
    impressionRed = scrapy.Field()
    impressionBlue = scrapy.Field()
    score_fuel = scrapy.Field()
    score_control = scrapy.Field()

    score_cost = scrapy.Field()
    score_power = scrapy.Field()
    score_config = scrapy.Field()
    score_comfort = scrapy.Field()
    score_space = scrapy.Field()
    score_appearance = scrapy.Field()
    score_trim = scrapy.Field()

class aika_mainpageItem(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()

    brandname = scrapy.Field()
    brandid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()

    level = scrapy.Field()
    segmentRank = scrapy.Field()
    impressionRed = scrapy.Field()
    impressionBlue = scrapy.Field()
    impressionRedNum = scrapy.Field()
    impressionBlueNum = scrapy.Field()
    commentRed = scrapy.Field()
    commentBlue = scrapy.Field()

    score_fuel = scrapy.Field()
    score_quality = scrapy.Field()
    score_config = scrapy.Field()
    score_comfort = scrapy.Field()
    score_detail = scrapy.Field()
    score_drive = scrapy.Field()
    fuel = scrapy.Field()
    quality = scrapy.Field()

    config = scrapy.Field()
    comfort = scrapy.Field()
    detail = scrapy.Field()
    drive = scrapy.Field()

class yicheDetailItem(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    website = scrapy.Field()

    brandname = scrapy.Field()
    factoryname = scrapy.Field()
    familyname = scrapy.Field()
    vehilename = scrapy.Field()
    location = scrapy.Field()
    date = scrapy.Field()
    price = scrapy.Field()
    score = scrapy.Field()
    shortComment = scrapy.Field()
    shopDate = scrapy.Field()
    mileage = scrapy.Field()
    presentOilWear = scrapy.Field()
    impressionRed = scrapy.Field()
    impressionBlue = scrapy.Field()
    isCoodComment = scrapy.Field()

    score_fuel = scrapy.Field()
    score_control = scrapy.Field()
    score_cost_efficient = scrapy.Field()
    score_power = scrapy.Field()
    score_config = scrapy.Field()
    score_comfort = scrapy.Field()
    score_space = scrapy.Field()
    score_appearance = scrapy.Field()
    score_trim = scrapy.Field()
    score_summary = scrapy.Field()

    fuel = scrapy.Field()
    control = scrapy.Field()
    cost_efficient = scrapy.Field()
    power = scrapy.Field()
    config = scrapy.Field()
    comfort = scrapy.Field()
    space = scrapy.Field()
    appearance = scrapy.Field()
    trim = scrapy.Field()
    summary = scrapy.Field()

class aikadetailItem(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    website = scrapy.Field()

    brandname = scrapy.Field()
    brandid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()


    commentAngle = scrapy.Field()
    isUseful = scrapy.Field()
    commentGB = scrapy.Field()
    comment = scrapy.Field()
    detail = scrapy.Field()
    resouce = scrapy.Field()
    reviewer = scrapy.Field()

    commentAngle = scrapy.Field()
    isUseful = scrapy.Field()
    commentGB = scrapy.Field()
    comment = scrapy.Field()
    detail = scrapy.Field()
    resouce = scrapy.Field()
    reviewer = scrapy.Field()


class AutohomeItem(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    autohomeid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    makeyear = scrapy.Field()

    #new add
    vehicle_dimensions = scrapy.Field()
    producestatus=scrapy.Field()
    brandid=scrapy.Field()
    factoryid=scrapy.Field()
    brandname=scrapy.Field()
    factoryname = scrapy.Field()
    nation = scrapy.Field()
    property = scrapy.Field()

    #basic config
    level = scrapy.Field()
    vehicle_warranty = scrapy.Field()
    bodystyle = scrapy.Field()
    salesdesc = scrapy.Field()
    masspeed = scrapy.Field()
    price = scrapy.Field()
    output = scrapy.Field()

    accelerate = scrapy.Field()
    petrol_test = scrapy.Field()
    accelerate_test = scrapy.Field()
    petrol = scrapy.Field()
    ground_distance_test = scrapy.Field()
    engine = scrapy.Field()
    brake_test = scrapy.Field()

    #car body 车身
    length = scrapy.Field()
    baggage = scrapy.Field()
    seats = scrapy.Field()
    min_ground_distance = scrapy.Field()
    doors = scrapy.Field()
    frontgauge = scrapy.Field()
    heigh = scrapy.Field()
    wheelbase = scrapy.Field()
    backgauge = scrapy.Field()
    weigth = scrapy.Field()
    width = scrapy.Field()
    fulevolumn = scrapy.Field()

    #engine 发动机
    fuelmethod = scrapy.Field()
    maxtorque = scrapy.Field()
    maxrpm = scrapy.Field()
    maxps = scrapy.Field()
    fuelnumber = scrapy.Field()
    fueltype = scrapy.Field()
    strokemm = scrapy.Field()
    lwvnumber = scrapy.Field()
    valve = scrapy.Field()
    valve_mechanism = scrapy.Field()
    emission = scrapy.Field()
    boremm = scrapy.Field()
    maxpower = scrapy.Field()
    engine_technology = scrapy.Field()
    lwv = scrapy.Field()
    method = scrapy.Field()
    maxnm = scrapy.Field()
    cylinder_material = scrapy.Field()
    compress = scrapy.Field()
    engine_type = scrapy.Field()
    cylinder = scrapy.Field()
    head_port = scrapy.Field()

    #变速箱
    geartype = scrapy.Field()
    gear = scrapy.Field()
    gearnumber = scrapy.Field()
    geardesc = scrapy.Field()

    #底盘转向
    body_structure = scrapy.Field()
    backhang = scrapy.Field()
    driveway = scrapy.Field()
    fronthang = scrapy.Field()
    assistanttype = scrapy.Field()

    #车轮制动
    parking_brake_type = scrapy.Field()
    frontbrake = scrapy.Field()
    backbrake = scrapy.Field()
    sparewheel = scrapy.Field()
    frontwheel = scrapy.Field()
    backwheel = scrapy.Field()

    #PART II
    #安全装备
    front_back_head_airbag = scrapy.Field()
    central_lock = scrapy.Field()
    keyless_start_system = scrapy.Field()
    safety_belt_is_not_prompt = scrapy.Field()
    engine_electronic_control_unit = scrapy.Field()
    remote_control_key = scrapy.Field()
    zero_tire_pressure = scrapy.Field()
    isofix_child_seat_interface = scrapy.Field()
    knee_airbag = scrapy.Field()
    driver_codrive_airbag = scrapy.Field()
    pke = scrapy.Field()
    tire_pressure_monitoring = scrapy.Field()
    front_back_side_airbag = scrapy.Field()

    #操控配置
    brake_assist_eba_bas_ba = scrapy.Field()
    hill_descent_control = scrapy.Field()
    back_vaq = scrapy.Field()
    vehicle_stability_control_esp_dsc_vsc = scrapy.Field()
    aimatic = scrapy.Field()
    front_vaq = scrapy.Field()
    hill_start_assist = scrapy.Field()
    braking_force_distribution_ebd_cbc = scrapy.Field()
    variable_suspension = scrapy.Field()
    automatic_parking = scrapy.Field()
    limited_slip_differential = scrapy.Field()
    variable_gear_steering_ratio = scrapy.Field()
    traction_control_system_asr_tcs_trc = scrapy.Field()
    abs_antilock = scrapy.Field()

    # 外部配置
    induction_trunk = scrapy.Field()
    electric_sunroof = scrapy.Field()
    hubtype = scrapy.Field()
    panoramic_sunroof = scrapy.Field()
    electric_trunk = scrapy.Field()
    sliding_door = scrapy.Field()
    sport_appearance_suite = scrapy.Field()
    roof_rack = scrapy.Field()
    electric_door = scrapy.Field()

    #内部配置
    computer_screen_of_driving = scrapy.Field()
    steering_wheel_shift = scrapy.Field()
    lhz = scrapy.Field()
    backing_radar = scrapy.Field()
    leather_steering_wheel = scrapy.Field()
    steering_wheel_adjustment = scrapy.Field()
    rear_video_monitor = scrapy.Field()
    memory_code = scrapy.Field()
    steering_wheel_electric_adjustment = scrapy.Field()
    cruise_control = scrapy.Field()
    multi_function_steering_wheel = scrapy.Field()
    lcd_panel = scrapy.Field()
    heads_up_display = scrapy.Field()

    #座椅配置
    sports_seats = scrapy.Field()
    adjustable_seat_height = scrapy.Field()
    third_row_seats = scrapy.Field()
    rear_seat_electric_adjustment = scrapy.Field()
    leather_seats = scrapy.Field()
    adjustable_rear_row_backrest_angle = scrapy.Field()
    rear_seat_down = scrapy.Field()
    rear_row_seat_movement = scrapy.Field()
    seat_armrest = scrapy.Field()
    driver_seat_electric_adjustment = scrapy.Field()
    rear_row_hang_cup = scrapy.Field()
    front_back_seat_heating = scrapy.Field()
    seat_ventilation = scrapy.Field()
    electric_chair_memory = scrapy.Field()
    adjustable_lumbar_support = scrapy.Field()
    massage_seat = scrapy.Field()
    adjustable_shoulder_support = scrapy.Field()

    #多媒体配置
    mp3_audio_support = scrapy.Field()
    bluetooth_car_phone = scrapy.Field()
    speakers_number = scrapy.Field()
    speaker_brand = scrapy.Field()
    rear_lcd_screen = scrapy.Field()
    gps_navigation = scrapy.Field()
    power_supply = scrapy.Field()
    single_cd_player = scrapy.Field()
    onboard_tv = scrapy.Field()
    external_audio_source_connectors = scrapy.Field()
    interactive_location_services = scrapy.Field()
    color_screen_display_control = scrapy.Field()

    # 灯光配置
    steering_headlights = scrapy.Field()
    Headlights_full = scrapy.Field()
    inside_atmosphere_lights = scrapy.Field()
    adjustable_headlight_height = scrapy.Field()
    headlight_cleaning_device = scrapy.Field()
    antifog_ligths = scrapy.Field()
    automatic_headlights = scrapy.Field()
    daytime__lights = scrapy.Field()
    Headlights_dipped = scrapy.Field()
    adaptive_light_distance = scrapy.Field()
    corner_lamp = scrapy.Field()

    #玻璃/后视镜
    rearview_mirror_electric_folding = scrapy.Field()
    rearview_mirror_memory = scrapy.Field()
    window_clip_hand_safety = scrapy.Field()
    rearview_mirror_electric_adjustment = scrapy.Field()
    visor__mirror = scrapy.Field()
    back_privacy_glass = scrapy.Field()
    rearview_mirror_auto_anti_glare = scrapy.Field()
    backglass_sunshade = scrapy.Field()
    windshield_wiper_sensor = scrapy.Field()
    rear_windshield_wiper = scrapy.Field()
    insulating_glass = scrapy.Field()
    backsideglass_sunshade = scrapy.Field()
    rearview_mirror_heating = scrapy.Field()
    front_rear_lectric_windows = scrapy.Field()

    #空调/冰箱
    zone_temperature_control = scrapy.Field()
    rear_ac = scrapy.Field()
    car_refrigerator = scrapy.Field()
    rear_independent_ac = scrapy.Field()
    ac_pollen_filter = scrapy.Field()
    auto_ac = scrapy.Field()

    #高科技配置
    park_assist = scrapy.Field()
    doubling_asisst = scrapy.Field()
    night_vision = scrapy.Field()
    ldws = scrapy.Field()
    adaptive_cruise = scrapy.Field()
    panoramic_camera = scrapy.Field()
    lcd_screen_display_control = scrapy.Field()
    engine_start_stop = scrapy.Field()
    abls = scrapy.Field()
    active_front_steering = scrapy.Field()
    datasave=scrapy.Field()


class autohomemerge(scrapy.Item):
    url=scrapy.Field()
    grabtime=scrapy.Field()
    website=scrapy.Field()
    status=scrapy.Field()
    familyid=scrapy.Field()
    brandid=scrapy.Field()
    producestatus=scrapy.Field()
    brandname=scrapy.Field()
    factoryid=scrapy.Field()
    factoryname=scrapy.Field()

class autohomeaddinfo(scrapy.Item):
    nation = scrapy.Field()
    property = scrapy.Field()
    url = scrapy.Field()
    status = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    grabtime = scrapy.Field()
    factoryname = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    onsale = scrapy.Field()
    offsale = scrapy.Field()

    autohomeid = scrapy.Field()
    factoryid = scrapy.Field()
    makeyear = scrapy.Field()
    salesdesc = scrapy.Field()
    producestatus = scrapy.Field()


class AutohomeCarUpcoming(scrapy.Item):
    grabtime= scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    url = scrapy.Field()
    uptime= scrapy.Field()
    title=scrapy.Field()
    trimid=scrapy.Field()
    shortdesc=scrapy.Field()


class AutohomeCarArrived(scrapy.Item):
    grabtime= scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    url = scrapy.Field()
    produceyear=scrapy.Field()
    arrivedtime= scrapy.Field()
    title=scrapy.Field()
    trimid=scrapy.Field()
    shortdesc=scrapy.Field()
    familyid=scrapy.Field()


class yicheItem_price(scrapy.Item):
    # define the fields for your item here like:
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    #bf
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    brandurl = scrapy.Field()
    brandnum = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    factorynum = scrapy.Field()
    factoryurl = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    familynum = scrapy.Field()
    familyurl = scrapy.Field()
    #model
    modelid= scrapy.Field()
    model= scrapy.Field()
    #city region
    # cityId = scrapy.Field()
    # regionId = scrapy.Field()
    # cityName = scrapy.Field()
    # regionName = scrapy.Field()
    # cityPinYin = scrapy.Field()
    # parentId = scrapy.Field()
    # shortName = scrapy.Field()
    # cityLevel = scrapy.Field()
    # navCityId = scrapy.Field()
    # centerCityId = scrapy.Field()
    type = scrapy.Field()
    ####key info
    shopid= scrapy.Field()
    shopname= scrapy.Field()
    shopfullname = scrapy.Field()
    shoptype= scrapy.Field()
    ####salemodel and saleprice
    mainbrands= scrapy.Field()
    tel= scrapy.Field()
    tel400 = scrapy.Field()
    saleregion=scrapy.Field()
    ####location
    location= scrapy.Field()
    locationurl= scrapy.Field()
    ####promotion
    promotion= scrapy.Field()
    promotionurl= scrapy.Field()
    #price
    price= scrapy.Field()
    price_district= scrapy.Field()
    price_city= scrapy.Field()

    guideprice = scrapy.Field()

class ChinaBiddingInfo(scrapy.Item):
    url = scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    desc=scrapy.Field()
    updatetime=scrapy.Field()
    label=scrapy.Field()

class Haicjcar(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    salesdesc=scrapy.Field()
    # datasave=scrapy.Field()
    No=scrapy.Field()
    Cartype=scrapy.Field()
    price=scrapy.Field()

class PcautoDistributorItem(scrapy.Item):
    url = scrapy.Field()
    website = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    # datasave = scrapy.Field()
    tel = scrapy.Field()
    shopname = scrapy.Field()
    shoptype = scrapy.Field()
    mainbrand = scrapy.Field()
    location = scrapy.Field()
    promotion = scrapy.Field()
    promotionurl = scrapy.Field()
    salesregion = scrapy.Field()
    brandid=scrapy.Field()
    shopstar=scrapy.Field()

class HaicjItem(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    # datasave = scrapy.Field()
    family_name=scrapy.Field()
    factoryname = scrapy.Field()
    salesdesc = scrapy.Field()
    makeyear = scrapy.Field()
    level = scrapy.Field()
    price = scrapy.Field()
    bodystyle = scrapy.Field()
    masspeed = scrapy.Field()
    accelerate = scrapy.Field()
    petrol = scrapy.Field()
    city_oil_consumption = scrapy.Field()
    suburb_oil_consumption = scrapy.Field()
    lenth_width_heigh = scrapy.Field()
    wheelbase = scrapy.Field()
    front_back_gauge = scrapy.Field()
    min_ground_distance = scrapy.Field()
    weigth_and_all_weight = scrapy.Field()
    doors = scrapy.Field()
    seats = scrapy.Field()
    fulevolumn = scrapy.Field()
    baggage = scrapy.Field()
    engine_type = scrapy.Field()
    output = scrapy.Field()
    cylinder_volume = scrapy.Field()
    method = scrapy.Field()
    lwv = scrapy.Field()
    lwvnumber = scrapy.Field()
    valve = scrapy.Field()
    compress = scrapy.Field()
    maxps = scrapy.Field()
    maxpower = scrapy.Field()
    maxrpm = scrapy.Field()
    maxnm = scrapy.Field()
    maxtorque = scrapy.Field()
    engine_technology = scrapy.Field()
    fueltype = scrapy.Field()
    fuelnumber = scrapy.Field()
    fuelmethod = scrapy.Field()
    engine_position = scrapy.Field()
    emission = scrapy.Field()
    gearnumber = scrapy.Field()
    geartype = scrapy.Field()
    geardesc = scrapy.Field()
    steering_resistance_type = scrapy.Field()
    driveway = scrapy.Field()
    fronthang = scrapy.Field()
    backhang = scrapy.Field()
    frontbrake = scrapy.Field()
    backbrake = scrapy.Field()
    frontwheel = scrapy.Field()
    backwheel = scrapy.Field()
    driver_codrive_airbag_major = scrapy.Field()
    driver_codrive_airbag_minor = scrapy.Field()
    front_side_airbag = scrapy.Field()
    back_side_airbag = scrapy.Field()
    front_head_airbag = scrapy.Field()
    back_head_airbag = scrapy.Field()
    knee_airbag = scrapy.Field()
    tire_pressure_monitoring = scrapy.Field()
    zero_tire_pressure = scrapy.Field()
    safety_belt_is_not_prompt = scrapy.Field()
    isofix_child_seat_interface = scrapy.Field()
    latch_seat_interface = scrapy.Field()
    engine_electronic_control_unit = scrapy.Field()
    central_lock = scrapy.Field()
    remote_control_key = scrapy.Field()
    keyless_start_system = scrapy.Field()
    abs_antilock = scrapy.Field()
    braking_force_distribution_ebd_cbc = scrapy.Field()
    brake_assist_eba_bas_ba = scrapy.Field()
    traction_control_system_asr_tcs_trc = scrapy.Field()
    vehicle_stability_control_esp_dsc_vsc = scrapy.Field()
    hill_start_assist_and_auto_parking = scrapy.Field()
    hill_descent_control = scrapy.Field()
    variable_suspension = scrapy.Field()
    aimatic = scrapy.Field()
    variable_gear_steering_ratio = scrapy.Field()
    active_steering_system = scrapy.Field()
    electric_sunroof = scrapy.Field()
    panoramic_sunroof = scrapy.Field()
    sport_appearance_suite = scrapy.Field()
    electric_door = scrapy.Field()
    electric_trunk = scrapy.Field()
    leather_steering_wheel = scrapy.Field()
    steering_up_and_down = scrapy.Field()
    steering_front_and_back = scrapy.Field()
    steering_wheel_electric_adjustment = scrapy.Field()
    multi_function_steering_wheel = scrapy.Field()
    steering_wheel_shift = scrapy.Field()
    cruise_control = scrapy.Field()
    parking_assistance = scrapy.Field()
    rear_video_monitor = scrapy.Field()
    computer_screen_of_driving = scrapy.Field()
    heads_up_display = scrapy.Field()
    abls = scrapy.Field()
    doubling_asisst = scrapy.Field()
    leather_seat = scrapy.Field()
    sports_seats = scrapy.Field()
    adjustable_seat_height = scrapy.Field()
    adjustable_lumbar_support = scrapy.Field()
    adjustable_shoulder_support = scrapy.Field()
    seat_electric_adjustment_major = scrapy.Field()
    seat_electric_adjustment_minor = scrapy.Field()
    adjustable_rear_row_backrest_angle_ = scrapy.Field()
    rear_row_seat_movement = scrapy.Field()
    rear_seat_electric_adjustment = scrapy.Field()
    electric_chair_memory = scrapy.Field()
    front_seat_heating = scrapy.Field()
    back_seat_heating = scrapy.Field()
    seat_ventilation = scrapy.Field()
    massage_seat = scrapy.Field()
    third_row_seats = scrapy.Field()
    rear_seat_down = scrapy.Field()
    rear_seat_proportion_down = scrapy.Field()
    front_seat_armrest = scrapy.Field()
    back_seat_armrest = scrapy.Field()
    rear_row_hang_cup = scrapy.Field()
    gps_navigation = scrapy.Field()
    interactive_location_services = scrapy.Field()
    color_screen_display_control = scrapy.Field()
    human_computer_interaction_system = scrapy.Field()
    built_in_hard_disk = scrapy.Field()
    bluetooth_car_phone = scrapy.Field()
    onboard_tv = scrapy.Field()
    rear_lcd_screen = scrapy.Field()
    external_audio_source_connectors = scrapy.Field()
    mp3_audio_support = scrapy.Field()
    single_cd_player = scrapy.Field()
    multi_cd_player = scrapy.Field()
    virtual_multi_cd_player = scrapy.Field()
    single_dvd_player = scrapy.Field()
    multi_dvd_player = scrapy.Field()
    speakers_number = scrapy.Field()
    xenon_headlight = scrapy.Field()
    led_headlight = scrapy.Field()
    daytime__lights = scrapy.Field()
    automatic_headlights = scrapy.Field()
    steering_headlights_or_auxiliary = scrapy.Field()
    antifog_ligths = scrapy.Field()
    adjustable_headlight_height = scrapy.Field()
    headlight_cleaning_device = scrapy.Field()
    inside_atmosphere_lights = scrapy.Field()
    front_lectric_windows = scrapy.Field()
    rear_lectric_windows = scrapy.Field()
    window_clip_hand_safety = scrapy.Field()
    insulating_glass = scrapy.Field()
    rearview_mirror_electric_adjustment = scrapy.Field()
    rearview_mirror_heating = scrapy.Field()
    rearview_mirror_auto_anti_glare = scrapy.Field()
    rearview_mirror_electric_folding = scrapy.Field()
    rearview_mirror_memory = scrapy.Field()
    backglass_sunshade = scrapy.Field()
    backsideglass_sunshade = scrapy.Field()
    visor__mirror = scrapy.Field()
    rear_windshield_wiper = scrapy.Field()
    windshield_wiper_sensor = scrapy.Field()
    air_conditioner = scrapy.Field()
    auto_air_conditioner = scrapy.Field()
    rear_independent_ac = scrapy.Field()
    rear_ac = scrapy.Field()
    zone_temperature_control = scrapy.Field()
    ac_pollen_filter = scrapy.Field()
    car_refrigerator = scrapy.Field()

class Okcis(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    desc = scrapy.Field()
    updatetime = scrapy.Field()
    label = scrapy.Field()




class BidNewsInfo(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    desc = scrapy.Field()
    updatetime = scrapy.Field()

class AutohomeItem_complete(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    autohomeid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    makeyear = scrapy.Field()
    vehicle_dimensions=scrapy.Field()
    factoryname=scrapy.Field()

    #basic config
    level = scrapy.Field()
    vehicle_warranty = scrapy.Field()
    bodystyle = scrapy.Field()
    salesdesc = scrapy.Field()
    masspeed = scrapy.Field()
    price = scrapy.Field()
    output = scrapy.Field()

    accelerate = scrapy.Field()
    petrol_test = scrapy.Field()
    accelerate_test = scrapy.Field()
    petrol = scrapy.Field()
    ground_distance_test = scrapy.Field()
    engine = scrapy.Field()
    brake_test = scrapy.Field()

    #car body 车身
    length = scrapy.Field()
    baggage = scrapy.Field()
    seats = scrapy.Field()
    min_ground_distance = scrapy.Field()
    doors = scrapy.Field()
    frontgauge = scrapy.Field()
    heigh = scrapy.Field()
    wheelbase = scrapy.Field()
    backgauge = scrapy.Field()
    weigth = scrapy.Field()
    width = scrapy.Field()
    fulevolumn = scrapy.Field()

    #engine 发动机
    fuelmethod = scrapy.Field()
    maxtorque = scrapy.Field()
    maxrpm = scrapy.Field()
    maxps = scrapy.Field()
    fuelnumber = scrapy.Field()
    fueltype = scrapy.Field()
    strokemm = scrapy.Field()
    lwvnumber = scrapy.Field()
    valve = scrapy.Field()
    valve_mechanism = scrapy.Field()
    emission = scrapy.Field()
    boremm = scrapy.Field()
    maxpower = scrapy.Field()
    engine_technology = scrapy.Field()
    lwv = scrapy.Field()
    method = scrapy.Field()
    maxnm = scrapy.Field()
    cylinder_material = scrapy.Field()
    compress = scrapy.Field()
    engine_type = scrapy.Field()
    cylinder = scrapy.Field()
    head_port = scrapy.Field()

    #变速箱
    geartype = scrapy.Field()
    gear = scrapy.Field()
    gearnumber = scrapy.Field()
    geardesc = scrapy.Field()

    #底盘转向
    body_structure = scrapy.Field()
    backhang = scrapy.Field()
    driveway = scrapy.Field()
    fronthang = scrapy.Field()
    assistanttype = scrapy.Field()

    #车轮制动
    parking_brake_type = scrapy.Field()
    frontbrake = scrapy.Field()
    backbrake = scrapy.Field()
    sparewheel = scrapy.Field()
    frontwheel = scrapy.Field()
    backwheel = scrapy.Field()

    #PART II
    #安全装备
    front_back_head_airbag = scrapy.Field()
    central_lock = scrapy.Field()
    keyless_start_system = scrapy.Field()
    safety_belt_is_not_prompt = scrapy.Field()
    engine_electronic_control_unit = scrapy.Field()
    remote_control_key = scrapy.Field()
    zero_tire_pressure = scrapy.Field()
    isofix_child_seat_interface = scrapy.Field()
    knee_airbag = scrapy.Field()
    driver_codrive_airbag = scrapy.Field()
    pke = scrapy.Field()
    tire_pressure_monitoring = scrapy.Field()
    front_back_side_airbag = scrapy.Field()

    #操控配置
    brake_assist_eba_bas_ba = scrapy.Field()
    hill_descent_control = scrapy.Field()
    back_vaq = scrapy.Field()
    vehicle_stability_control_esp_dsc_vsc = scrapy.Field()
    aimatic = scrapy.Field()
    front_vaq = scrapy.Field()
    hill_start_assist = scrapy.Field()
    braking_force_distribution_ebd_cbc = scrapy.Field()
    variable_suspension = scrapy.Field()
    automatic_parking = scrapy.Field()
    limited_slip_differential = scrapy.Field()
    variable_gear_steering_ratio = scrapy.Field()
    traction_control_system_asr_tcs_trc = scrapy.Field()
    abs_antilock = scrapy.Field()

    # 外部配置
    induction_trunk = scrapy.Field()
    electric_sunroof = scrapy.Field()
    hubtype = scrapy.Field()
    panoramic_sunroof = scrapy.Field()
    electric_trunk = scrapy.Field()
    sliding_door = scrapy.Field()
    sport_appearance_suite = scrapy.Field()
    roof_rack = scrapy.Field()
    electric_door = scrapy.Field()

    #内部配置
    computer_screen_of_driving = scrapy.Field()
    steering_wheel_shift = scrapy.Field()
    lhz = scrapy.Field()
    backing_radar = scrapy.Field()
    leather_steering_wheel = scrapy.Field()
    steering_wheel_adjustment = scrapy.Field()
    rear_video_monitor = scrapy.Field()
    memory_code = scrapy.Field()
    steering_wheel_electric_adjustment = scrapy.Field()
    cruise_control = scrapy.Field()
    multi_function_steering_wheel = scrapy.Field()
    lcd_panel = scrapy.Field()
    heads_up_display = scrapy.Field()

    #座椅配置
    sports_seats = scrapy.Field()
    adjustable_seat_height = scrapy.Field()
    third_row_seats = scrapy.Field()
    rear_seat_electric_adjustment = scrapy.Field()
    leather_seats = scrapy.Field()
    adjustable_rear_row_backrest_angle = scrapy.Field()
    rear_seat_down = scrapy.Field()
    rear_row_seat_movement = scrapy.Field()
    seat_armrest = scrapy.Field()
    driver_seat_electric_adjustment = scrapy.Field()
    rear_row_hang_cup = scrapy.Field()
    front_back_seat_heating = scrapy.Field()
    seat_ventilation = scrapy.Field()
    electric_chair_memory = scrapy.Field()
    adjustable_lumbar_support = scrapy.Field()
    massage_seat = scrapy.Field()
    adjustable_shoulder_support = scrapy.Field()

    #多媒体配置
    mp3_audio_support = scrapy.Field()
    bluetooth_car_phone = scrapy.Field()
    speakers_number = scrapy.Field()
    speaker_brand = scrapy.Field()
    rear_lcd_screen = scrapy.Field()
    gps_navigation = scrapy.Field()
    power_supply = scrapy.Field()
    single_cd_player = scrapy.Field()
    onboard_tv = scrapy.Field()
    external_audio_source_connectors = scrapy.Field()
    interactive_location_services = scrapy.Field()
    color_screen_display_control = scrapy.Field()

    # 灯光配置
    steering_headlights = scrapy.Field()
    Headlights_full = scrapy.Field()
    inside_atmosphere_lights = scrapy.Field()
    adjustable_headlight_height = scrapy.Field()
    headlight_cleaning_device = scrapy.Field()
    antifog_ligths = scrapy.Field()
    automatic_headlights = scrapy.Field()
    daytime__lights = scrapy.Field()
    Headlights_dipped = scrapy.Field()
    adaptive_light_distance = scrapy.Field()
    corner_lamp = scrapy.Field()

    #玻璃/后视镜
    rearview_mirror_electric_folding = scrapy.Field()
    rearview_mirror_memory = scrapy.Field()
    window_clip_hand_safety = scrapy.Field()
    rearview_mirror_electric_adjustment = scrapy.Field()
    visor__mirror = scrapy.Field()
    back_privacy_glass = scrapy.Field()
    rearview_mirror_auto_anti_glare = scrapy.Field()
    backglass_sunshade = scrapy.Field()
    windshield_wiper_sensor = scrapy.Field()
    rear_windshield_wiper = scrapy.Field()
    insulating_glass = scrapy.Field()
    backsideglass_sunshade = scrapy.Field()
    rearview_mirror_heating = scrapy.Field()
    front_rear_lectric_windows = scrapy.Field()

    #空调/冰箱
    zone_temperature_control = scrapy.Field()
    rear_ac = scrapy.Field()
    car_refrigerator = scrapy.Field()
    rear_independent_ac = scrapy.Field()
    ac_pollen_filter = scrapy.Field()
    auto_ac = scrapy.Field()

    #高科技配置
    park_assist = scrapy.Field()
    doubling_asisst = scrapy.Field()
    night_vision = scrapy.Field()
    ldws = scrapy.Field()
    adaptive_cruise = scrapy.Field()
    panoramic_camera = scrapy.Field()
    lcd_screen_display_control = scrapy.Field()
    engine_start_stop = scrapy.Field()
    abls = scrapy.Field()
    active_front_steering = scrapy.Field()

class Pcauto_comments(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    brand=scrapy.Field()
    ext_vehicle_type=scrapy.Field()
    user_name=scrapy.Field()
    appearance=scrapy.Field()
    why_buy=scrapy.Field()
    unsatisfaction=scrapy.Field()
    control_suv=scrapy.Field()
    comfort=scrapy.Field()
    power=scrapy.Field()
    fuel=scrapy.Field()
    space=scrapy.Field()
    trim=scrapy.Field()
    equipment=scrapy.Field()
    score_app=scrapy.Field()
    score_trim=scrapy.Field()
    score_space=scrapy.Field()
    score_equipment=scrapy.Field()
    score_power=scrapy.Field()
    score_control=scrapy.Field()
    score_fuel=scrapy.Field()
    score_comfort=scrapy.Field()


class wechat_autohomeItem(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    shopurl=scrapy.Field()
    wechatid=scrapy.Field()
    title=scrapy.Field()


class PcautoWeiboItem(scrapy.Item):
    grabtime = scrapy.Field()
    url = scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    shopname = scrapy.Field()
    username = scrapy.Field()
    companyname = scrapy.Field()
    follower = scrapy.Field()
    weibonum = scrapy.Field()
    following = scrapy.Field()
    location = scrapy.Field()
    officialweb = scrapy.Field()
    label = scrapy.Field()

class YicheShopItem(scrapy.Item):
    pass


class yicheLocalPriceItem(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    location = scrapy.Field()
    location_id = scrapy.Field()
    discount = scrapy.Field()
    model_id = scrapy.Field()
    family_id = scrapy.Field()
    title = scrapy.Field()
    family_name = scrapy.Field()

class newcar2017Item(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    status = scrapy.Field()
    title = scrapy.Field()
    id = scrapy.Field()
    length = scrapy.Field()
    width = scrapy.Field()
    height = scrapy.Field()
    weight = scrapy.Field()
    gear_weight = scrapy.Field()
    speed = scrapy.Field()
    miles = scrapy.Field()
    ekg = scrapy.Field()
    battery_weight_ratio = scrapy.Field()
    energy_density = scrapy.Field()
    restore_type = scrapy.Field()
    electricity_machine_type = scrapy.Field()
    electricity_machine_detail = scrapy.Field()
    store_energy = scrapy.Field()
