__author__ = 'cagey'

import pymongo
import redis

settings = {
    'MONGODB_USER': 'admin',
    # 'MONGODB_PORT': 1206,
    'MONGODB_PORT': 27017,
    'MONGODB_DB': 'baogang',
    'MONGODB_COLLECTION': 'ouyeel_new',
    'MONGODB_PWD': 'ABCabc123',
    # 'MONGODB_SERVER': '180.167.80.118',
    'MONGODB_SERVER': '192.168.1.92',

}
city_list = ['https://www.xin.com/hefei/s/', 'https://www.xin.com/anqing/s/', 'https://www.xin.com/bengbu/s/',
                  'https://www.xin.com/fuyang/s/', 'https://www.xin.com/huaibei/s/', 'https://www.xin.com/huainan/s/',
                  'https://www.xin.com/luan/s/', 'https://www.xin.com/maanshan/s/', 'https://www.xin.com/tongling/s/',
                  'https://www.xin.com/wuhu/s/', 'https://www.xin.com/xuancheng/s/', 'https://www.xin.com/chuzhou/s/',
                  'https://www.xin.com/bozhou/s/', 'https://www.xin.com/huangshan/s/',
                  'https://www.xin.com/suzhouah/s/', 'https://www.xin.com/beijing/s/', 'https://www.xin.com/fuzhou/s/',
                  'https://www.xin.com/xiamen/s/', 'https://www.xin.com/longyan/s/', 'https://www.xin.com/zhangzhou/s/',
                  'https://www.xin.com/putian/s/', 'https://www.xin.com/quanzhou/s/', 'https://www.xin.com/nanping/s/',
                  'https://www.xin.com/ningde/s/', 'https://www.xin.com/sanming/s/', 'https://www.xin.com/lanzhou/s/',
                  'https://www.xin.com/dingxi/s/', 'https://www.xin.com/pingliang/s/', 'https://www.xin.com/jiuquan/s/',
                  'https://www.xin.com/qingyang/s/', 'https://www.xin.com/wuwei/s/', 'https://www.xin.com/tianshui/s/',
                  'https://www.xin.com/baiyin/s/', 'https://www.xin.com/longnan/s/', 'https://www.xin.com/guangzhou/s/',
                  'https://www.xin.com/shenzhen/s/', 'https://www.xin.com/zhuhai/s/', 'https://www.xin.com/dongguan/s/',
                  'https://www.xin.com/zhongshan/s/', 'https://www.xin.com/shantou/s/',
                  'https://www.xin.com/chaozhou/s/', 'https://www.xin.com/shaoguan/s/',
                  'https://www.xin.com/zhanjiang/s/', 'https://www.xin.com/zhaoqing/s/',
                  'https://www.xin.com/maoming/s/', 'https://www.xin.com/meizhou/s/', 'https://www.xin.com/foshan/s/',
                  'https://www.xin.com/huizhou/s/', 'https://www.xin.com/jiangmen/s/', 'https://www.xin.com/jieyang/s/',
                  'https://www.xin.com/qingyuan/s/', 'https://www.xin.com/yangjiang/s/',
                  'https://www.xin.com/heyuan/s/', 'https://www.xin.com/shanwei/s/', 'https://www.xin.com/nanning/s/',
                  'https://www.xin.com/liuzhou/s/', 'https://www.xin.com/guilin/s/', 'https://www.xin.com/beihai/s/',
                  'https://www.xin.com/baise/s/', 'https://www.xin.com/hezhou/s/', 'https://www.xin.com/hechi/s/',
                  'https://www.xin.com/guigang/s/', 'https://www.xin.com/yulin/s/', 'https://www.xin.com/qinzhou/s/',
                  'https://www.xin.com/wuzhou/s/', 'https://www.xin.com/fangchenggang/s/',
                  'https://www.xin.com/guiyang/s/', 'https://www.xin.com/zunyi/s/', 'https://www.xin.com/bijie/s/',
                  'https://www.xin.com/liupanshui/s/', 'https://www.xin.com/tongren/s/',
                  'https://www.xin.com/haikou/s/', 'https://www.xin.com/sanya/s/',
                  'https://www.xin.com/shijiazhuang/s/', 'https://www.xin.com/tangshan/s/',
                  'https://www.xin.com/xingtai/s/', 'https://www.xin.com/qinhuangdao/s/',
                  'https://www.xin.com/langfang/s/', 'https://www.xin.com/handan/s/', 'https://www.xin.com/hengshui/s/',
                  'https://www.xin.com/cangzhou/s/', 'https://www.xin.com/baoding/s/',
                  'https://www.xin.com/zhangjiakou/s/', 'https://www.xin.com/chengde/s/',
                  'https://www.xin.com/zhengzhou/s/', 'https://www.xin.com/luoyang/s/',
                  'https://www.xin.com/zhoukou/s/', 'https://www.xin.com/xinyang/s/', 'https://www.xin.com/xinxiang/s/',
                  'https://www.xin.com/shangqiu/s/', 'https://www.xin.com/sanmenxia/s/',
                  'https://www.xin.com/puyang/s/', 'https://www.xin.com/nanyang/s/', 'https://www.xin.com/luohe/s/',
                  'https://www.xin.com/jiaozuo/s/', 'https://www.xin.com/kaifeng/s/', 'https://www.xin.com/anyang/s/',
                  'https://www.xin.com/dezhou/s/', 'https://www.xin.com/hebi/s/', 'https://www.xin.com/pingdingshan/s/',
                  'https://www.xin.com/zhumadian/s/', 'https://www.xin.com/xuchang/s/',
                  'https://www.xin.com/haerbin/s/', 'https://www.xin.com/daqing/s/', 'https://www.xin.com/qiqihaer/s/',
                  'https://www.xin.com/jiamusi/s/', 'https://www.xin.com/jixi/s/', 'https://www.xin.com/mudanjiang/s/',
                  'https://www.xin.com/qitaihe/s/', 'https://www.xin.com/yichun/s/', 'https://www.xin.com/heihe/s/',
                  'https://www.xin.com/suihua/s/', 'https://www.xin.com/shuangyashan/s/',
                  'https://www.xin.com/wuhan/s/', 'https://www.xin.com/shiyan/s/', 'https://www.xin.com/xiangyang/s/',
                  'https://www.xin.com/suizhou/s/', 'https://www.xin.com/xiantao/s/',
                  'https://www.xin.com/tianmenshi/s/', 'https://www.xin.com/yichang/s/',
                  'https://www.xin.com/huangshi/s/', 'https://www.xin.com/jingmen/s/',
                  'https://www.xin.com/jingzhou/s/', 'https://www.xin.com/huanggang/s/', 'https://www.xin.com/ezhou/s/',
                  'https://www.xin.com/xianning/s/', 'https://www.xin.com/xiaogan/s/',
                  'https://www.xin.com/qianjiang/s/', 'https://www.xin.com/changsha/s/',
                  'https://www.xin.com/chenzhou/s/', 'https://www.xin.com/changde/s/',
                  'https://www.xin.com/hengyang/s/', 'https://www.xin.com/huaihua/s/', 'https://www.xin.com/loudi/s/',
                  'https://www.xin.com/zhuzhou/s/', 'https://www.xin.com/yueyang/s/', 'https://www.xin.com/xiangtan/s/',
                  'https://www.xin.com/shaoyang/s/', 'https://www.xin.com/yiyang/s/',
                  'https://www.xin.com/zhangjiajie/s/', 'https://www.xin.com/changchun/s/',
                  'https://www.xin.com/jilin/s/', 'https://www.xin.com/tonghua/s/', 'https://www.xin.com/liaoyuan/s/',
                  'https://www.xin.com/baishan/s/', 'https://www.xin.com/baicheng/s/',
                  'https://www.xin.com/songyuan/s/', 'https://www.xin.com/nanjing/s/', 'https://www.xin.com/suzhou/s/',
                  'https://www.xin.com/wuxi/s/', 'https://www.xin.com/changzhou/s/', 'https://www.xin.com/huaian/s/',
                  'https://www.xin.com/lianyungang/s/', 'https://www.xin.com/nantong/s/',
                  'https://www.xin.com/yancheng/s/', 'https://www.xin.com/yangzhou/s/',
                  'https://www.xin.com/zhenjiang/s/', 'https://www.xin.com/taizhou/s/', 'https://www.xin.com/xuzhou/s/',
                  'https://www.xin.com/suqian/s/', 'https://www.xin.com/nanchang/s/', 'https://www.xin.com/shangrao/s/',
                  'https://www.xin.com/pingxiang/s/', 'https://www.xin.com/xinyu/s/', 'https://www.xin.com/yichunjx/s/',
                  'https://www.xin.com/jiujiang/s/', 'https://www.xin.com/ganzhou/s/', 'https://www.xin.com/jian/s/',
                  'https://www.xin.com/jingdezhen/s/', 'https://www.xin.com/fuzhoujx/s/',
                  'https://www.xin.com/siping/s/', 'https://www.xin.com/shenyang/s/', 'https://www.xin.com/dandong/s/',
                  'https://www.xin.com/fushun/s/', 'https://www.xin.com/fuxin/s/', 'https://www.xin.com/huludao/s/',
                  'https://www.xin.com/chaoyang/s/', 'https://www.xin.com/dalian/s/', 'https://www.xin.com/benxi/s/',
                  'https://www.xin.com/anshan/s/', 'https://www.xin.com/jinzhou/s/', 'https://www.xin.com/liaoyang/s/',
                  'https://www.xin.com/yingkou/s/', 'https://www.xin.com/panjin/s/', 'https://www.xin.com/tieling/s/',
                  'https://www.xin.com/huhehaote/s/', 'https://www.xin.com/baotou/s/', 'https://www.xin.com/chifeng/s/',
                  'https://www.xin.com/tongliao/s/', 'https://www.xin.com/wuhai/s/', 'https://www.xin.com/eerduosi/s/',
                  'https://www.xin.com/hulunbeier/s/', 'https://www.xin.com/xilinguolemeng/s/',
                  'https://www.xin.com/wulanchabu/s/', 'https://www.xin.com/alashanmeng/s/',
                  'https://www.xin.com/yinchuan/s/', 'https://www.xin.com/wuzhong/s/', 'https://www.xin.com/guyuan/s/',
                  'https://www.xin.com/shizuishan/s/', 'https://www.xin.com/xining/s/',
                  'https://www.xin.com/haidong/s/', 'https://www.xin.com/jinan/s/', 'https://www.xin.com/qingdao/s/',
                  'https://www.xin.com/yantai/s/', 'https://www.xin.com/weihai/s/', 'https://www.xin.com/weifang/s/',
                  'https://www.xin.com/taian/s/', 'https://www.xin.com/zaozhuang/s/', 'https://www.xin.com/zibo/s/',
                  'https://www.xin.com/dongying/s/', 'https://www.xin.com/heze/s/', 'https://www.xin.com/binzhou/s/',
                  'https://www.xin.com/liaocheng/s/', 'https://www.xin.com/linyi/s/', 'https://www.xin.com/jiningsd/s/',
                  'https://www.xin.com/rizhao/s/', 'https://www.xin.com/laiwu/s/', 'https://www.xin.com/taiyuan/s/',
                  'https://www.xin.com/datong/s/', 'https://www.xin.com/jincheng/s/', 'https://www.xin.com/jinzhong/s/',
                  'https://www.xin.com/linfen/s/', 'https://www.xin.com/changzhi/s/', 'https://www.xin.com/yuncheng/s/',
                  'https://www.xin.com/xinzhou/s/', 'https://www.xin.com/yangquan/s/',
                  'https://www.xin.com/shuozhou/s/', 'https://www.xin.com/lvliang/s/', 'https://www.xin.com/xian/s/',
                  'https://www.xin.com/xianyang/s/', 'https://www.xin.com/weinan/s/', 'https://www.xin.com/yulinsx/s/',
                  'https://www.xin.com/baoji/s/', 'https://www.xin.com/ankang/s/', 'https://www.xin.com/hanzhong/s/',
                  'https://www.xin.com/yanan/s/', 'https://www.xin.com/tongchuan/s/', 'https://www.xin.com/shangluo/s/',
                  'https://www.xin.com/shanghai/s/', 'https://www.xin.com/chengdu/s/',
                  'https://www.xin.com/mianyang/s/', 'https://www.xin.com/suining/s/',
                  'https://www.xin.com/panzhihua/s/', 'https://www.xin.com/yibin/s/', 'https://www.xin.com/zigong/s/',
                  'https://www.xin.com/guangyuan/s/', 'https://www.xin.com/deyang/s/', 'https://www.xin.com/leshan/s/',
                  'https://www.xin.com/nanchong/s/', 'https://www.xin.com/meishan/s/', 'https://www.xin.com/luzhou/s/',
                  'https://www.xin.com/neijiang/s/', 'https://www.xin.com/dazhou/s/', 'https://www.xin.com/guangan/s/',
                  'https://www.xin.com/tianjin/s/', 'https://www.xin.com/shannanshi/s/',
                  'https://www.xin.com/wulumuqi/s/', 'https://www.xin.com/hami/s/', 'https://www.xin.com/tulufan/s/',
                  'https://www.xin.com/shihezishi/s/', 'https://www.xin.com/kunming/s/', 'https://www.xin.com/yuxi/s/',
                  'https://www.xin.com/qujing/s/', 'https://www.xin.com/baoshanshi/s/',
                  'https://www.xin.com/zhaotong/s/', 'https://www.xin.com/lijiang/s/',
                  'https://www.xin.com/hangzhou/s/', 'https://www.xin.com/ningbo/s/', 'https://www.xin.com/wenzhou/s/',
                  'https://www.xin.com/jiaxing/s/', 'https://www.xin.com/jinhua/s/', 'https://www.xin.com/lishui/s/',
                  'https://www.xin.com/huzhou/s/', 'https://www.xin.com/quzhou/s/', 'https://www.xin.com/taizhouzj/s/',
                  'https://www.xin.com/shaoxing/s/', 'https://www.xin.com/zhoushan/s/',
                  'https://www.xin.com/chongqing/s/', 'https://www.xin.com/bayannaoer/s/',
                  'https://www.xin.com/zhongwei/s/', 'https://www.xin.com/yanbianchaoxianzuzizhizhou/s/',
                  'https://www.xin.com/enshitujiazuzizhizhou/s/', 'https://www.xin.com/chongzuo/s/',
                  'https://www.xin.com/liangshanyizuzizhizhou/s/', 'https://www.xin.com/qianxinan/s/',
                  'https://www.xin.com/qiandongnan/s/', 'https://www.xin.com/qiannanbuyizu/s/',
                  'https://www.xin.com/chuxiong/s/', 'https://www.xin.com/honghehanizu/s/',
                  'https://www.xin.com/wenshanzhuangzuzizhizhou/s/',
                  'https://www.xin.com/xishuangbannadaizuzizhizhou/s/', 'https://www.xin.com/dalibaizuzizhizhou/s/',
                  'https://www.xin.com/dehongdaizujingpozuzizhizhou/s/', 'https://www.xin.com/linxiahuizuzizhizhou/s/',
                  'https://www.xin.com/huangnan/s/', 'https://www.xin.com/changjihuizuzizhizhou/s/',
                  'https://www.xin.com/bayinguoleng/s/', 'https://www.xin.com/akesudiqu/s/',
                  'https://www.xin.com/yilihasakezizhizhou/s/']

url_list = ['http://www.baidu.com']
# pool = redis.ConnectionPool(host='192.168.1.241', port=6379)
pool = redis.ConnectionPool(host='192.168.1.92', port=6379, db=15)
con = redis.Redis(connection_pool=pool)
c = con.client()
# c.lpush('che168:start_urls', *url_list)
c.lpush('youxin:start_urls', *city_list)
# p = bytes.decode(p)
# print(p)
con.close()




